// reactOrig/src/caseNoteTracker/fbcntModalReturnListSend.tsx
import React from 'react';
import { fbButton as FbButton } from '../components/fbButton';
import { fbModal as FbModal } from '../components/fbModal';
import type { CntVolume } from './cntStore';
import { FbcntSelectedVolumesReceived } from './fbcntSelectedVolumesReceived';

export function FbcntModalReturnListSend({
  volumes,
  checkedVolumeUuids,
  toggleVolume,
  onSend,
  onCancel,
}: {
  volumes: CntVolume[];
  checkedVolumeUuids: string[];
  toggleVolume: (volumeUuid: string) => void;
  onSend: () => void;
  onCancel: () => void;
}) {
  return (
    <FbModal
      title="Send"
      footer={
        <div style={styles.popupFooter}>
          <FbButton variant="success" onClick={onSend}>Send</FbButton>
          <FbButton variant="danger" onClick={onCancel}>Cancel</FbButton>
        </div>
      }
    >
      <FbcntSelectedVolumesReceived
        volumes={volumes}
        checkedVolumeUuids={checkedVolumeUuids}
        toggleVolume={toggleVolume}
      />
    </FbModal>
  );
}

const styles = {
  popupFooter: {
    display: 'flex',
    gap: '0.5rem',
    justifyContent: 'flex-end',
  } as React.CSSProperties,
};

// svelte/src/caseNoteTracker/FbcntModalReturnListSend.svelte
<script lang="ts">
  import FbButton from '../components/fbButton.svelte';
  import FbModal from '../components/fbModal.svelte';
  import type { CntVolume } from './cntStore';
  import FbcntSelectedVolumesReceived from './FbcntSelectedVolumesReceived.svelte';

  export let volumes: CntVolume[] = [];
  export let checkedVolumeUuids: string[] = [];
  export let toggleVolume: (volumeUuid: string) => void = () => {};
  export let onSend: () => void = () => {};
  export let onCancel: () => void = () => {};
</script>

<FbModal title="Send">
  <FbcntSelectedVolumesReceived {volumes} {checkedVolumeUuids} {toggleVolume} />
  <div class="popup-footer">
    <FbButton variant="success" onClick={onSend}>Send</FbButton>
    <FbButton variant="danger" onClick={onCancel}>Cancel</FbButton>
  </div>
</FbModal>

<style>
  .popup-footer { display: flex; gap: 0.5rem; justify-content: flex-end; margin-top: 1rem; }
</style>
