// src/caseNoteTracker/fbcntUserBadge.tsx
import React from 'react';
import { fbToolTip as FbToolTip } from '../components/fbToolTip';
import type { CntUser } from './cntStore';
import { fbDarkerYellow } from './cntStyles';

export function FbcntUserBadge({ user }: { user: CntUser }) {
  const [active, setActive] = React.useState(false);
  const [tooltipPosition, setTooltipPosition] = React.useState({ x: 0, y: 0 });

  const showTooltip = (element: HTMLElement) => {
    const rect = element.getBoundingClientRect();
    setTooltipPosition({
      x: Math.max(10, Math.min(rect.left, window.innerWidth - 250)),
      y: rect.bottom + 5,
    });
    setActive(true);
  };

  return (
    <>
      <span
        className="fbcntUserBadge"
        style={{ ...styles.badge, backgroundColor: active ? fbDarkerYellow : 'transparent' }}
        onMouseEnter={(event) => showTooltip(event.currentTarget)}
        onMouseLeave={() => setActive(false)}
        onFocus={(event) => showTooltip(event.currentTarget)}
        onBlur={() => setActive(false)}
        tabIndex={0}
      >
        {userInitials(user)}: {user.nadexId}
      </span>
      {active && (
        <FbToolTip
          x={tooltipPosition.x}
          y={tooltipPosition.y}
          text={userTooltipText(user)}
        />
      )}
    </>
  );
}

function userInitials(user: CntUser) {
  return `${user.firstNames.charAt(0)}${user.surname.charAt(0)}`.toUpperCase();
}

function userTooltipText(user: CntUser) {
  return [
    `${user.surname.toUpperCase()}, ${user.firstNames}, ${user.title}`,
    user.role,
    user.facility,
    user.nadexId,
  ].join('\n');
}

const styles = {
  badge: {
    display: 'inline-block',
    borderRadius: '0.2rem',
    padding: '0.05rem 0.2rem',
    outlineOffset: '0.1rem',
  } as React.CSSProperties,
};

// svelte/src/caseNoteTracker/FbcntUserBadge.svelte
<script lang="ts">
  import FbToolTip from '../components/fbToolTip.svelte';
  import type { CntUser } from './cntStore';

  export let user: CntUser;

  $: initials = user ? `${user.firstNames.charAt(0)}${user.surname.charAt(0)}`.toUpperCase() : '';
  $: tooltipText = user ? [
    `${user.surname.toUpperCase()}, ${user.firstNames}, ${user.title}`,
    user.role,
    user.facility,
    user.nadexId,
  ].join('\n') : '';
</script>

{#if user}
  <FbToolTip as="span" className="fbcnt-user-badge" text={tooltipText} tabindex={0}>
    {initials}: {user.nadexId}
  </FbToolTip>
{/if}

<style>
  :global(.fbcnt-user-badge) {
    display: inline-block;
    border-radius: 0.2rem;
    padding: 0.05rem 0.2rem;
    outline-offset: 0.1rem;
  }

  :global(.fbcnt-user-badge:hover),
  :global(.fbcnt-user-badge:focus),
  :global(.fbcnt-user-badge:focus-within) {
    background-color: #fee715;
  }
</style>
