// reactOrig/src/components/fbAuthControls.tsx
import React from 'react';
import { fbUserName as FbUserName } from './fbUserName';

interface AuthControlsProps {
  username: string;
  setUsername?: (value: string) => void;
  onUsernameChange?: (value: string) => void;
  password?: string;
  setPassword?: (value: string) => void;
  onPasswordChange?: (value: string) => void;
  formChanged?: boolean;
  passwordTimeoutRef: React.MutableRefObject<number | null>;
}

export const fbAuthControls: React.FC<AuthControlsProps> = ({
  username,
  setUsername,
  onUsernameChange,
  password = '',
  setPassword,
  onPasswordChange,
  formChanged = true,
  passwordTimeoutRef
}) => {
  const handleUsernameChange = onUsernameChange || setUsername;
  const handlePasswordChange = onPasswordChange || setPassword;

  return (
    <>
      <FbUserName
        value={username}
        onChange={(val) => handleUsernameChange && handleUsernameChange(val)}
        style={{ marginLeft: '0.2rem' }}
      />
      {formChanged && (
        <input
          type="password"
          name="password"
          value={password}
          onChange={(e) => handlePasswordChange && handlePasswordChange(e.target.value)}
          placeholder="Enter password"
          className="fb-bottom-control-password"
          style={{
            display: 'inline-block',
            height: '2.0rem',
            lineHeight: '2rem',
            marginLeft: '0.2rem',
            padding: '0 0.5rem',
            border: '0.1rem solid silver',
            borderRadius: '0.4rem',
            backgroundColor: 'white',
            fontFamily: 'Roboto, sans-serif',
            fontSize: '1rem',
            fontWeight: 400,
            color: 'black'
          }}
          onFocus={(e) => {
            e.target.style.backgroundColor = '#ffffcc';
            // Clear any pending timeout when field is focused
            if (passwordTimeoutRef.current !== null) {
              window.clearTimeout(passwordTimeoutRef.current);
              passwordTimeoutRef.current = null;
            }
          }}
          onBlur={(e) => {
            e.target.style.backgroundColor = 'white';
            const passwordAtBlur = e.currentTarget.value;
            // Set timeout to clear password after 2 seconds
            if (passwordAtBlur && handlePasswordChange) {
              passwordTimeoutRef.current = window.setTimeout(() => {
                handlePasswordChange('');
                passwordTimeoutRef.current = null;
              }, 2000);
            }
          }}
        />
      )}
    </>
  );
};

// src/lib/components/fb/fbAuthControls.svelte
<script lang="ts">
  import FbUserName from './fbUserName.svelte';

  let {
    username = $bindable(''),
    password = $bindable(''),
    formChanged = true,
    onUsernameChange,
    onPasswordChange
  }: {
    username?: string;
    password?: string;
    formChanged?: boolean;
    onUsernameChange?: (value: string) => void;
    onPasswordChange?: (value: string) => void;
  } = $props();

  let passwordTimeout: number | null = null;

  function handleUsernameChange(value: string) {
    username = value;
    onUsernameChange?.(value);
  }

  function handlePasswordChange(value: string) {
    password = value;
    onPasswordChange?.(value);
  }

  function clearPasswordTimeout() {
    if (passwordTimeout !== null) {
      window.clearTimeout(passwordTimeout);
      passwordTimeout = null;
    }
  }
</script>

<FbUserName bind:value={username} onChange={handleUsernameChange} />
{#if formChanged}
  <input
    type="password"
    name="password"
    bind:value={password}
    oninput={(event) => handlePasswordChange(event.currentTarget.value)}
    placeholder="Enter password"
    class="fb-bottom-control-password"
    onfocus={clearPasswordTimeout}
    onblur={(event) => {
      const passwordAtBlur = event.currentTarget.value;
      if (passwordAtBlur) {
        passwordTimeout = window.setTimeout(() => {
          handlePasswordChange('');
          passwordTimeout = null;
        }, 2000);
      }
    }}
  />
{/if}

<style>
  .fb-bottom-control-password {
    display: inline-block;
    height: 2rem;
    line-height: 2rem;
    margin-left: 0.2rem;
    padding: 0 0.5rem;
    border: 0.1rem solid silver;
    border-radius: 0.4rem;
    background-color: white;
    font-family: 'Roboto', sans-serif;
    font-size: 1rem;
    font-weight: 400;
    color: black;
  }

  .fb-bottom-control-password:focus {
    background-color: #ffffcc;
  }
</style>
