// src/components/fbAuthAndSensitivity.tsx
import React from 'react';
import { fbAuthControls as AuthControls } from './fbAuthControls';
import { fbFinalControl as FinalControl } from './fbFinalControl';

interface fbAuthAndSensitivityProps {
  highlySensitive: boolean;
  onHighlySensitiveChange: (checked: boolean) => void;
  finalChecked: boolean;
  onFinalCheckedChange: (checked: boolean) => void;
  requiredFieldsComplete: boolean;
  username: string;
  onUsernameChange: (value: string) => void;
  password?: string;
  onPasswordChange: (value: string) => void;
  formChanged?: boolean;
  passwordTimeoutRef: React.MutableRefObject<number | null>;
}

export const fbAuthAndSensitivity: React.FC<fbAuthAndSensitivityProps> = ({
  highlySensitive,
  onHighlySensitiveChange,
  finalChecked,
  onFinalCheckedChange,
  requiredFieldsComplete,
  username,
  onUsernameChange,
  password = '',
  onPasswordChange,
  formChanged = true,
  passwordTimeoutRef,
}) => {
  return (
    <div className="flex flex-wrap md:flex-nowrap items-center gap-2">
      <label
        className="flex items-center gap-2 bottom-control-item"
        style={{
          border: '0.1rem solid silver',
          borderRadius: '0.4rem',
          display: 'inline-flex',
          alignItems: 'center',
          height: '2.0rem',
          marginLeft: '0.2rem',
          padding: '0 0.5rem',
          backgroundColor: 'white',
          fontFamily: "'Roboto', sans-serif",
          fontSize: '1rem',
          fontWeight: 400,
          color: 'black',
          cursor: 'pointer',
          userSelect: 'none',
        }}
      >
        <input
          type="checkbox"
          checked={highlySensitive}
          onChange={(e) => onHighlySensitiveChange(e.target.checked)}
          style={{
            margin: 0,
            width: '1rem',
            height: '1rem',
            cursor: 'pointer',
            outline: 'none',
            boxShadow: 'none',
          }}
        />
        <span style={{ fontWeight: 300 }}>Highly sensitive</span>
      </label>

      <FinalControl
        checked={finalChecked}
        disabled={!requiredFieldsComplete}
        onChange={onFinalCheckedChange}
        className="bottom-control-final"
        style={{
          marginLeft: '0.2rem',
        }}
      />

      <AuthControls
        username={username}
        password={password}
        onUsernameChange={onUsernameChange}
        onPasswordChange={onPasswordChange}
        formChanged={formChanged}
        passwordTimeoutRef={passwordTimeoutRef}
      />
    </div>
  );
};

// src/lib/components/fb/fbAuthAndSensitivity.svelte
<script lang="ts">
  import FbAuthControls from './fbAuthControls.svelte';
  import FbFinalControl from './fbFinalControl.svelte';

  let {
    highlySensitive = $bindable(false),
    finalChecked = $bindable(false),
    requiredFieldsComplete,
    username = $bindable(''),
    password = $bindable(''),
    formChanged = true,
    onHighlySensitiveChange,
    onFinalCheckedChange,
    onUsernameChange,
    onPasswordChange
  }: {
    highlySensitive?: boolean;
    finalChecked?: boolean;
    requiredFieldsComplete: boolean;
    username?: string;
    password?: string;
    formChanged?: boolean;
    onHighlySensitiveChange?: (checked: boolean) => void;
    onFinalCheckedChange?: (checked: boolean) => void;
    onUsernameChange?: (value: string) => void;
    onPasswordChange?: (value: string) => void;
  } = $props();

  function updateHighlySensitive(event: Event) {
    highlySensitive = (event.currentTarget as HTMLInputElement).checked;
    onHighlySensitiveChange?.(highlySensitive);
  }
</script>

<div class="fb-auth-and-sensitivity">
  <label class="fb-bottom-control-item">
    <input type="checkbox" bind:checked={highlySensitive} onchange={updateHighlySensitive} />
    <span>Highly sensitive</span>
  </label>

  <FbFinalControl
    bind:checked={finalChecked}
    disabled={!requiredFieldsComplete}
    onChange={onFinalCheckedChange}
    class="fb-bottom-control-final"
  />

  <FbAuthControls
    bind:username
    bind:password
    {formChanged}
    {onUsernameChange}
    {onPasswordChange}
  />
</div>

<style>
  .fb-auth-and-sensitivity {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 0.5rem;
  }

  .fb-bottom-control-item {
    border: 0.1rem solid silver;
    border-radius: 0.4rem;
    display: inline-flex;
    align-items: center;
    gap: 0.5rem;
    height: 2rem;
    margin-left: 0.2rem;
    padding: 0 0.5rem;
    background-color: white;
    font-family: 'Roboto', sans-serif;
    font-size: 1rem;
    font-weight: 400;
    color: black;
    cursor: pointer;
    user-select: none;
  }

  .fb-bottom-control-item input {
    margin: 0;
    width: 1rem;
    height: 1rem;
    cursor: pointer;
    outline: none;
    box-shadow: none;
  }

  .fb-bottom-control-item span {
    font-weight: 300;
  }
</style>
