// reactOrig/src/components/fbCheck.tsx
import React from 'react';
import { fbAnimatedSubquestion as FbAnimatedSubquestion } from './fbAnimatedSubquestion';
import { fbGroupRequiredMarkerContext } from './fbGroup';
import { fbQuestionRequiredMarkerContext, fbSubfieldContext } from './fbQuestion';

interface fbCheckProps {
  id?: string;
  name: string;
  value?: string;
  checked: boolean;
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  label: string;
  required?: boolean;
  requiredForAudit?: boolean;
  showRequiredMarkers?: boolean;
  disabled?: boolean;
  children?: React.ReactNode; // For subquestions or nested content
  style?: React.CSSProperties;
  onMouseEnter?: (e: React.MouseEvent<HTMLLabelElement>) => void;
  onMouseLeave?: (e: React.MouseEvent<HTMLLabelElement>) => void;
  onFocus?: (e: React.FocusEvent<HTMLInputElement>) => void;
  onBlur?: (e: React.FocusEvent<HTMLInputElement>) => void;
}

export const fbCheck: React.FC<fbCheckProps> = ({
  id,
  name,
  value,
  checked,
  onChange,
  label,
  required,
  requiredForAudit,
  showRequiredMarkers = true,
  disabled,
  children,
  style,
  onMouseEnter,
  onMouseLeave,
  onFocus,
  onBlur,
}) => {
  const groupOwnsRequiredMarkers = React.useContext(fbGroupRequiredMarkerContext);
  const questionOwnsRequiredMarkers = React.useContext(fbQuestionRequiredMarkerContext);
  const renderRequiredMarkers = showRequiredMarkers && !groupOwnsRequiredMarkers && !questionOwnsRequiredMarkers;

  return (
    <div className="fb-subquestion-wrapper" style={style}>
      <label
        className="flex items-start gap-2 fb-radio-checkbox-item w-full"
        onMouseEnter={onMouseEnter}
        onMouseLeave={onMouseLeave}
        style={{
          paddingTop: 0,
          paddingBottom: 0,
          marginTop: 0,
          marginBottom: 0,
          cursor: 'pointer',
          fontFamily: "'Roboto', sans-serif",
          fontSize: '1rem',
          fontWeight: 300,
          userSelect: 'none',
          display: 'flex',
          alignItems: 'flex-start',
          borderRadius: '0.4rem',
          boxSizing: 'border-box'
        }}
      >
        <input
          id={id}
          type="checkbox"
          name={name}
          value={value}
          checked={checked}
          onChange={onChange}
          required={required}
          disabled={disabled}
          onFocus={onFocus}
          onBlur={onBlur}
          style={{
            cursor: 'pointer',
            flexShrink: 0,
            outline: 'none',
            boxShadow: 'none'
          }}
        />
        <span style={{ fontWeight: 300 }}>
          {label}
          {renderRequiredMarkers && requiredForAudit && <span style={{ backgroundColor: '#fd8a10', color: 'white', fontSize: '0.8rem', fontWeight: 300, lineHeight: 1, marginLeft: '0.1rem', padding: '0.05rem 0.2rem', display: 'inline-block', whiteSpace: 'nowrap' }}>RfA</span>}
          {renderRequiredMarkers && required && <span style={{ color: '#d50000', marginLeft: '0.1rem', fontWeight: 500 }}>*</span>}
        </span>
      </label>
      {children && (
        <FbAnimatedSubquestion open={checked}>
          <fbSubfieldContext.Provider value>
            {children}
          </fbSubfieldContext.Provider>
        </FbAnimatedSubquestion>
      )}
    </div>
  );
};

// src/lib/components/fb/fbCheck.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { getContext, setContext } from 'svelte';
  import { fbGroupRequiredMarkerContextKey, fbQuestionRequiredMarkerContextKey, fbSubfieldContextKey } from './context';
  import FbAnimatedSubquestion from './fbAnimatedSubquestion.svelte';
  import FbRequiredForAudit from './fbRequiredForAudit.svelte';

  let {
    id,
    name,
    value,
    checked = $bindable(false),
    label,
    required = false,
    requiredForAudit = false,
    showRequiredMarkers = true,
    disabled = false,
    children,
    onChange,
    change
  }: {
    id?: string;
    name: string;
    value?: string;
    checked?: boolean;
    label: string;
    required?: boolean;
    requiredForAudit?: boolean;
    showRequiredMarkers?: boolean;
    disabled?: boolean;
    children?: Snippet;
    onChange?: (checked: boolean, event: Event) => void;
    change?: (checked: boolean, event: Event) => void;
  } = $props();

  const groupContext = getContext<{ value: boolean } | undefined>(fbGroupRequiredMarkerContextKey);
  const questionContext = getContext<{ value: boolean } | undefined>(fbQuestionRequiredMarkerContextKey);
  const renderRequiredMarkers = $derived(showRequiredMarkers && !groupContext?.value && !questionContext?.value);
  setContext(fbSubfieldContextKey, { value: true });

  function update(event: Event) {
    checked = (event.currentTarget as HTMLInputElement).checked;
    onChange?.(checked, event);
    change?.(checked, event);
  }
</script>

<div class="fb-subquestion-wrapper">
  <label class="flex items-start gap-2 fb-radio-checkbox-item w-full">
    <input
      {id}
      type="checkbox"
      {name}
      {value}
      bind:checked
      onchange={update}
      {required}
      {disabled}
      data-lily-reference-component="checkbox"
    />
    <span>
      {label}
      {#if renderRequiredMarkers && requiredForAudit}<FbRequiredForAudit />{/if}
      {#if renderRequiredMarkers && required}<span class="fb-required-marker">*</span>{/if}
    </span>
  </label>
  {#if children}
    <FbAnimatedSubquestion open={checked}>
      {@render children()}
    </FbAnimatedSubquestion>
  {/if}
</div>

<style>
  .fb-radio-checkbox-item {
    padding-top: 0;
    padding-bottom: 0;
    margin-top: 0;
    margin-bottom: 0;
    cursor: pointer;
    font-family: 'Roboto', sans-serif;
    font-size: 1rem;
    font-weight: 300;
    user-select: none;
    display: flex;
    align-items: flex-start;
    gap: 0.5rem;
    border-radius: 0.4rem;
    box-sizing: border-box;
  }

  input {
    cursor: pointer;
    flex-shrink: 0;
    outline: none;
    box-shadow: none;
  }

  span {
    font-weight: 300;
  }

  .fb-required-marker {
    color: #d50000;
    margin-left: 0.1rem;
    font-weight: 500;
  }
</style>
