// reactOrig/src/components/fbModalStaleSave.tsx
import React from 'react';
import { fbButton as FbButton } from './fbButton';
import { fbModal as FbModal } from './fbModal';

interface FbModalStaleSaveProps {
  onContinue: () => void;
}

export const fbModalStaleSave: React.FC<FbModalStaleSaveProps> = ({ onContinue }) => (
  <FbModal
    title="Changes NOT saved"
    footer={
      <div style={{ display: 'flex', justifyContent: 'flex-start' }}>
        <FbButton type="button" variant="success" onClick={onContinue}>
          Continue
        </FbButton>
      </div>
    }
  >
    <p style={{ marginBottom: '1.5rem', lineHeight: '1.4', color: '#333333' }}>
      Your changes were not saved, because the document or form was updated by another user (or possibly by yourself in a different window). When you click "Continue", the read-only view of the current version will be displayed.
    </p>
  </FbModal>
);

// src/lib/components/fb/fbModalStaleSave.svelte
<script lang="ts">
  import FbModal from './fbModal.svelte';
  import FbButton from './fbButton.svelte';
  import FbModalActions from './FbModalActions.svelte';

  let { onContinue = () => {} }: { onContinue?: () => void } = $props();
</script>

<FbModal title="Changes NOT saved" onEscape={onContinue}>
  <p>
    Your changes were not saved, because the document or form was updated by another user (or possibly
    by yourself in a different window). When you click "Continue", the read-only view of the current
    version will be displayed.
  </p>
  <FbModalActions><FbButton variant="green" onClick={onContinue}>Continue</FbButton></FbModalActions>
</FbModal>

<style>
  p {
    margin-bottom: 1.5rem;
    line-height: 1.4;
    color: #333333;
    max-width: 38rem;
  }
</style>
