// src/components/fbMSISelector.tsx
import React from 'react';
import { parseServerResponse } from '../utils/shadesOfPaleParser';
import { fbQuestion as FbQuestion, fbQuestionRequiredMarkerContext } from './fbQuestion';
import { fbValueError as FbValueError } from './fbValueError';

interface MSISelectorProps {
  label?: string;
  name: string;
  value: string;
  onChange: (value: string, coded: boolean) => void;
  onFocus?: (e: React.FocusEvent<HTMLInputElement>) => void;
  onBlur?: () => void;
  required?: boolean;
  requiredForAudit?: boolean;
  coded?: boolean;
  placeholder?: string;
  hasLabel?: boolean;
  valueError?: string;
  labelStyle?: React.CSSProperties;
  subfield?: boolean;
}

export const fbMSISelector: React.FC<MSISelectorProps> = ({ 
  label,
  name, 
  value, 
  onChange, 
  onFocus, 
  onBlur, 
  required, 
  requiredForAudit,
  coded,
  placeholder = "Type to search staff index",
  hasLabel = true,
  valueError,
  labelStyle,
  subfield = false
}) => {
  const questionOwnsRequiredMarkers = React.useContext(fbQuestionRequiredMarkerContext);
  const renderRequiredMarkers = !questionOwnsRequiredMarkers;
  const [searchTerm, setSearchTerm] = React.useState<string>(value);
  const [results, setResults] = React.useState<Array<{score: number, ie: {line: string}}>>([]);
  const [showDropdown, setShowDropdown] = React.useState<boolean>(false);
  const [isLoading, setIsLoading] = React.useState<boolean>(false);
  const [highlightedIndex, setHighlightedIndex] = React.useState<number>(-1);
  const [dropdownLeft, setDropdownLeft] = React.useState<number>(0);
  const [dropdownTop, setDropdownTop] = React.useState<number>(0);
  const [dropdownMaxHeight, setDropdownMaxHeight] = React.useState<number>(300);
  const [justSelected, setJustSelected] = React.useState<boolean>(false);
  const [hasInteracted, setHasInteracted] = React.useState<boolean>(false);
  const [lastSelectedValue, setLastSelectedValue] = React.useState<string>(value);

  React.useEffect(() => {
    if (value !== searchTerm) {
      setSearchTerm(value);
      setLastSelectedValue(value);
    }
  }, [value]);
  const inputRef = React.useRef<HTMLInputElement>(null);
  const dropdownRef = React.useRef<HTMLDivElement>(null);
  const containerRef = React.useRef<HTMLDivElement>(null);

  const performSearch = () => {
    if (searchTerm.length > 0) {
      setIsLoading(true);
      const authHeader = 'Basic ' + btoa('dhcw:dhcw');

      fetch(`https://www.shadesofpale.net/MSISearch?st=${encodeURIComponent(searchTerm)}`, {
        method: 'GET',
        headers: {
          'Authorization': authHeader,
          'Accept': 'application/json'
        }
      })
        .then(response => response.text())
        .then(text => {
          try {
            const data = parseServerResponse(text);
            setResults(data || []);
            if (hasInteracted) {
              setShowDropdown(true);
            }
            setHighlightedIndex(-1);
          } catch (e) {
            console.error('Failed to parse response:', e);
            setResults([]);
          }
          setIsLoading(false);
        })
        .catch(error => {
          console.error('MSISearch error:', error);
          setResults([]);
          setIsLoading(false);
        });
    } else {
      setResults([]);
      setShowDropdown(false);
      setHighlightedIndex(-1);
    }
  };

  React.useEffect(() => {
    if (!justSelected) {
      performSearch();
    }
  }, [searchTerm]);

  const updateDropdownPosition = React.useCallback(() => {
    if (containerRef.current) {
      const dropdownWidthPx = 45 * 16;
      const maxDropdownWidth = Math.min(dropdownWidthPx, window.innerWidth - 40);
      const containerRect = containerRef.current.getBoundingClientRect();

      const spaceBelow = window.innerHeight - containerRect.bottom - 20;
      const spaceAbove = containerRect.top - 20;
      const preferredHeight = 300;

      let topPos: number;
      let maxHeight: number;

      if (spaceBelow >= preferredHeight || spaceBelow >= spaceAbove) {
        topPos = containerRect.bottom + 2;
        maxHeight = Math.min(preferredHeight, Math.max(100, spaceBelow));
      } else {
        maxHeight = Math.min(preferredHeight, Math.max(100, spaceAbove));
        topPos = containerRect.top - maxHeight - 2;
      }

      setDropdownTop(topPos);
      setDropdownMaxHeight(maxHeight);

      const dropdownRight = containerRect.left + maxDropdownWidth;

      if (dropdownRight > window.innerWidth) {
        const shift = dropdownRight - window.innerWidth + 20;
        setDropdownLeft(containerRect.left - shift);
      } else {
        setDropdownLeft(containerRect.left);
      }
    }
  }, []);

  React.useEffect(() => {
    if (showDropdown && results.length > 0) {
      setHighlightedIndex(-1);
      updateDropdownPosition();

      const scrollContainer = document.querySelector('.flex-1.overflow-y-auto');
      if (scrollContainer) {
        scrollContainer.addEventListener('scroll', updateDropdownPosition);
        return () => {
          scrollContainer.removeEventListener('scroll', updateDropdownPosition);
        };
      }
    } else if (!showDropdown) {
      setHighlightedIndex(-1);
    }
  }, [showDropdown, results, updateDropdownPosition]);

  const handleSelect = (line: string) => {
    setJustSelected(true);
    setSearchTerm(line);
    onChange(line, true);
    setShowDropdown(false);
    setHighlightedIndex(-1);
    setLastSelectedValue(line);
    setTimeout(() => setJustSelected(false), 100);
  };

  const handleClear = () => {
    setSearchTerm('');
    onChange('', false);
    setShowDropdown(false);
    setResults([]);
    setHighlightedIndex(-1);
    setLastSelectedValue('');
    if (inputRef.current) {
      inputRef.current.focus();
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Escape') {
      e.preventDefault();
      setShowDropdown(false);
      setHighlightedIndex(-1);
      return;
    }

    if (!showDropdown || results.length === 0) return;

    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setHighlightedIndex(prev => {
        if (prev === -1) return 0;
        return Math.min(prev + 1, results.length - 1);
      });
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setHighlightedIndex(prev => {
        return Math.max(prev - 1, -1);
      });
    } else if (e.key === 'Enter' && highlightedIndex >= 0) {
      e.preventDefault();
      handleSelect(results[highlightedIndex].ie.line);
    }
  };

  const renderContent = () => {
    return (
      <div style={{display: 'flex', alignItems: 'center', width: '100%', gap: '0.3rem'}}>
        <div ref={containerRef} style={{position: 'relative', flex: 1}}>
          <div style={{position: 'relative', display: 'flex', alignItems: 'center'}}>
            <input
              ref={inputRef}
              type="text"
              name={name}
              value={searchTerm}
              onChange={(e) => {
                setHasInteracted(true);
                setSearchTerm(e.target.value);
                onChange(e.target.value, false);
              }}
              onFocus={(e) => {
                setHasInteracted(true);
                if (results.length > 0 && !justSelected) setShowDropdown(true);
                if (onFocus) onFocus(e);
              }}
              onBlur={() => {
                setTimeout(() => {
                  setShowDropdown(false);
                  if (onBlur) onBlur();
                }, 200);
              }}
              onKeyDown={handleKeyDown}
              className="w-full p-2 fb-hide-border-in-rov fb-msi-selector-input"
              style={{
                border: '0.1rem solid silver',
                borderRadius: '0.4rem',
                paddingRight: '2.5rem',
                height: '2rem',
                boxSizing: 'border-box',
                backgroundColor: 'white'
              }}
              required={required}
              placeholder={placeholder}
              autoComplete="off"
            />
            <div style={{
              position: 'absolute',
              right: '0.2rem',
              display: 'flex',
              gap: '0.1rem',
              alignItems: 'center'
            }}>
              {searchTerm && (
                <button
                  type="button"
                  onClick={handleClear}
                  onMouseDown={(e) => e.preventDefault()}
                  style={{
                    border: 'none',
                    background: 'none',
                    cursor: 'pointer',
                    color: '#666',
                    fontSize: '0.9rem',
                    padding: '0.1rem',
                    lineHeight: 1
                  }}
                >
                  ✕
                </button>
              )}
              <button
                type="button"
                onClick={() => {
                  setHasInteracted(true);
                  if (showDropdown) {
                    setShowDropdown(false);
                    setHighlightedIndex(-1);
                  } else {
                    setHighlightedIndex(-1);
                    if (results.length > 0) {
                      setShowDropdown(true);
                    } else {
                      performSearch();
                    }
                  }
                }}
                onMouseDown={(e) => e.preventDefault()}
                style={{
                  border: 'none',
                  background: 'none',
                  cursor: 'pointer',
                  color: '#666',
                  fontSize: '1rem',
                  padding: '0.1rem',
                  lineHeight: 1
                }}
              >
                {showDropdown ? '▲' : '▼'}
              </button>
            </div>
          </div>
          {showDropdown && results.length > 0 && (
            <div
              ref={dropdownRef}
              style={{
                position: 'fixed',
                top: `${dropdownTop}px`,
                left: `${dropdownLeft}px`,
                width: '45rem',
                maxWidth: '100vw',
                maxHeight: `${dropdownMaxHeight}px`,
                overflowY: 'auto',
                overflowX: 'auto',
                backgroundColor: 'white',
                border: '0.1rem solid silver',
                borderRadius: '0.4rem',
                zIndex: 10000,
                boxShadow: '0 2px 8px rgba(0,0,0,0.15)'
              }}
            >
              {results.map((result, index) => (
                <div
                  key={index}
                  onMouseDown={() => handleSelect(result.ie.line)}
                  onMouseEnter={() => setHighlightedIndex(index)}
                  style={{
                    padding: '0.2rem 0.5rem',
                    cursor: 'pointer',
                    fontSize: '0.9rem',
                    whiteSpace: 'nowrap',
                    backgroundColor: highlightedIndex === index ? '#ffffcc' : 'white',
                    transition: 'background-color 0.2s',
                    lineHeight: '1.2'
                  }}
                >
                  {result.ie.line}
                </div>
              ))}
            </div>
          )}
          {isLoading && (
            <div style={{
              position: 'absolute',
              right: '2.5rem',
              top: '50%',
              transform: 'translateY(-50%)',
              fontSize: '0.8rem',
              color: '#666'
            }}>
              Searching...
            </div>
          )}
        </div>
        {searchTerm && (coded !== undefined ? coded : (searchTerm === lastSelectedValue)) && (
          <span className="material-icons" style={{
            color: '#008000',
            fontSize: '1.2rem'
          }} title="Coded">
            check_circle_outline
          </span>
        )}
        {searchTerm && !(coded !== undefined ? coded : (searchTerm === lastSelectedValue)) && (
          <span className="material-icons" style={{
            color: '#fd8a10',
            fontSize: '1.2rem'
          }} title="Not coded">
            warning
          </span>
        )}
      </div>
    );
  };

  const renderWithStandaloneValueError = (content: React.ReactNode) => {
    if (!valueError) return content;
    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.2rem', width: '100%' }}>
        <FbValueError message={valueError} />
        {content}
      </div>
    );
  };

  if (label) {
    return (
      <FbQuestion label={label} required={required} requiredForAudit={requiredForAudit} valueError={valueError} labelStyle={{ ...(subfield ? { fontWeight: 300, fontSize: '1rem' } : {}), ...labelStyle }}>
        {renderContent()}
      </FbQuestion>
    );
  }

  if ((required || requiredForAudit) && !hasLabel) {
    if (!renderRequiredMarkers) return renderWithStandaloneValueError(renderContent());
    return renderWithStandaloneValueError(
      <div style={{ display: 'flex', alignItems: 'flex-start', gap: '0.2rem', width: '100%', boxSizing: 'border-box' }}>
        <div style={{ flex: 1, width: '100%' }}>
          {renderContent()}
        </div>
        <span style={{ display: 'inline-flex', alignItems: 'flex-start', gap: '0.1rem', marginTop: '0.15rem' }}>
          {requiredForAudit && <span style={{ backgroundColor: '#fd8a10', color: 'white', fontSize: '0.8rem', fontWeight: 300, lineHeight: 1, padding: '0.05rem 0.2rem', display: 'inline-block', whiteSpace: 'nowrap' }}>RfA</span>}
          {required && <span style={{ color: '#d50000', fontSize: '1rem', fontWeight: 'bold', lineHeight: '1.2rem', display: 'inline-block', userSelect: 'none' }}>*</span>}
        </span>
      </div>
    );
  }

  return renderWithStandaloneValueError(renderContent());
};

// src/lib/components/fb/fbMSISelector.svelte
<script lang="ts">
  import FbQuestion from './fbQuestion.svelte';
  import { parseServerResponse } from '$lib/utils/shadesOfPaleParser';

  type StaffResult = {
    display?: string;
    name?: string;
    fullName?: string;
    id?: string;
    code?: string;
    jobTitle?: string;
    specialty?: string;
    ie?: { line?: string };
    nadexId?: string;
    NADEXId?: string;
  };

  let {
    id = '',
    name,
    label = '',
    value = $bindable(''),
    required = false,
    requiredForAudit = false,
    coded,
    valueError = '',
    subfield = false,
    placeholder = 'Type to search staff index',
    readonly = false,
    onChange,
    change
  }: {
    id?: string;
    name: string;
    label?: string;
    value?: string;
    required?: boolean;
    requiredForAudit?: boolean;
    coded?: boolean;
    valueError?: string;
    subfield?: boolean;
    placeholder?: string;
    readonly?: boolean;
    onChange?: (value: string, coded: boolean, nadexId?: string) => void;
    change?: (value: string, coded: boolean, nadexId?: string) => void;
  } = $props();

  let searchText = $state(value || '');
  let localCoded = $state(Boolean(value));
  let isOpen = $state(false);
  let isSearching = $state(false);
  let error = $state('');
  let results = $state<StaffResult[]>([]);
  let highlightedIndex = $state(-1);
  let selectorElement = $state<HTMLDivElement | undefined>();
  let popupTop = $state(0);
  let popupLeft = $state(0);
  let popupWidth = $state(0);
  let popupMaxHeight = $state(320);
  let scrollParents: Array<Window | HTMLElement> = [];
  let popupListenersAttached = false;
  let searchTimer: number | undefined = undefined;
  let blurTimer: number | undefined = undefined;

  const effectiveCoded = $derived(coded !== undefined ? coded : localCoded);
  const inputId = $derived(id || `${name}-msi-input`);
  const popupId = $derived(`${inputId}-results`);
  const activeOptionId = $derived(isOpen && highlightedIndex >= 0 ? `${popupId}-option-${highlightedIndex}` : undefined);

  $effect(() => {
    if (value !== searchText && !isOpen) {
      searchText = value || '';
      localCoded = Boolean(value);
    }
  });

  function displayFor(result: StaffResult) {
    return result.display || result.name || result.fullName || result.ie?.line || result.id || result.code || '';
  }

  function nadexIdFor(result: StaffResult) {
    const direct = result.id || result.code || result.nadexId || result.NADEXId || '';
    if (direct) return direct;
    const line = displayFor(result);
    const nadexMatch = line.match(/\bNADEX\s*:?\s*([A-Za-z0-9._-]+)/i);
    if (nadexMatch) return nadexMatch[1];
    const bracketedId = line.match(/\(([A-Za-z]{1,6}\d{2,})\)/);
    return bracketedId ? bracketedId[1] : '';
  }

  function detailFor(result: StaffResult) {
    return [result.jobTitle, result.specialty, result.code || result.id].filter(Boolean).join(' - ');
  }

  function emit(nextValue: string, nextCoded: boolean, nadexId = '') {
    value = nextValue;
    onChange?.(nextValue, nextCoded, nadexId);
    change?.(nextValue, nextCoded, nadexId);
  }

  function updatePopupPosition() {
    if (!selectorElement) return;
    const rect = selectorElement.getBoundingClientRect();
    const edgeGap = 12;
    const preferredWidth = 45 * 16;
    const preferredHeight = 320;
    const spaceBelow = window.innerHeight - rect.bottom - edgeGap;
    const spaceAbove = rect.top - edgeGap;
    popupWidth = Math.min(preferredWidth, Math.max(rect.width, window.innerWidth - (edgeGap * 2)));
    popupMaxHeight = Math.min(preferredHeight, Math.max(120, spaceBelow >= spaceAbove ? spaceBelow : spaceAbove));
    popupTop = spaceBelow >= preferredHeight || spaceBelow >= spaceAbove ? rect.bottom + 2 : Math.max(edgeGap, rect.top - popupMaxHeight - 2);
    popupLeft = Math.min(rect.left, window.innerWidth - popupWidth - edgeGap);
    if (popupLeft < edgeGap) popupLeft = edgeGap;
  }

  function collectScrollParents(element: HTMLElement) {
    const parents: Array<Window | HTMLElement> = [window];
    let current = element.parentElement;
    while (current) {
      const style = window.getComputedStyle(current);
      if (/(auto|scroll|overlay)/.test(`${style.overflow}${style.overflowY}${style.overflowX}`)) parents.push(current);
      current = current.parentElement;
    }
    return parents;
  }

  function attachPopupListeners() {
    if (popupListenersAttached || !selectorElement) return;
    scrollParents = collectScrollParents(selectorElement);
    for (const parent of scrollParents) parent.addEventListener('scroll', updatePopupPosition, { passive: true });
    window.addEventListener('resize', updatePopupPosition);
    popupListenersAttached = true;
  }

  function detachPopupListeners() {
    if (!popupListenersAttached) return;
    for (const parent of scrollParents) parent.removeEventListener('scroll', updatePopupPosition);
    window.removeEventListener('resize', updatePopupPosition);
    scrollParents = [];
    popupListenersAttached = false;
  }

  $effect(() => {
    if (isOpen) {
      updatePopupPosition();
      attachPopupListeners();
    } else {
      detachPopupListeners();
    }
  });

  async function searchStaff(term: string) {
    if (readonly) return;
    const trimmed = term.trim();
    if (trimmed.length < 1) {
      results = [];
      isOpen = false;
      return;
    }

    try {
      isSearching = true;
      isOpen = true;
      updatePopupPosition();
      error = '';
      const response = await fetch(`https://www.shadesofpale.net/MSISearch?st=${encodeURIComponent(trimmed)}`, {
        headers: { Authorization: `Basic ${btoa('dhcw:dhcw')}` }
      });
      const text = await response.text();
      const parsed = parseServerResponse(text) as unknown;
      results = Array.isArray(parsed)
        ? parsed as StaffResult[]
        : Array.isArray((parsed as { results?: unknown[] })?.results)
          ? (parsed as { results: StaffResult[] }).results
          : [];
      highlightedIndex = results.length ? 0 : -1;
    } catch (err) {
      error = err instanceof Error ? err.message : String(err);
      results = [];
    } finally {
      isSearching = false;
    }
  }

  function queueSearch() {
    if (readonly) return;
    localCoded = false;
    isOpen = searchText.trim().length > 0;
    emit(searchText, false, '');
    window.clearTimeout(searchTimer);
    searchTimer = window.setTimeout(() => searchStaff(searchText), 250);
  }

  function selectResult(result: StaffResult) {
    if (readonly) return;
    const nextValue = displayFor(result);
    const nadexId = nadexIdFor(result);
    searchText = nextValue;
    localCoded = true;
    isOpen = false;
    highlightedIndex = -1;
    emit(nextValue, true, nadexId);
  }

  function clearValue() {
    if (readonly) return;
    searchText = '';
    localCoded = false;
    results = [];
    highlightedIndex = -1;
    emit('', false, '');
  }

  function toggleOpen() {
    if (readonly) return;
    isOpen = !isOpen;
    if (isOpen) searchStaff(searchText);
  }

  function closeAfterBlur() {
    window.clearTimeout(blurTimer);
    blurTimer = window.setTimeout(() => isOpen = false, 200);
  }

  function handleKeydown(event: KeyboardEvent) {
    if (readonly) return;
    if (event.key === 'ArrowDown') {
      event.preventDefault();
      if (!isOpen) {
        isOpen = true;
        updatePopupPosition();
        if (searchText.trim()) searchStaff(searchText);
      }
      highlightedIndex = results.length ? Math.min(highlightedIndex + 1, results.length - 1) : -1;
    } else if (event.key === 'ArrowUp') {
      event.preventDefault();
      if (!isOpen) {
        isOpen = true;
        updatePopupPosition();
      }
      highlightedIndex = results.length ? Math.max(highlightedIndex - 1, 0) : -1;
    } else if (event.key === 'Enter' && isOpen && highlightedIndex >= 0 && results[highlightedIndex]) {
      event.preventDefault();
      selectResult(results[highlightedIndex]);
    } else if (event.key === 'Escape') {
      isOpen = false;
      highlightedIndex = -1;
    }
  }
</script>

{#snippet selectorControl()}
  <div class="fb-selector" bind:this={selectorElement}>
    <div class="fb-selector-input-wrap">
      <input
        id={inputId}
        {name}
        bind:value={searchText}
        {placeholder}
        autocomplete="off"
        {readonly}
        onfocus={() => { if (!readonly) { window.clearTimeout(blurTimer); isOpen = true; updatePopupPosition(); } }}
        oninput={queueSearch}
        onkeydown={handleKeydown}
        onblur={closeAfterBlur}
        role="combobox"
        aria-autocomplete="list"
        aria-expanded={isOpen && !readonly}
        aria-controls={popupId}
        aria-activedescendant={activeOptionId}
        data-lily-reference-component="combobox"
      />
      <div class="fb-selector-actions">
        {#if searchText && !readonly}
          <button type="button" class="fb-selector-button fb-clear" aria-label="Clear" onmousedown={(event) => event.preventDefault()} onclick={clearValue}>{'\u2715'}</button>
        {/if}
        {#if !readonly}
          <button type="button" class="fb-selector-button fb-arrow" aria-label="Search" onmousedown={(event) => event.preventDefault()} onclick={toggleOpen}>{isOpen ? '\u25b2' : '\u25bc'}</button>
        {/if}
      </div>
    </div>
    {#if searchText}
      <span class="material-icons fb-coded-icon" class:coded={effectiveCoded} aria-hidden="true">{effectiveCoded ? 'check_circle_outline' : 'warning'}</span>
    {/if}
    {#if isOpen && !readonly}
      <div id={popupId} class="fb-selector-popup" style={`top: ${popupTop}px; left: ${popupLeft}px; width: ${popupWidth}px; max-height: ${popupMaxHeight}px;`} role="listbox">
        {#if isSearching && results.length === 0}
          <div class="fb-selector-empty">Searching...</div>
        {:else if error}
          <div class="fb-selector-empty">Search unavailable</div>
        {:else if results.length === 0}
          <div class="fb-selector-empty">No matches</div>
        {:else}
          {#each results as result, index}
            <button type="button" id={`${popupId}-option-${index}`} class="fb-selector-result" class:highlighted={highlightedIndex === index} role="option" aria-selected={highlightedIndex === index} onmouseenter={() => highlightedIndex = index} onclick={() => selectResult(result)}>
              <span>{displayFor(result)}</span>
              {#if detailFor(result)}<small>{detailFor(result)}</small>{/if}
            </button>
          {/each}
        {/if}
      </div>
    {/if}
  </div>
{/snippet}

{#if label}
  <FbQuestion {label} {required} {requiredForAudit} {valueError} {subfield}>
    {@render selectorControl()}
  </FbQuestion>
{:else}
  {@render selectorControl()}
{/if}

<style>
  .fb-selector {
    position: relative;
    display: flex;
    gap: 0.3rem;
    align-items: center;
    width: 100%;
    max-width: 30rem;
  }

  .fb-selector-input-wrap {
    position: relative;
    flex: 1;
    min-width: 0;
  }

  input {
    width: 100%;
    height: 2rem;
    min-width: 0;
    border: 0.1rem solid silver;
    border-radius: 0.4rem;
    padding: 0.2rem 2.5rem 0.2rem 0.4rem;
    font-size: 1rem;
    font-weight: 400;
    box-sizing: border-box;
  }

  .fb-selector-actions {
    position: absolute;
    right: 0.2rem;
    top: 50%;
    transform: translateY(-50%);
    display: flex;
    gap: 0.1rem;
  }

  .fb-selector-button {
    border: 0;
    background: transparent;
    color: #666;
    cursor: pointer;
    line-height: 1;
    padding: 0.1rem;
  }

  .fb-clear {
    font-size: 0.9rem;
  }

  .fb-arrow {
    font-size: 1rem;
  }

  .fb-coded-icon {
    color: #fd8a10;
    font-size: 1.2rem;
  }

  .fb-coded-icon.coded {
    color: #008000;
  }

  .fb-selector-popup {
    position: fixed;
    z-index: 10000;
    overflow-y: auto;
    border: 0.1rem solid silver;
    border-radius: 0.4rem;
    background: white;
    box-shadow: 0 2px 8px rgb(0 0 0 / 15%);
  }

  .fb-selector-empty {
    padding: 0.5rem;
    color: #666;
  }

  .fb-selector-result {
    display: flex;
    flex-direction: column;
    width: 100%;
    border: 0;
    background: white;
    cursor: pointer;
    padding: 0.4rem 0.5rem;
    text-align: left;
    font-family: 'Roboto', sans-serif;
  }

  .fb-selector-result:hover,
  .fb-selector-result:focus,
  .fb-selector-result.highlighted {
    background: #ffffcc;
  }

  small {
    color: #666;
    font-size: 0.75rem;
  }
</style>
