// src/components/fbSCTProcedure.tsx
import * as React from 'react';
import { fbSCTSelector as FbSCTSelector } from './fbSCTSelector';

interface fbSCTProcedureProps {
  label?: string;
  name: string;
  value: string;
  onChange: (value: string, coded: boolean) => void;
  onFocus?: (e: React.FocusEvent<HTMLInputElement>) => void;
  onBlur?: () => void;
  placeholder?: string;
  required?: boolean;
  requiredForAudit?: boolean;
  coded?: boolean;
  valueError?: string;
  labelStyle?: React.CSSProperties;
  subfield?: boolean;
}

export const fbSCTProcedure: React.FC<fbSCTProcedureProps> = ({
  label,
  name,
  value,
  onChange,
  onFocus,
  onBlur,
  placeholder = 'Type to search SNOMED CT',
  required,
  requiredForAudit,
  coded,
  valueError,
  labelStyle,
  subfield,
}) => (
  <FbSCTSelector
    label={label}
    name={name}
    value={value}
    onChange={onChange}
    onFocus={onFocus}
    onBlur={onBlur}
    placeholder={placeholder}
    required={required}
    requiredForAudit={requiredForAudit}
    coded={coded}
    valueError={valueError}
    labelStyle={labelStyle}
    subfield={subfield}
    searchCommand="findProcedure"
    mode="procedure"
    inputClassName="fb-sct-procedure-selector-input"
  />
);

// src/lib/components/fb/fbSCTProcedure.svelte
<script lang="ts">
  import FbSCTSelector from './fbSCTSelector.svelte';

  let {
    id = '',
    name,
    label = '',
    value = $bindable(''),
    required = false,
    requiredForAudit = false,
    coded,
    valueError = '',
    subfield = false,
    placeholder = 'Type to search SNOMED CT',
    readonly = false,
    onChange,
    change
  }: {
    id?: string;
    name: string;
    label?: string;
    value?: string;
    required?: boolean;
    requiredForAudit?: boolean;
    coded?: boolean;
    valueError?: string;
    subfield?: boolean;
    placeholder?: string;
    readonly?: boolean;
    onChange?: (value: string, coded: boolean) => void;
    change?: (value: string, coded: boolean) => void;
  } = $props();
</script>

<FbSCTSelector
  {id}
  {name}
  {label}
  bind:value
  {required}
  {requiredForAudit}
  {coded}
  {valueError}
  {subfield}
  {placeholder}
  {readonly}
  searchCommand="findProcedure"
  mode="procedure"
  inputClassName="fb-sct-procedure-selector-input"
  {onChange}
  {change}
/>
