// reactOrig/src/components/fbSubqForOption.tsx
import React from 'react';
import { fbAnimatedSubquestion as FbAnimatedSubquestion } from './fbAnimatedSubquestion';
import { fbSubfieldContext } from './fbQuestion';

interface fbSubqForOptionProps {
  optionValue: string;
  selectedValue?: string;
  children: React.ReactNode;
}

export const fbSubqForOption: React.FC<fbSubqForOptionProps> = ({ optionValue, selectedValue = '', children }) => (
  <FbAnimatedSubquestion open={selectedValue === optionValue}>
    <div className="fb-subquestion" style={{ paddingLeft: '1.5rem' }}>
      <fbSubfieldContext.Provider value>
        {children}
      </fbSubfieldContext.Provider>
    </div>
  </FbAnimatedSubquestion>
);

// src/lib/components/fb/fbSubqForOption.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { setContext } from 'svelte';
  import { fbSubfieldContextKey } from './context';
  import FbAnimatedSubquestion from './fbAnimatedSubquestion.svelte';

  let {
    optionValue,
    selectedValue = '',
    children
  }: {
    optionValue: string;
    selectedValue?: string;
    children: Snippet;
  } = $props();

  setContext(fbSubfieldContextKey, { value: true });
</script>

<FbAnimatedSubquestion open={selectedValue === optionValue}>
  <div class="fb-subquestion fb-subq-for-option">
    {@render children()}
  </div>
</FbAnimatedSubquestion>

<style>
  .fb-subq-for-option {
    padding-left: 1.5rem;
  }
</style>
