// src/components/fbTextArea.tsx
import React from 'react';
import { fbQuestion as FbQuestion } from './fbQuestion';
import { fbAutoExpandingTextarea as AutoExpandingTextarea } from './fbAutoExpandingTextarea';

interface fbTextAreaProps {
  label?: string;
  value: string;
  onChange: (value: string) => void;
  required?: boolean;
  placeholder?: string;
  id?: string;
  name?: string;
  className?: string;
  style?: React.CSSProperties;
  inputStyle?: React.CSSProperties;
  subfield?: boolean;
  rows?: number;
  fullWidth?: boolean;
  valueError?: string;
}

export const fbTextArea: React.FC<fbTextAreaProps> = ({
  label,
  value = '',
  onChange,
  required = false,
  placeholder = '',
  id,
  name,
  className = '',
  style,
  inputStyle,
  subfield = false,
  rows = 2,
  fullWidth = false,
  valueError,
}) => {
  const renderTextarea = () => {
    return (
      <AutoExpandingTextarea
        id={id}
        name={name}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        required={required}
        rows={rows}
        className="w-full text-black font-sans"
        style={{
          fontFamily: "'Roboto', sans-serif",
          fontWeight: 400,
          padding: '0.3rem 0.5rem',
          fontSize: '1rem',
          minHeight: '2rem',
          maxWidth: fullWidth ? undefined : '37rem',
          backgroundColor: 'white',
          ...inputStyle,
          border: '0.1rem solid silver',
          borderRadius: '0.4rem',
        }}
      />
    );
  };

  if (!label) {
    if (required) {
      return (
        <div style={{ display: 'flex', alignItems: 'flex-start', gap: '0.2rem', width: '100%', boxSizing: 'border-box' }}>
          <div style={{ flex: 1, width: '100%' }}>
            {renderTextarea()}
          </div>
          <span style={{ color: '#d50000', fontSize: '1rem', fontWeight: 'bold', lineHeight: '1.2rem', marginTop: '0.15rem', display: 'inline-block', userSelect: 'none' }}>*</span>
        </div>
      );
    }
    return renderTextarea();
  }

  return (
    <FbQuestion
      label={label}
      required={required}
      className={className}
      style={style}
      labelStyle={subfield ? { fontWeight: 300, fontSize: '1rem' } : undefined}
      valueError={valueError}
    >
      {renderTextarea()}
    </FbQuestion>
  );
};

// src/lib/components/fb/fbTextArea.svelte
<script lang="ts">
  import { tick } from 'svelte';
  import FbQuestion from './fbQuestion.svelte';
  import FbRequiredForAudit from './fbRequiredForAudit.svelte';

  let {
    label,
    value = $bindable(''),
    required = false,
    requiredForAudit = false,
    placeholder = '',
    id,
    name,
    class: className = '',
    subfield = false,
    rows = 2,
    fullWidth = false,
    valueError = '',
    readonly = false,
    onChange,
    change
  }: {
    label?: string;
    value?: string;
    required?: boolean;
    requiredForAudit?: boolean;
    placeholder?: string;
    id?: string;
    name?: string;
    class?: string;
    subfield?: boolean;
    rows?: number;
    fullWidth?: boolean;
    valueError?: string;
    readonly?: boolean;
    onChange?: (value: string) => void;
    change?: (value: string) => void;
  } = $props();

  let textAreaElement = $state<HTMLTextAreaElement | undefined>();

  function resize() {
    if (!textAreaElement) return;
    textAreaElement.style.height = 'auto';
    textAreaElement.style.height = `${textAreaElement.scrollHeight}px`;
  }

  async function update(nextValue: string) {
    if (readonly) return;
    value = nextValue;
    onChange?.(nextValue);
    change?.(nextValue);
    await tick();
    resize();
  }

  $effect(() => {
    value;
    tick().then(resize);
  });
</script>

{#snippet textAreaControl()}
  <textarea
    bind:this={textAreaElement}
    {id}
    {name}
    bind:value
    oninput={(event) => update(event.currentTarget.value)}
    {placeholder}
    {required}
    {rows}
    {readonly}
    class="w-full text-black font-sans"
    class:full-width={fullWidth}
    data-lily-reference-component="textarea"
  ></textarea>
{/snippet}

{#if label}
  <FbQuestion {label} {required} {requiredForAudit} class={className} {subfield} {valueError}>
    {@render textAreaControl()}
  </FbQuestion>
{:else if required || requiredForAudit}
  <div class="fb-unlabelled-required-control">
    <div>{@render textAreaControl()}</div>
    <span class="fb-unlabelled-required-markers">
      {#if requiredForAudit}<FbRequiredForAudit />{/if}
      {#if required}<span class="fb-required-marker">*</span>{/if}
    </span>
  </div>
{:else}
  {@render textAreaControl()}
{/if}

<style>
  textarea {
    font-family: 'Roboto', sans-serif;
    font-weight: 400;
    padding: 0.3rem 0.5rem;
    font-size: 1rem;
    min-height: 2rem;
    max-width: 37rem;
    background-color: white;
    border: 0.1rem solid silver;
    border-radius: 0.4rem;
    box-sizing: border-box;
    resize: none;
    overflow: hidden;
    width: 100%;
  }

  textarea.full-width {
    max-width: none;
  }

  .fb-unlabelled-required-control {
    display: flex;
    align-items: flex-start;
    gap: 0.2rem;
    width: 100%;
    box-sizing: border-box;
  }

  .fb-unlabelled-required-control > div {
    flex: 1;
    width: 100%;
  }

  .fb-unlabelled-required-markers {
    display: inline-flex;
    align-items: flex-start;
    gap: 0.1rem;
    margin-top: 0.15rem;
  }

  .fb-required-marker {
    color: #d50000;
    font-size: 1rem;
    font-weight: bold;
    line-height: 1.2rem;
    display: inline-block;
    user-select: none;
  }
</style>
