// src/components/fbUserName.tsx
import React, { useState } from 'react';

interface fbUserNameProps {
  value: string;
  onChange: (value: string) => void;
  id?: string;
  className?: string;
  style?: React.CSSProperties;
}

export const fbUserName: React.FC<fbUserNameProps> = ({
  value = '',
  onChange,
  id = 'username-input',
  className = 'fb-bottom-control-username',
  style,
}) => {
  const [isHovered, setIsHovered] = useState(false);
  const [isFocused, setIsFocused] = useState(false);

  return (
    <input
      type="text"
      id={id}
      name="username"
      value={value}
      onChange={(e) => onChange(e.target.value)}
      placeholder="Enter username"
      className={className}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      onFocus={() => setIsFocused(true)}
      onBlur={() => setIsFocused(false)}
      style={{
        display: 'inline-block',
        height: '2.0rem',
        lineHeight: '2rem',
        padding: '0 0.5rem',
        border: '0.1rem solid silver',
        borderRadius: '0.4rem',
        fontFamily: "'Roboto', sans-serif",
        fontSize: '1rem',
        fontWeight: 400,
        color: 'black',
        boxSizing: 'border-box',
        backgroundColor: (isHovered || isFocused) ? '#fee715' : 'white',
        outline: 'none',
        transition: 'background-color 0.2s ease, border-color 0.2s ease',
        ...style,
      }}
    />
  );
};

// src/lib/components/fb/fbUserName.svelte
<script lang="ts">
  type Props = {
    value?: string;
    disabled?: boolean;
    id?: string;
    class?: string;
    onChange?: (value: string) => void;
  };

  let { value = $bindable('demoUser'), disabled = false, id = 'username-input', class: className = 'fb-bottom-control-username', onChange }: Props = $props();
  let hovering = $state(false);
  let focusing = $state(false);

  const inputStyle = $derived([
    'display: inline-block',
    'height: 2rem',
    'line-height: 2rem',
    'width: 9rem',
    'box-sizing: border-box',
    'border: 0.1rem solid silver',
    'border-radius: 0.4rem',
    'padding: 0 0.5rem',
    "font-family: 'Roboto', sans-serif",
    'font-size: 1rem',
    'font-weight: 400',
    'color: black',
    `background-color: ${hovering || focusing ? '#fee715' : 'white'}`,
    'outline: none',
    'transition: background-color 0.2s ease, border-color 0.2s ease'
  ].join('; '));

  function handleInput(event: Event) {
    const nextValue = (event.currentTarget as HTMLInputElement).value;
    value = nextValue;
    onChange?.(nextValue);
  }
</script>

<input
  class={`${className} fb-username-input`.trim()}
  {id}
  name="username"
  type="text"
  placeholder="Enter username"
  {disabled}
  bind:value
  oninput={handleInput}
  onmouseenter={() => (hovering = true)}
  onmouseleave={() => (hovering = false)}
  onfocus={() => (focusing = true)}
  onblur={() => (focusing = false)}
  style={inputStyle}
  aria-label="User id"
  data-lily-reference-component="text-input"
/>
