// reactOrig/src/components/fbcPanel.tsx
import React from 'react';

type FbcPanelProps = {
  header: React.ReactNode;
  properties: React.ReactNode;
  actions: React.ReactNode;
  footer: React.ReactNode;
  bodyRef?: React.Ref<HTMLDivElement>;
};

export const fbcPanel: React.FC<FbcPanelProps> = ({ header, properties, actions, footer, bodyRef }) => (
  <FbcPanelLayout header={header} properties={properties} actions={actions} footer={footer} bodyRef={bodyRef} />
);

const FbcPanelLayout: React.FC<FbcPanelProps> = ({ header, properties, actions, footer, bodyRef }) => {
  const bodyElementRef = React.useRef<HTMLDivElement | null>(null);
  const propertiesElementRef = React.useRef<HTMLDivElement | null>(null);
  const actionsElementRef = React.useRef<HTMLDivElement | null>(null);
  const [constrained, setConstrained] = React.useState(false);

  const setBodyElement = React.useCallback((element: HTMLDivElement | null) => {
    bodyElementRef.current = element;
    if (typeof bodyRef === 'function') {
      bodyRef(element);
    } else if (bodyRef && 'current' in bodyRef) {
      (bodyRef as React.MutableRefObject<HTMLDivElement | null>).current = element;
    }
  }, [bodyRef]);

  const updateLayoutMode = React.useCallback(() => {
    const bodyElement = bodyElementRef.current;
    const propertiesElement = propertiesElementRef.current;
    const actionsElement = actionsElementRef.current;
    if (!bodyElement || !propertiesElement || !actionsElement) return;
    const bodyStyle = window.getComputedStyle(bodyElement);
    const rowGap = Number.parseFloat(bodyStyle.rowGap || bodyStyle.gap || '0') || 0;
    const needsConstrainedLayout = propertiesElement.scrollHeight + actionsElement.scrollHeight + rowGap > bodyElement.clientHeight + 1;
    setConstrained((current) => (current === needsConstrainedLayout ? current : needsConstrainedLayout));
  }, []);

  React.useLayoutEffect(() => {
    updateLayoutMode();
  });

  React.useEffect(() => {
    const observedElements = [bodyElementRef.current, propertiesElementRef.current, actionsElementRef.current].filter(Boolean) as HTMLElement[];
    if (!observedElements.length) return undefined;
    const resizeObserver = typeof ResizeObserver === 'undefined' ? undefined : new ResizeObserver(updateLayoutMode);
    const mutationObserver = typeof MutationObserver === 'undefined' ? undefined : new MutationObserver(updateLayoutMode);
    observedElements.forEach((element) => resizeObserver?.observe(element));
    [propertiesElementRef.current, actionsElementRef.current].forEach((element) => {
      if (element) mutationObserver?.observe(element, { attributes: true, childList: true, characterData: true, subtree: true });
    });
    window.addEventListener('resize', updateLayoutMode);
    return () => {
      resizeObserver?.disconnect();
      mutationObserver?.disconnect();
      window.removeEventListener('resize', updateLayoutMode);
    };
  }, [updateLayoutMode]);

  return (
    <aside className="fb-designer-panel fbc-panel">
      <div className="fbc-panel-header">{header}</div>
      <div className={`fbc-panel-body${constrained ? ' fbc-panel-body-constrained' : ''}`} ref={setBodyElement}>
        <div className="fbc-panel-scroll fbc-panel-properties" ref={propertiesElementRef}>{properties}</div>
        <div className="fbc-panel-scroll fbc-panel-actions" ref={actionsElementRef}>{actions}</div>
      </div>
      <div className="fbc-panel-footer">{footer}</div>
    </aside>
  );
};

// src/lib/components/fbc/fbcPanel.svelte
<script lang="ts">
  import { onMount, tick } from 'svelte';

  let bodyElement: HTMLDivElement | undefined;
  let propertiesElement: HTMLDivElement | undefined;
  let actionsElement: HTMLDivElement | undefined;
  let constrained = $state(false);

  function updateLayoutMode() {
    if (!bodyElement || !propertiesElement || !actionsElement) return;
    const bodyStyle = window.getComputedStyle(bodyElement);
    const rowGap = Number.parseFloat(bodyStyle.rowGap || bodyStyle.gap || '0') || 0;
    constrained = propertiesElement.scrollHeight + actionsElement.scrollHeight + rowGap > bodyElement.clientHeight + 1;
  }

  $effect(() => {
    tick().then(updateLayoutMode);
  });

  onMount(() => {
    const resizeObserver = typeof ResizeObserver === 'undefined' ? undefined : new ResizeObserver(updateLayoutMode);
    const mutationObserver = typeof MutationObserver === 'undefined' ? undefined : new MutationObserver(updateLayoutMode);
    if (resizeObserver) {
      [bodyElement, propertiesElement, actionsElement].forEach((element) => {
        if (element) resizeObserver.observe(element);
      });
    }
    if (mutationObserver) {
      [propertiesElement, actionsElement].forEach((element) => {
        if (element) mutationObserver.observe(element, { attributes: true, childList: true, characterData: true, subtree: true });
      });
    }
    window.addEventListener('resize', updateLayoutMode);
    updateLayoutMode();
    return () => {
      resizeObserver?.disconnect();
      mutationObserver?.disconnect();
      window.removeEventListener('resize', updateLayoutMode);
    };
  });
</script>

<aside class="fb-designer-panel fbc-panel">
  <div class="fbc-panel-header"><slot name="header" /></div>
  <div class:fbc-panel-body-constrained={constrained} class="fbc-panel-body" bind:this={bodyElement}>
    <div class="fbc-panel-scroll fbc-panel-properties" bind:this={propertiesElement}><slot name="properties" /></div>
    <div class="fbc-panel-scroll fbc-panel-actions" bind:this={actionsElement}><slot name="actions" /></div>
  </div>
  <div class="fbc-panel-footer"><slot name="footer" /></div>
</aside>

<style>
  .fbc-panel {
    border-left: 0.1rem solid black;
    padding: 0.8rem;
    display: flex;
    flex-direction: column;
    overflow: hidden;
  }

  .fbc-panel-header {
    flex: 0 0 auto;
  }

  .fbc-panel-body {
    flex: 1 1 auto;
    min-height: 0;
    display: grid;
    grid-template-rows: minmax(0, max-content) minmax(0, 1fr);
    gap: 0.5rem;
    padding: 0.6rem 0;
    overflow: hidden;
  }

  .fbc-panel-body-constrained {
    grid-template-rows: minmax(0, 1fr) minmax(0, 1fr);
  }

  .fbc-panel-scroll {
    min-height: 0;
    overflow: auto;
  }

  .fbc-panel-actions {
    position: relative;
    border-top: 0.1rem solid silver;
    padding-top: 0.5rem;
  }

  .fbc-panel-footer {
    flex: 0 0 auto;
    padding-top: 0.5rem;
  }

  @media (max-width: 900px) {
    .fbc-panel {
      border-left: 0;
      border-top: 0.1rem solid black;
    }
  }
</style>
