// src/lib/caseNoteTracker/FbcntHeader.svelte
<script lang="ts">
  export let title: {
    kicker: string;
    title: string;
    details?: unknown;
    titleStyle?: string;
    detailsStyle?: string;
  };
</script>

<header class="fbcnt-header">
  <div class="title-block">
    <div class="kicker">{title.kicker}</div>
    <h1 style={title.titleStyle || ''}>{title.title}</h1>
    {#if title.details}
      <div class="title-details" style={title.detailsStyle || ''}>{title.details}</div>
    {/if}
  </div>
  <div class="header-right"><slot name="right" /></div>
</header>

<style>
  .fbcnt-header {
    background-color: white;
    border-bottom: 0.2rem solid #1b6ec2;
    padding: 0 0.8rem;
    display: flex;
    align-items: center;
    justify-content: space-between;
    min-height: 4.2rem;
    gap: 1rem;
  }

  .title-block {
    padding-top: 1rem;
    padding-bottom: 1rem;
  }

  .kicker {
    font-size: 1rem;
    font-weight: 300;
    color: #333;
    line-height: 1.1;
  }

  h1 {
    font-size: 2rem;
    font-weight: 500;
    margin: 0;
    color: #333;
    line-height: 1.05;
  }

  .title-details {
    margin-top: 0.2rem;
    font-size: 0.9rem;
    font-weight: 300;
    color: #333;
    line-height: 1.05;
  }

  .header-right {
    font-weight: 500;
    color: #333;
  }
</style>

// reactOrig/src/caseNoteTracker/fbcntHeader.tsx
import React from 'react';
import { fbBlue } from './cntStyles';

type TitleSpec = {
  kicker: string;
  title: string;
  details?: React.ReactNode;
  titleStyle?: React.CSSProperties;
  detailsStyle?: React.CSSProperties;
};

export function FbcntHeader({ title, right }: { title: TitleSpec; right?: React.ReactNode }) {
  return (
    <header style={styles.header}>
      <div style={styles.titleBlock}>
        <div style={styles.kicker}>{title.kicker}</div>
        <h1 style={{ ...styles.title, ...title.titleStyle }}>{title.title}</h1>
        {title.details && <div style={{ ...styles.titleDetails, ...title.detailsStyle }}>{title.details}</div>}
      </div>
      <div style={styles.headerRight}>{right}</div>
    </header>
  );
}

const styles = {
  header: {
    backgroundColor: 'white',
    borderBottom: `0.2rem solid ${fbBlue}`,
    padding: '0 0.8rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: '4.2rem',
    gap: '1rem',
  } as React.CSSProperties,
  titleBlock: {
    paddingTop: '1rem',
    paddingBottom: '1rem',
  } as React.CSSProperties,
  kicker: {
    fontSize: '1rem',
    fontWeight: 300,
    color: '#333',
    lineHeight: 1.1,
  } as React.CSSProperties,
  title: {
    fontSize: '2rem',
    fontWeight: 500,
    margin: 0,
    color: '#333',
    lineHeight: 1.05,
  } as React.CSSProperties,
  titleDetails: {
    marginTop: '0.2rem',
    fontSize: '0.9rem',
    fontWeight: 300,
    color: '#333',
    lineHeight: 1.05,
  } as React.CSSProperties,
  headerRight: {
    fontWeight: 500,
    color: '#333',
  } as React.CSSProperties,
};
