// svelte/src/caseNoteTracker/fbcntClinicInstancesTable.svelte
<script lang="ts">
  import type { CntClinicInstance, CntStore } from './cntStore';
  import FbcntUserBadge from './FbcntUserBadge.svelte';
  import FbcntSmallButton from './FbcntSmallButton.svelte';
  import Table from './cntTable.svelte';

  export let store: CntStore;
  export let instances: CntClinicInstance[] = [];
  export let openClinicList: (instanceUuid: string) => void = () => {};

  function dateTime(value = '') {
    const date = new Date(value);
    if (Number.isNaN(date.valueOf())) return value;
    return `${date.toLocaleDateString('en-GB')} ${date.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}`;
  }
</script>

<Table>
  <thead><tr><th>Date/time</th><th>Clinic</th><th>Retrievers</th><th>Appointments</th><th class="right">Action</th></tr></thead>
  <tbody>
    {#each instances as instance (instance.uuid)}
      {@const clinic = store.clinics.find((item) => item.uuid === instance.clinicUuid)}
      <tr>
        <td>{dateTime(instance.dateTime || `${instance.date}T${instance.startTime || '00:00'}`)}</td>
        <td>{clinic?.clinicName}<br>{clinic?.speciality}<br>{clinic?.clinician}</td>
        <td>
          {#each instance.retrieverUserUuids || [] as uuid}
            {@const retriever = store.users.find((user) => user.uuid === uuid)}
            {#if retriever}<div><FbcntUserBadge user={retriever} /></div>{/if}
          {/each}
        </td>
        <td>{instance.appointments.length}</td>
        <td class="right"><FbcntSmallButton onClick={() => openClinicList(instance.uuid)}>Clinic list</FbcntSmallButton></td>
      </tr>
    {/each}
  </tbody>
</Table>

<style>
  .right { text-align: right; }
</style>

// reactOrig/src/caseNoteTracker/fbcntClinicInstancesTable.tsx
import { fbDateDisplay as FbDateDisplay } from '../components/fbDateDisplay';
import { fbTimeDisplay as FbTimeDisplay } from '../components/fbTimeDisplay';
import { fbTable as FbTable, fbTableBody as FbTableBody, fbTableHeader as FbTableHeader, fbTableHeaderCell as FbTableHeaderCell, fbTableRow as FbTableRow } from '../components/fbTable';
import { fbTableCell as FbTableCell } from '../components/fbTableCell';
import type { CntClinicInstance, CntStore } from './cntStore';
import { FbcntLocationDisplay } from './fbcntLocationDisplay';
import { FbcntSmallButton } from './fbcntSmallButton';
import { clinicSummary } from './fbcntPageComponents';

export function ClinicInstancesTable({
  store,
  instances,
  openClinicList,
}: {
  store: CntStore;
  instances: CntClinicInstance[];
  openClinicList: (clinicInstanceUuid: string) => void;
}) {
  return (
    <FbTable aria-label="Clinic instances">
      <FbTableHeader>
        <FbTableRow>
          <FbTableHeaderCell style={{ width: '10rem' }}>Clinic instance</FbTableHeaderCell>
          <FbTableHeaderCell>Clinic</FbTableHeaderCell>
          <FbTableHeaderCell>Holding location</FbTableHeaderCell>
          <FbTableHeaderCell style={{ width: '8rem', textAlign: 'right' }}>Action</FbTableHeaderCell>
        </FbTableRow>
      </FbTableHeader>
      <FbTableBody>
        {instances.map((instance) => {
          const clinic = store.clinics.find((item) => item.uuid === instance.clinicUuid);
          return (
            <FbTableRow key={instance.uuid}>
              <FbTableCell>
                <FbDateDisplay value={instance.date} />
                <br />
                <FbTimeDisplay value={instance.startTime} />-<FbTimeDisplay value={instance.endTime} />
              </FbTableCell>
              <FbTableCell>{clinicSummary(clinic)}</FbTableCell>
              <FbTableCell>{clinic ? <FbcntLocationDisplay store={store} locationUuid={clinic.holdingLocationUuid} compact /> : ''}</FbTableCell>
              <FbTableCell style={{ textAlign: 'right' }}>
                <FbcntSmallButton onClick={() => openClinicList(instance.uuid)}>Clinic list</FbcntSmallButton>
              </FbTableCell>
            </FbTableRow>
          );
        })}
      </FbTableBody>
    </FbTable>
  );
}
