// src/lib/caseNoteTracker/FbcntTag.svelte
<script lang="ts">
  export let title = '';
</script>

<span class="material-icons fbcnt-tag" {title} aria-label={title || 'Tagged'}>sell</span>

<style>
  .fbcnt-tag {
    color: #1b6ec2;
    background-color: white;
    font-family: 'Material Icons';
    font-size: 1rem;
    line-height: 1;
    display: inline-block;
    vertical-align: middle;
  }
</style>

// reactOrig/src/caseNoteTracker/fbcntTag.tsx
import React from 'react';
import { fbBlue } from './cntStyles';

export function FbcntTag({ title }: { title?: string }) {
  return (
    <span
      className="material-icons"
      title={title}
      aria-label={title || 'Tagged'}
      style={{
        color: fbBlue,
        backgroundColor: 'white',
        fontFamily: 'Material Icons',
        fontSize: '1rem',
        lineHeight: 1,
        display: 'inline-block',
        verticalAlign: 'middle',
      }}
    >
      sell
    </span>
  );
}
