// svelte/src/caseNoteTracker/FbcntLocation.svelte
<script lang="ts">
  import { onDestroy, tick } from 'svelte';
  import FbQuestion from '../components/fbQuestion.svelte';
  import FbToolTip from '../components/fbToolTip.svelte';
  import type { CntLocation, CntStore } from './cntStore';
  import { locationLabel } from './cntStore';

  export let label = '';
  export let store: CntStore;
  export let value = '';
  export let onChange: (value: string) => void = () => {};
  export let allowBlank = false;

  let searchTerm = '';
  let showDropdown = false;
  let highlightedIndex = -1;
  let inputWrap: HTMLDivElement | undefined;
  let openAbove = false;
  let maxHeight = 300;

  $: selectedLabel = store ? locationLabel(store, value) : '';
  $: if (!showDropdown && searchTerm !== selectedLabel) searchTerm = selectedLabel;
  $: results = locationResults(store, searchTerm);
  $: selected = store?.locations.find((location) => location.uuid === value);
  $: coded = !searchTerm.trim() ? allowBlank : !!selected && searchTerm === selectedLabel;

  function locationResults(storeValue: CntStore, termValue: string) {
    const term = termValue.trim().toLowerCase();
    return storeValue.locations
      .map((location) => ({ location, label: locationLabel(storeValue, location.uuid) }))
      .filter((item) => !term || item.label.toLowerCase().includes(term) || item.location.code.toLowerCase().includes(term))
      .slice(0, 50);
  }

  function updateDropdownPosition() {
    if (!inputWrap) return;
    const rect = inputWrap.getBoundingClientRect();
    const preferredHeight = 300;
    const spaceBelow = window.innerHeight - rect.bottom - 20;
    const spaceAbove = rect.top - 20;
    maxHeight = Math.min(preferredHeight, Math.max(120, spaceBelow >= spaceAbove ? spaceBelow : spaceAbove));
    openAbove = !(spaceBelow >= preferredHeight || spaceBelow >= spaceAbove);
  }

  async function openDropdown() {
    showDropdown = true;
    await tick();
    updateDropdownPosition();
    window.addEventListener('resize', updateDropdownPosition);
    window.addEventListener('scroll', updateDropdownPosition, true);
  }

  function closeDropdown() {
    showDropdown = false;
    highlightedIndex = -1;
    window.removeEventListener('resize', updateDropdownPosition);
    window.removeEventListener('scroll', updateDropdownPosition, true);
  }

  onDestroy(closeDropdown);

  function selectLocation(location: CntLocation) {
    searchTerm = locationLabel(store, location.uuid);
    onChange(location.uuid);
    closeDropdown();
  }

  function clear() {
    searchTerm = '';
    if (allowBlank) onChange('');
    closeDropdown();
  }

  function handleInput(event: Event) {
    searchTerm = (event.currentTarget as HTMLInputElement).value;
    onChange('');
    highlightedIndex = -1;
    openDropdown();
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape') {
      closeDropdown();
      return;
    }
    if (!showDropdown || !results.length) return;
    if (event.key === 'ArrowDown') {
      event.preventDefault();
      highlightedIndex = Math.min(highlightedIndex + 1, results.length - 1);
    } else if (event.key === 'ArrowUp') {
      event.preventDefault();
      highlightedIndex = Math.max(highlightedIndex - 1, 0);
    } else if (event.key === 'Enter' && highlightedIndex >= 0) {
      event.preventDefault();
      selectLocation(results[highlightedIndex].location);
    }
  }
</script>

<FbQuestion {label}>
  <div class="control-row">
    <div class="input-wrap" bind:this={inputWrap}>
      <input
        type="text"
        value={searchTerm}
        oninput={handleInput}
        onfocus={openDropdown}
        onblur={() => window.setTimeout(closeDropdown, 150)}
        onkeydown={handleKeydown}
        placeholder="Type to search locations"
        autocomplete="off"
      />
      <div class="input-buttons">
        {#if searchTerm}
          <button type="button" class="icon-button" aria-label="Clear location" onmousedown={(event) => event.preventDefault()} onclick={clear}>&times;</button>
        {/if}
        <button
          type="button"
          class="toggle-button"
          onmousedown={(event) => event.preventDefault()}
          onclick={() => showDropdown ? closeDropdown() : openDropdown()}
        >{showDropdown ? '\u25b2' : '\u25bc'}</button>
      </div>
      {#if showDropdown && results.length}
        <div class="dropdown" class:open-above={openAbove} style={`max-height: ${maxHeight}px`}>
          {#each results as result, index (result.location.uuid)}
            <div
              class="result"
              class:highlighted={highlightedIndex === index}
              role="option"
              aria-selected={highlightedIndex === index}
              tabindex="-1"
              onmousedown={() => selectLocation(result.location)}
              onmouseenter={() => highlightedIndex = index}
            >
              <div>{result.label}</div>
              <div class="result-code">{result.location.code}</div>
            </div>
          {/each}
        </div>
      {/if}
    </div>
    {#if searchTerm && coded}
      <FbToolTip as="span" className="material-icons coded-icon" text="Coded" tabindex={0}>check_circle_outline</FbToolTip>
    {:else if searchTerm && !coded}
      <FbToolTip as="span" className="material-icons warning-icon" text="Not coded" tabindex={0}>warning</FbToolTip>
    {/if}
  </div>
</FbQuestion>

<style>
  .control-row { display: flex; align-items: center; width: 100%; gap: 0.3rem; }
  .input-wrap { position: relative; flex: 1; }
  input {
    width: 100%;
    height: 2rem;
    border: 0.1rem solid silver;
    border-radius: 0.4rem;
    padding: 0.35rem 2.5rem 0.35rem 0.45rem;
    box-sizing: border-box;
    background-color: white;
    font-family: 'Roboto', sans-serif;
  }
  .input-buttons {
    position: absolute;
    right: 0.2rem;
    top: 50%;
    transform: translateY(-50%);
    display: flex;
    align-items: center;
    gap: 0.1rem;
  }
  .icon-button,
  .toggle-button {
    border: 0;
    background: transparent;
    color: #666;
    cursor: pointer;
    padding: 0.1rem;
    line-height: 1;
  }
  .icon-button { font-size: 0.9rem; }
  .toggle-button { font-size: 1rem; }
  .dropdown {
    position: absolute;
    left: 0;
    top: calc(100% + 0.2rem);
    width: 45rem;
    max-width: calc(100vw - 40px);
    overflow-y: auto;
    overflow-x: auto;
    background-color: white;
    border: 0.1rem solid silver;
    border-radius: 0.4rem;
    z-index: 10000;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
  }
  .dropdown.open-above {
    top: auto;
    bottom: calc(100% + 0.2rem);
  }
  .result {
    padding: 0.125rem 0.5rem;
    cursor: pointer;
    font-size: 0.9rem;
    line-height: 1.1;
    white-space: nowrap;
  }
  .result.highlighted,
  .result:hover {
    background-color: #ffffcc;
  }
  .result-code { font-size: 0.75rem; color: #555; }
  :global(.coded-icon) { color: #008000; font-size: 1.2rem; }
  :global(.warning-icon) { color: #fd8a10; font-size: 1.2rem; }
</style>

// reactOrig/src/caseNoteTracker/fbcntLocation.tsx
import React from 'react';
import { fbQuestion as FbQuestion } from '../components/fbQuestion';
import { fbToolTip as FbToolTip } from '../components/fbToolTip';
import type { CntLocation, CntStore } from './cntStore';
import { locationLabel } from './cntStore';
import { fbGreen, fbOrange } from './cntStyles';

type FbcntLocationProps = {
  label: string;
  store: CntStore;
  value: string;
  onChange: (value: string) => void;
  allowBlank?: boolean;
};

export function FbcntLocation({ label, store, value, onChange, allowBlank = false }: FbcntLocationProps) {
  const selectedLabel = locationLabel(store, value);
  const [searchTerm, setSearchTerm] = React.useState(selectedLabel);
  const [showDropdown, setShowDropdown] = React.useState(false);
  const [highlightedIndex, setHighlightedIndex] = React.useState(-1);
  const containerRef = React.useRef<HTMLDivElement>(null);
  const [dropdownPlacement, setDropdownPlacement] = React.useState({ openAbove: false, maxHeight: 300 });

  React.useEffect(() => {
    setSearchTerm(selectedLabel);
  }, [selectedLabel]);

  const results = React.useMemo(() => {
    const term = searchTerm.trim().toLowerCase();
    const ranked = store.locations
      .map((location) => ({ location, label: locationLabel(store, location.uuid) }))
      .filter((item) => !term || item.label.toLowerCase().includes(term) || item.location.code.toLowerCase().includes(term));
    return ranked.slice(0, 50);
  }, [store, searchTerm]);

  const selected = store.locations.find((location) => location.uuid === value);
  const coded = !searchTerm.trim() ? allowBlank : !!selected && searchTerm === selectedLabel;

  const updateDropdownPosition = React.useCallback(() => {
    if (!containerRef.current) return;
    const rect = containerRef.current.getBoundingClientRect();
    const preferredHeight = 300;
    const spaceBelow = window.innerHeight - rect.bottom - 20;
    const spaceAbove = rect.top - 20;
    const maxHeight = Math.min(preferredHeight, Math.max(120, spaceBelow >= spaceAbove ? spaceBelow : spaceAbove));
    setDropdownPlacement({
      openAbove: !(spaceBelow >= preferredHeight || spaceBelow >= spaceAbove),
      maxHeight,
    });
  }, []);

  React.useEffect(() => {
    if (!showDropdown) return;
    updateDropdownPosition();
    const update = () => updateDropdownPosition();
    window.addEventListener('resize', update);
    window.addEventListener('scroll', update, true);
    return () => {
      window.removeEventListener('resize', update);
      window.removeEventListener('scroll', update, true);
    };
  }, [showDropdown, updateDropdownPosition]);

  const selectLocation = (location: CntLocation) => {
    setSearchTerm(locationLabel(store, location.uuid));
    onChange(location.uuid);
    setShowDropdown(false);
    setHighlightedIndex(-1);
  };

  const clear = () => {
    setSearchTerm('');
    if (allowBlank) onChange('');
    setShowDropdown(false);
    setHighlightedIndex(-1);
  };

  const handleKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.key === 'Escape') {
      setShowDropdown(false);
      setHighlightedIndex(-1);
      return;
    }
    if (!showDropdown || !results.length) return;
    if (event.key === 'ArrowDown') {
      event.preventDefault();
      setHighlightedIndex((current) => Math.min(current + 1, results.length - 1));
    }
    if (event.key === 'ArrowUp') {
      event.preventDefault();
      setHighlightedIndex((current) => Math.max(current - 1, 0));
    }
    if (event.key === 'Enter' && highlightedIndex >= 0) {
      event.preventDefault();
      selectLocation(results[highlightedIndex].location);
    }
  };

  const content = (
    <div style={styles.controlRow}>
      <div ref={containerRef} style={styles.inputWrap}>
        <input
          type="text"
          value={searchTerm}
          onChange={(event) => {
            setSearchTerm(event.target.value);
            onChange('');
            updateDropdownPosition();
            setShowDropdown(true);
            setHighlightedIndex(-1);
          }}
          onFocus={() => {
            updateDropdownPosition();
            setShowDropdown(true);
          }}
          onBlur={() => window.setTimeout(() => setShowDropdown(false), 150)}
          onKeyDown={handleKeyDown}
          placeholder="Type to search locations"
          autoComplete="off"
          style={styles.input}
        />
        <div style={styles.inputButtons}>
          {searchTerm && (
            <button type="button" onMouseDown={(event) => event.preventDefault()} onClick={clear} style={styles.iconButton}>{'\u2715'}</button>
          )}
          <button
            type="button"
            onMouseDown={(event) => event.preventDefault()}
            onClick={() => {
              updateDropdownPosition();
              setShowDropdown((current) => !current);
            }}
            style={styles.toggleButton}
          >
            {showDropdown ? '\u25b2' : '\u25bc'}
          </button>
        </div>
        {showDropdown && results.length > 0 && (
          <div
            style={{
              ...styles.dropdown,
              maxHeight: dropdownPlacement.maxHeight,
              ...(dropdownPlacement.openAbove
                ? { bottom: 'calc(100% + 0.2rem)' }
                : { top: 'calc(100% + 0.2rem)' }),
            }}
          >
            {results.map((result, index) => (
              <div
                key={result.location.uuid}
                onMouseDown={() => selectLocation(result.location)}
                onMouseEnter={() => setHighlightedIndex(index)}
                style={{
                  ...styles.result,
                  backgroundColor: highlightedIndex === index ? '#ffffcc' : 'white',
                }}
              >
                <div>{result.label}</div>
                <div style={styles.resultCode}>{result.location.code}</div>
              </div>
            ))}
          </div>
        )}
      </div>
      {searchTerm && coded && (
        <TooltipIcon icon="check_circle_outline" text="Coded" style={styles.codedIcon} />
      )}
      {searchTerm && !coded && (
        <TooltipIcon icon="warning" text="Not coded" style={styles.warningIcon} />
      )}
    </div>
  );

  return <FbQuestion label={label}>{content}</FbQuestion>;
}

export function FbcntFromLocation(props: Omit<FbcntLocationProps, 'label'>) {
  return <FbcntLocation {...props} label="From" />;
}

export function FbcntToLocation(props: Omit<FbcntLocationProps, 'label'>) {
  return <FbcntLocation {...props} label="To" />;
}

function TooltipIcon({ icon, text, style }: { icon: string; text: string; style: React.CSSProperties }) {
  const ref = React.useRef<HTMLSpanElement | null>(null);
  const [tooltip, setTooltip] = React.useState<{ x: number; y: number } | null>(null);
  const showTooltip = () => {
    const rect = ref.current?.getBoundingClientRect();
    if (!rect) return;
    setTooltip({ x: Math.max(10, rect.left), y: Math.max(10, rect.top - 34) });
  };
  return (
    <>
      <span
        ref={ref}
        className="material-icons"
        style={style}
        tabIndex={0}
        aria-label={text}
        onMouseEnter={showTooltip}
        onMouseLeave={() => setTooltip(null)}
        onFocus={showTooltip}
        onBlur={() => setTooltip(null)}
      >
        {icon}
      </span>
      {tooltip && <FbToolTip x={tooltip.x} y={tooltip.y} text={text} />}
    </>
  );
}

const styles = {
  controlRow: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    gap: '0.3rem',
  } as React.CSSProperties,
  inputWrap: {
    position: 'relative',
    flex: 1,
  } as React.CSSProperties,
  input: {
    width: '100%',
    height: '2rem',
    border: '0.1rem solid silver',
    borderRadius: '0.4rem',
    padding: '0.35rem 2.5rem 0.35rem 0.45rem',
    boxSizing: 'border-box',
    backgroundColor: 'white',
    fontFamily: "'Roboto', sans-serif",
  } as React.CSSProperties,
  inputButtons: {
    position: 'absolute',
    right: '0.2rem',
    top: '50%',
    transform: 'translateY(-50%)',
    display: 'flex',
    alignItems: 'center',
    gap: '0.1rem',
  } as React.CSSProperties,
  iconButton: {
    border: 0,
    background: 'transparent',
    color: '#666',
    cursor: 'pointer',
    fontSize: '0.9rem',
    padding: '0.1rem',
    lineHeight: 1,
  } as React.CSSProperties,
  toggleButton: {
    border: 0,
    background: 'transparent',
    color: '#666',
    cursor: 'pointer',
    fontSize: '1rem',
    padding: '0.1rem',
    lineHeight: 1,
  } as React.CSSProperties,
  dropdown: {
    position: 'absolute',
    left: 0,
    width: '45rem',
    maxWidth: 'calc(100vw - 40px)',
    overflowY: 'auto',
    overflowX: 'auto',
    backgroundColor: 'white',
    border: '0.1rem solid silver',
    borderRadius: '0.4rem',
    zIndex: 10000,
    boxShadow: '0 2px 8px rgba(0,0,0,0.15)',
  } as React.CSSProperties,
  result: {
    padding: '0.125rem 0.5rem',
    cursor: 'pointer',
    fontSize: '0.9rem',
    lineHeight: 1.1,
    whiteSpace: 'nowrap',
  } as React.CSSProperties,
  resultCode: {
    fontSize: '0.75rem',
    color: '#555',
  } as React.CSSProperties,
  codedIcon: {
    color: fbGreen,
    fontSize: '1.2rem',
  } as React.CSSProperties,
  warningIcon: {
    color: fbOrange,
    fontSize: '1.2rem',
  } as React.CSSProperties,
};
