// svelteOrig/src/caseNoteTracker/FbcntPageLocator.svelte
<script lang="ts">
  import type { CntStore, CntVolume } from './cntStore';
  import FbcntLocationDisplay from './FbcntLocationDisplay.svelte';
  import FbcntSmallButton from './FbcntSmallButton.svelte';
  import FbcntButtonManageVolume from './FbcntButtonManageVolume.svelte';
  import FbcntBadgeActive from './FbcntBadgeActive.svelte';
  import FbcntBadgeClosed from './FbcntBadgeClosed.svelte';
  import FbcntBadgeDestroyed from './FbcntBadgeDestroyed.svelte';
  import HighlightBlock from './fbcntHighlightBlock.svelte';
  import TreeNode from './fbcntTreeNode.svelte';
  import VolumeTagIcon from './fbcntVolumeTagIcon.svelte';
  import PatientChooser from './fbcntPatientChooser.svelte';

  export let store: CntStore;
  export let selectedPatientUuid = '';
  export let selectedVolumeUuids: string[] = [];
  export let toggleVolume: (volumeUuid: string) => void = () => {};
  export let openHistory: (volumeUuid: string) => void = () => {};
  export let openManageVolume: ((volumeUuid: string) => void) | undefined = undefined;
  export let selectPatient: (patientUuid: string) => void = () => {};

  let collapsed: Record<string, boolean> = {};

  $: patient = store?.patients.find((item) => item.uuid === selectedPatientUuid);
  $: volumes = (store?.volumes || []).filter((volume) => volume.patientUuid === selectedPatientUuid).sort(volumeSort);
  $: tree = buildVolumeTree(volumes);

  function volumeSort(a: CntVolume, b: CntVolume) {
    return a.healthBoard.localeCompare(b.healthBoard)
      || a.locality.localeCompare(b.locality)
      || a.type.localeCompare(b.type)
      || Number(a.temporary) - Number(b.temporary)
      || a.volumeNumber - b.volumeNumber;
  }

  function buildVolumeTree(items: CntVolume[]) {
    const result: Record<string, Record<string, Record<string, CntVolume[]>>> = {};
    for (const volume of items) {
      result[volume.healthBoard] ||= {};
      result[volume.healthBoard][volume.locality] ||= {};
      result[volume.healthBoard][volume.locality][volume.type] ||= [];
      result[volume.healthBoard][volume.locality][volume.type].push(volume);
    }
    return result;
  }

  function toggleCollapsed(key: string) {
    collapsed = { ...collapsed, [key]: !collapsed[key] };
  }

  function selectAllVolumes(items: CntVolume[]) {
    for (const volume of items) {
      if (volume.status !== 'destroyed' && !selectedVolumeUuids.includes(volume.uuid)) toggleVolume(volume.uuid);
    }
  }

  function isSelected(volume: CntVolume) {
    return volume.status !== 'destroyed' && selectedVolumeUuids.includes(volume.uuid);
  }
</script>

{#if !patient}
  <PatientChooser {store} {selectPatient} />
{:else}
  <section class="locator-shell">
    <div class="locator-scroll">
      <div class="tree">
        {#each Object.entries(tree) as [healthBoard, localities] (healthBoard)}
          <TreeNode
            label={healthBoard}
            level={0}
            nodeKey={`hb:${healthBoard}`}
            {collapsed}
            {toggleCollapsed}
            preventCollapse={volumes.some((volume) => volume.healthBoard === healthBoard && selectedVolumeUuids.includes(volume.uuid))}
          >
            {#each Object.entries(localities) as [locality, types] (`${healthBoard}:${locality}`)}
              <TreeNode
                label={locality}
                level={1}
                nodeKey={`loc:${healthBoard}:${locality}`}
                {collapsed}
                {toggleCollapsed}
                preventCollapse={volumes.some((volume) => volume.healthBoard === healthBoard && volume.locality === locality && selectedVolumeUuids.includes(volume.uuid))}
              >
                {#each Object.entries(types) as [type, items] (`${healthBoard}:${locality}:${type}`)}
                  <TreeNode
                    label={type}
                    level={2}
                    nodeKey={`type:${healthBoard}:${locality}:${type}`}
                    {collapsed}
                    {toggleCollapsed}
                    preventCollapse={items.some((volume) => selectedVolumeUuids.includes(volume.uuid))}
                  >
                    {#if items.filter((volume) => volume.status !== 'destroyed').length > 1}
                      <div class="select-all-row">
                        <button type="button" class="select-all-button" onclick={() => selectAllVolumes(items)}>Select all</button>
                      </div>
                    {/if}
                    {#each items as volume (volume.uuid)}
                      <HighlightBlock level={3} style="grid-template-columns: minmax(10rem, 1fr) 6.5rem minmax(16rem, 2fr) 2rem auto auto; padding-left: 4.8rem;">
                        <label class:disabled={volume.status === 'destroyed'} class="volume-label">
                          <input
                            type="checkbox"
                            checked={isSelected(volume)}
                            disabled={volume.status === 'destroyed'}
                            onchange={() => toggleVolume(volume.uuid)}
                          />
                          <span>Volume {volume.volumeNumber}{volume.temporary ? ' temporary' : ''}</span>
                        </label>
                        <span class="status-cell">
                          {#if volume.status === 'destroyed'}
                            <FbcntBadgeDestroyed />
                          {:else if volume.status === 'closed'}
                            <FbcntBadgeClosed />
                          {:else}
                            <FbcntBadgeActive />
                          {/if}
                        </span>
                        <span class="volume-meta"><FbcntLocationDisplay {store} {volume} withIcon /></span>
                        <VolumeTagIcon {store} {volume} />
                        {#if openManageVolume}<FbcntButtonManageVolume onClick={() => openManageVolume?.(volume.uuid)} />{/if}
                        <FbcntSmallButton onClick={() => openHistory(volume.uuid)}>History</FbcntSmallButton>
                      </HighlightBlock>
                    {/each}
                  </TreeNode>
                {/each}
              </TreeNode>
            {/each}
          </TreeNode>
        {/each}
      </div>
    </div>
  </section>
{/if}

<style>
  .locator-shell {
    height: 100%;
    min-height: 0;
    display: flex;
    flex-direction: column;
    background: white;
  }

  .locator-scroll {
    flex: 1;
    min-height: 0;
    overflow-y: auto;
    padding-bottom: 0.8rem;
  }

  .tree {
    padding: 0.4rem;
  }

  .select-all-row {
    padding: 0.15rem 0 0.15rem 4.8rem;
  }

  .select-all-button {
    border: 0;
    border-radius: 0.4rem;
    background: #1b6ec2;
    color: white;
    padding: 0.15rem 0.4rem;
    font-family: 'Roboto', sans-serif;
    font-size: 0.75rem;
    font-weight: 500;
    cursor: pointer;
  }

  :global(.fbcnt-highlight-level-3) {
    display: grid;
    gap: 0.6rem;
    align-items: center;
    border-top: 0.1rem solid #eee;
    padding-top: 0.25rem;
    padding-bottom: 0.25rem;
  }

  .volume-label {
    display: inline-flex;
    align-items: center;
    gap: 0.35rem;
  }

  .volume-label.disabled {
    color: #666;
    cursor: not-allowed;
  }

  .status-cell,
  .volume-meta {
    min-width: 0;
  }
</style>

// src/caseNoteTracker/fbcntPageLocator.tsx
import React from 'react';
import type { CntAppointmentStatus, CntClinicInstance, CntRequest, CntPatient, CntStore, CntVolume } from './cntStore';
import {
  FbAddressograph, FbBoxedInfo, FbDropdown, FbExactDate, FbGridCell, FbGridRow, FbGroup, FbNumberInput, FbModal, FbQuestion, FbRadio, FbRoVField, FbTextArea, FbTextInput, FbToolTip, FbDateDisplay, FbTimeDisplay, FbTable, FbTableBody, FbTableHeader, FbTableHeaderCell, FbTableRow, FbTableCell, FbGroupWithBorder, FbcntBatchVolumeSet, FbcntFromLocation, FbcntLocation, FbcntToLocation, FbcntSelectedVolumes, FbcntSelectedVolumesLocation, FbcntSmallButton, FbcntUserBadge, FbcntBadgeActive, FbcntBadgeClosed, FbcntBadgeDestroyed, FbcntBadgeCancelled, FbcntBadgeRescheduled, FbcntButtonManageVolume, FbcntTag, FbcntLocationDisplay, fbBlue, fbGreen, fbLightBlue, fbOrange, fbRed, formatDisplayDate, formatDisplayTime, locationLabel, patientName, locationDisplayText, cntHomeEntry, pushCntNavigation, styles, patientSearchUrl, TreeNode, HighlightBlock, VolumeTagLine, VolumeTagIcon, volumeTagTooltip, TagTooltipLine, volumeStatusBadge, appointmentStatusBadge, PatientChooser, FbcntBatchFilter, latestVolumeEvent, ClinicInstancesTable, FbcntClinicFilter, FbcntLocationFilter, LocationSelect, SelectedVolumeList, PatientAddressograph, buildVolumeTree, volumeSort, nextVolumeNumber, uniqueValues, addDaysToIso, clinicInstancesInNextSixWeeks, clinicMatchesFilter, custodianUuidsForLocation, requestRows, requestMatchesRow, highlightStyleForLevel, clinicSummaryForReturnList, renderMultiline, volumeLabelForRequest, userBatchUuids, defaultLibraryUuids, userLibraryUuids, locationHyphenLabel, volumeLocationCounts, clinicSummary,
} from './fbcntPageComponents';
import type { View, CntClinicFilterState, CntLocationFilterState, RequestRow } from './fbcntPageComponents';

export function FbcntPageLocator({
  store,
  selectedPatientUuid,
  selectedVolumeUuids,
  toggleVolume,
  openHistory,
  openManageVolume,
}
: {
  store: CntStore;
  selectedPatientUuid: string;
  selectedVolumeUuids: string[];
  toggleVolume: (volumeUuid: string) => void;
  openHistory: (volumeUuid: string) => void;
  openManageVolume?: (volumeUuid: string) => void;
}) {
  const patient = store.patients.find((item) => item.uuid === selectedPatientUuid);
  const volumes = store.volumes
    .filter((volume) => volume.patientUuid === selectedPatientUuid)
    .sort(volumeSort);
  const [collapsed, setCollapsed] = React.useState<Record<string, boolean>>({});

  if (!patient) {
    return <PatientChooser store={store} />;
  }

  const toggleCollapsed = (key: string) => setCollapsed((current) => ({ ...current, [key]: !current[key] }));
  const selectAllVolumes = (items: CntVolume[]) => {
    items
      .filter((volume) => volume.status !== 'destroyed' && !selectedVolumeUuids.includes(volume.uuid))
      .forEach((volume) => toggleVolume(volume.uuid));
  };
  const tree = buildVolumeTree(volumes);

  return (
    <section style={styles.locatorShell}>
      <div style={styles.locatorScroll}>
      <div style={styles.tree}>
        {Object.entries(tree).map(([hb, localities]) => (
          <TreeNode
            key={hb}
            label={hb}
            level={0}
            nodeKey={`hb:${hb}`}
            collapsed={collapsed}
            toggleCollapsed={toggleCollapsed}
            preventCollapse={volumes.some((volume) => volume.healthBoard === hb && selectedVolumeUuids.includes(volume.uuid))}
          >
            {Object.entries(localities).map(([locality, types]) => (
              <TreeNode
                key={locality}
                label={locality}
                level={1}
                nodeKey={`loc:${hb}:${locality}`}
                collapsed={collapsed}
                toggleCollapsed={toggleCollapsed}
                preventCollapse={volumes.some((volume) => volume.healthBoard === hb && volume.locality === locality && selectedVolumeUuids.includes(volume.uuid))}
              >
                {Object.entries(types).map(([type, items]) => (
                  <TreeNode
                    key={type}
                    label={type}
                    level={2}
                    nodeKey={`type:${hb}:${locality}:${type}`}
                    collapsed={collapsed}
                    toggleCollapsed={toggleCollapsed}
                    preventCollapse={items.some((volume) => selectedVolumeUuids.includes(volume.uuid))}
                  >
                    {items.filter((volume) => volume.status !== 'destroyed').length > 1 && (
                      <div style={styles.selectAllButtonRow}>
                        <button type="button" style={styles.selectAllButton} onClick={() => selectAllVolumes(items)}>
                          Select all
                        </button>
                      </div>
                    )}
                    {items.map((volume) => (
                      (() => {
                        const isDestroyed = volume.status === 'destroyed';
                        return (
                      <HighlightBlock
                        key={volume.uuid}
                        level={3}
                        style={{ ...styles.volumeRow, gridTemplateColumns: 'minmax(10rem, 1fr) 6.5rem minmax(16rem, 2fr) 2rem auto auto', paddingLeft: '4.8rem' }}
                      >
                        <label style={{ ...styles.volumeLabel, ...(isDestroyed ? styles.volumeLabelDisabled : {}) }}>
                          <input
                            type="checkbox"
                            checked={!isDestroyed && selectedVolumeUuids.includes(volume.uuid)}
                            disabled={isDestroyed}
                            onChange={() => toggleVolume(volume.uuid)}
                          />
                          <span>Volume {volume.volumeNumber}{volume.temporary ? ' temporary' : ''}</span>
                        </label>
                        <span style={styles.volumeStatusCell}>{volumeStatusBadge(volume)}</span>
                        <span style={styles.volumeMeta}>
                          <FbcntLocationDisplay store={store} volume={volume} withIcon />
                        </span>
                        <VolumeTagIcon store={store} volume={volume} />
                        {openManageVolume && <FbcntButtonManageVolume onClick={() => openManageVolume(volume.uuid)} />}
                        <FbcntSmallButton onClick={() => openHistory(volume.uuid)}>History</FbcntSmallButton>
                      </HighlightBlock>
                        );
                      })()
                    ))}
                  </TreeNode>
                ))}
              </TreeNode>
            ))}
          </TreeNode>
        ))}
      </div>
      </div>
    </section>
  );
}
