// src/lib/caseNoteTracker/fbcntTreeNode.svelte
<script lang="ts">
  import { slide } from 'svelte/transition';
  import HighlightBlock from './fbcntHighlightBlock.svelte';

  export let label = '';
  export let level = 0;
  export let nodeKey = '';
  export let collapsed: Record<string, boolean> = {};
  export let toggleCollapsed: (key: string) => void = () => {};
  export let preventCollapse = false;

  $: isCollapsed = !!collapsed[nodeKey];

  function toggle() {
    if (!isCollapsed && preventCollapse) return;
    toggleCollapsed(nodeKey);
  }
</script>

<HighlightBlock {level}>
  <button
    type="button"
    class="tree-toggle"
    style={`padding-left: ${level * 1.6}rem`}
    onclick={toggle}
    aria-disabled={!isCollapsed && preventCollapse}
    aria-expanded={!isCollapsed}
  >
    <span class="tree-icon" aria-hidden="true">{isCollapsed ? '\u25b6' : '\u25bc'}</span>
    <strong>{label}</strong>
  </button>
</HighlightBlock>

{#if !isCollapsed}
  <div class="tree-content" transition:slide={{ duration: 500 }} aria-hidden={isCollapsed}>
    <slot />
  </div>
{/if}

<style>
  .tree-toggle {
    display: flex;
    align-items: center;
    gap: 0.35rem;
    width: 100%;
    border: 0;
    background-color: transparent;
    color: #111;
    text-align: left;
    font-family: 'Roboto', sans-serif;
    font-size: 0.95rem;
    padding-top: 0.25rem;
    padding-bottom: 0.25rem;
    cursor: pointer;
  }

  .tree-icon {
    display: inline-block;
    line-height: 1;
  }

  .tree-content {
    overflow: hidden;
    min-height: 0;
  }
</style>

// src/caseNoteTracker/fbcntTreeNode.tsx
import React from 'react';
import { styles } from './fbcntPageComponents';
import { HighlightBlock } from './fbcntHighlightBlock';

export function TreeNode({
  label,
  level,
  nodeKey,
  collapsed,
  toggleCollapsed,
  preventCollapse = false,
  children,
}: {
  key?: React.Key;
  label: string;
  level: number;
  nodeKey: string;
  collapsed: Record<string, boolean>;
  toggleCollapsed: (key: string) => void;
  preventCollapse?: boolean;
  children: React.ReactNode;
}) {
  const isCollapsed = !!collapsed[nodeKey];
  return (
    <>
    <HighlightBlock level={level}>
      <button
        type="button"
        style={{ ...styles.treeToggle, paddingLeft: `${level * 1.6}rem`, backgroundColor: 'transparent' }}
        onClick={() => {
          if (!isCollapsed && preventCollapse) return;
          toggleCollapsed(nodeKey);
        }}
        aria-disabled={!isCollapsed && preventCollapse}
      >
        <span aria-hidden="true">{isCollapsed ? '\u25b6' : '\u25bc'}</span>
        <strong>{label}</strong>
      </button>
    </HighlightBlock>
    {!isCollapsed && <div>{children}</div>}
    </>
  );
}
