// svelte/src/caseNoteTracker/FbcntPageClinicList.svelte
<script lang="ts">
  import type { CntStore, CntVolume } from './cntStore';
  import FbcntSelectedVolumes from './FbcntSelectedVolumes.svelte';
  import FbcntSmallButton from './FbcntSmallButton.svelte';
  import PatientAddressograph from './fbcntPatientAddressograph.svelte';
  import Table from './cntTable.svelte';
  import FbcntBadgeActive from './FbcntBadgeActive.svelte';
  import FbcntBadgeCancelled from './FbcntBadgeCancelled.svelte';
  import FbcntBadgeRescheduled from './FbcntBadgeRescheduled.svelte';

  export let store: CntStore;
  export let clinicInstanceUuid = '';
  export let showRescheduled = false;
  export let showCancelled = false;
  export let openPatientRecord: (patientUuid: string) => void = () => {};
  export let openPickListSelector: (clinicInstanceUuid: string, patientUuid: string) => void = () => {};
  export let openPickListReceive: (clinicInstanceUuid: string, patientUuid: string) => void = () => {};

  $: instance = store.clinicInstances.find((item) => item.uuid === clinicInstanceUuid);
  $: rows = (instance?.appointments || [])
    .filter((appointment) => appointment.status === 'active' || (appointment.status === 'rescheduled' && showRescheduled) || (appointment.status === 'cancelled' && showCancelled))
    .sort((a, b) => a.time.localeCompare(b.time));

  function volumeSort(a: CntVolume, b: CntVolume) {
    return a.healthBoard.localeCompare(b.healthBoard)
      || a.locality.localeCompare(b.locality)
      || a.type.localeCompare(b.type)
      || Number(a.temporary) - Number(b.temporary)
      || a.volumeNumber - b.volumeNumber;
  }

  function formatDisplayTime(value: string) {
    return value?.slice(0, 5) || '';
  }
</script>

{#if !instance}
  <p class="note">Clinic instance not found.</p>
{:else}
  <div class="table-page-stack">
    <Table>
      <thead><tr><th class="status-col">Status</th><th>Patient</th><th>Volumes</th><th class="right action-col">Action</th></tr></thead>
      <tbody>
        {#each rows as appointment (appointment.uuid)}
          {@const patient = store.patients.find((item) => item.uuid === appointment.patientUuid)}
          {@const selectedEntries = store.cntPickList.filter((entry) => entry.clinicInstanceUuid === instance.uuid)}
          {@const volumes = store.volumes.filter((volume) => volume.patientUuid === appointment.patientUuid && selectedEntries.some((entry) => entry.volumeUuid === volume.uuid)).sort(volumeSort)}
          <tr>
            <td>
              {#if appointment.status === 'cancelled'}
                <FbcntBadgeCancelled />
              {:else if appointment.status === 'rescheduled'}
                <FbcntBadgeRescheduled />
              {:else}
                <FbcntBadgeActive />
              {/if}
              <div class="time">{formatDisplayTime(appointment.time)}</div>
            </td>
            <td>{#if patient}<PatientAddressograph {patient} />{/if}</td>
            <td><FbcntSelectedVolumes {store} {volumes} /></td>
            <td class="right">
              <div class="stacked-buttons">
                <FbcntSmallButton onClick={() => openPatientRecord(appointment.patientUuid)}>Open record</FbcntSmallButton>
                <FbcntSmallButton onClick={() => openPickListSelector(instance.uuid, appointment.patientUuid)}>Select case notes</FbcntSmallButton>
                <FbcntSmallButton onClick={() => openPickListReceive(instance.uuid, appointment.patientUuid)}>Receive case notes</FbcntSmallButton>
              </div>
            </td>
          </tr>
        {/each}
      </tbody>
    </Table>
  </div>
{/if}

<style>
  .table-page-stack { display: grid; gap: 0.8rem; }
  .status-col { width: 9rem; }
  .action-col { width: 10rem; }
  .right { text-align: right; }
  .time { margin-top: 0.25rem; }
  .stacked-buttons { display: grid; gap: 0.25rem; justify-items: end; }
  .note { color: #555; font-style: italic; }
</style>

// src/caseNoteTracker/fbcntPageClinicList.tsx
import React from 'react';
import type { CntAppointmentStatus, CntClinicInstance, CntRequest, CntPatient, CntStore, CntVolume } from './cntStore';
import {
  FbAddressograph, FbBoxedInfo, FbDropdown, FbExactDate, FbGridCell, FbGridRow, FbGroup, FbNumberInput, FbModal, FbQuestion, FbRadio, FbRoVField, FbTextArea, FbTextInput, FbToolTip, FbDateDisplay, FbTimeDisplay, FbTable, FbTableBody, FbTableHeader, FbTableHeaderCell, FbTableRow, FbTableCell, FbGroupWithBorder, FbcntBatchVolumeSet, FbcntFromLocation, FbcntLocation, FbcntToLocation, FbcntSelectedVolumes, FbcntSelectedVolumesLocation, FbcntSmallButton, FbcntUserBadge, FbcntBadgeActive, FbcntBadgeClosed, FbcntBadgeDestroyed, FbcntBadgeCancelled, FbcntBadgeRescheduled, FbcntButtonManageVolume, FbcntTag, FbcntLocationDisplay, fbBlue, fbGreen, fbLightBlue, fbOrange, fbRed, formatDisplayDate, formatDisplayTime, locationLabel, patientName, locationDisplayText, cntHomeEntry, pushCntNavigation, styles, patientSearchUrl, TreeNode, HighlightBlock, VolumeTagLine, VolumeTagIcon, volumeTagTooltip, TagTooltipLine, volumeStatusBadge, appointmentStatusBadge, PatientChooser, FbcntBatchFilter, latestVolumeEvent, ClinicInstancesTable, FbcntClinicFilter, FbcntLocationFilter, LocationSelect, SelectedVolumeList, PatientAddressograph, buildVolumeTree, volumeSort, nextVolumeNumber, uniqueValues, addDaysToIso, clinicInstancesInNextSixWeeks, clinicMatchesFilter, custodianUuidsForLocation, requestRows, requestMatchesRow, highlightStyleForLevel, clinicSummaryForReturnList, renderMultiline, volumeLabelForRequest, userBatchUuids, defaultLibraryUuids, userLibraryUuids, locationHyphenLabel, volumeLocationCounts, clinicSummary,
} from './fbcntPageComponents';
import type { View, CntClinicFilterState, CntLocationFilterState, RequestRow } from './fbcntPageComponents';

export function FbcntPageClinicList({
  store,
  clinicInstanceUuid,
  showRescheduled,
  showCancelled,
  openPatientRecord,
  openPickListSelector,
  openPickListReceive,
}
: {
  store: CntStore;
  clinicInstanceUuid: string;
  showRescheduled: boolean;
  showCancelled: boolean;
  openPatientRecord: (patientUuid: string) => void;
  openPickListSelector: (clinicInstanceUuid: string, patientUuid: string) => void;
  openPickListReceive: (clinicInstanceUuid: string, patientUuid: string) => void;
}) {
  const instance = store.clinicInstances.find((item) => item.uuid === clinicInstanceUuid);
  if (!instance) return <p style={styles.note}>Clinic instance not found.</p>;
  const rows = instance.appointments
    .filter((appointment) => appointment.status === 'active' || (appointment.status === 'rescheduled' && showRescheduled) || (appointment.status === 'cancelled' && showCancelled))
    .sort((a, b) => a.time.localeCompare(b.time));
  return (
    <div style={styles.tablePageStack}>
      <FbTable aria-label="Clinic appointment list">
        <FbTableHeader>
          <FbTableRow>
            <FbTableHeaderCell style={{ width: '9rem' }}>Status</FbTableHeaderCell>
            <FbTableHeaderCell>Patient</FbTableHeaderCell>
            <FbTableHeaderCell>Volumes</FbTableHeaderCell>
            <FbTableHeaderCell style={{ width: '10rem', textAlign: 'right' }}>Action</FbTableHeaderCell>
          </FbTableRow>
        </FbTableHeader>
        <FbTableBody>
          {rows.map((appointment) => {
            const patient = store.patients.find((item) => item.uuid === appointment.patientUuid);
            const selectedEntries = store.cntPickList.filter((entry) => entry.clinicInstanceUuid === instance.uuid);
            const volumes = store.volumes
              .filter((volume) => volume.patientUuid === appointment.patientUuid && selectedEntries.some((entry) => entry.volumeUuid === volume.uuid))
              .sort(volumeSort);
            return (
              <FbTableRow key={appointment.uuid}>
                <FbTableCell>
                  {appointmentStatusBadge(appointment.status)}
                  <div style={{ marginTop: '0.25rem' }}><FbTimeDisplay value={appointment.time} /></div>
                </FbTableCell>
                <FbTableCell>{patient && <PatientAddressograph patient={patient} />}</FbTableCell>
                <FbTableCell><FbcntSelectedVolumes store={store} volumes={volumes} /></FbTableCell>
                <FbTableCell style={{ textAlign: 'right' }}>
                  <div style={styles.stackedButtons}>
                    <FbcntSmallButton onClick={() => openPatientRecord(appointment.patientUuid)}>Open record</FbcntSmallButton>
                    <FbcntSmallButton onClick={() => openPickListSelector(instance.uuid, appointment.patientUuid)}>Select case notes</FbcntSmallButton>
                    <FbcntSmallButton onClick={() => openPickListReceive(instance.uuid, appointment.patientUuid)}>Receive case notes</FbcntSmallButton>
                  </div>
                </FbTableCell>
              </FbTableRow>
            );
          })}
        </FbTableBody>
      </FbTable>
    </div>
  );
}
