// src/lib/components/fb/fbBadgeSuperseded.svelte
<div
  class="fb-superseded-badge"
  style="background-color: #d50000; color: white; font-weight: 700; padding: 0.2rem 0.4rem; font-family: 'Roboto', sans-serif; font-size: 1rem; display: inline-block; line-height: 1.2; border-radius: 0;"
  data-lily-reference-component="badge"
>
  Superseded
</div>

// reactOrig/src/components/fbBadgeSuperseded.tsx
import React from 'react';

export const fbBadgeSuperseded: React.FC = () => (
  <span
    className="fb-superseded-badge"
    style={{
      backgroundColor: '#d50000',
      color: 'white',
      fontWeight: 700,
      padding: '0.2rem 0.4rem',
      fontFamily: "'Roboto', sans-serif",
      fontSize: '1rem',
      display: 'inline-block',
      lineHeight: 1.2,
      borderRadius: 0,
    }}
  >
    Superseded
  </span>
);
