// src/lib/components/fb/fbCancelFormButton.svelte
<script lang="ts">
  import FbButton from './fbButton.svelte';

  let {
    onclick,
    class: className = '',
    style = ''
  }: {
    onclick?: (event: MouseEvent) => void;
    class?: string;
    style?: string;
  } = $props();
</script>

<FbButton type="button" variant="danger" class={className} {style} {onclick}>Cancel</FbButton>

// reactOrig/src/components/fbCancelFormButton.tsx
import React from 'react';
import { fbButton as FbButton } from './fbButton';

interface fbCancelFormButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {}

export const fbCancelFormButton: React.FC<fbCancelFormButtonProps> = ({
  style,
  ...props
}) => {
  return (
    <FbButton
      type="button"
      variant="danger"
      style={style}
      {...props}
    >
      Cancel
    </FbButton>
  );
};
