// src/lib/components/fb/fbInverseSubq.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { setContext } from 'svelte';
  import { fbSubfieldContextKey } from './context';
  import FbAnimatedSubquestion from './fbAnimatedSubquestion.svelte';

  let {
    open,
    children
  }: {
    open: boolean;
    children: Snippet;
  } = $props();

  setContext(fbSubfieldContextKey, { value: true });
</script>

<FbAnimatedSubquestion {open}>
  <div class="fb-subquestion fb-inverse-subq">
    {@render children()}
  </div>
</FbAnimatedSubquestion>

<style>
  .fb-inverse-subq {
    padding-left: 0;
  }
</style>

// reactOrig/src/components/fbInverseSubq.tsx
import React from 'react';
import { fbAnimatedSubquestion as FbAnimatedSubquestion } from './fbAnimatedSubquestion';
import { fbSubfieldContext } from './fbQuestion';

interface fbInverseSubqProps {
  open: boolean;
  children: React.ReactNode;
  style?: React.CSSProperties;
}

export const fbInverseSubq: React.FC<fbInverseSubqProps> = ({ open, children, style }) => (
  <FbAnimatedSubquestion open={open}>
    <div className="fb-subquestion fb-inverse-subq" style={{ paddingLeft: 0, ...style }}>
      <fbSubfieldContext.Provider value>
        {children}
      </fbSubfieldContext.Provider>
    </div>
  </FbAnimatedSubquestion>
);
