// svelteOrig/src/components/fbSaveCancelButtons.svelte
<script lang="ts">
  import FbButton from './fbButton.svelte';

  export let saveDisabled = false;
  export let saving = false;
  export let formChanged = true;
  export let showRov = true;
  export let onSave: () => void = () => {};
  export let onCancel: () => void = () => {};
  export let onRov: () => void = () => {};
</script>

<div class="fb-save-cancel-buttons">
  {#if showRov}
    <FbButton type="button" onClick={onRov}>RoV</FbButton>
  {/if}
  <FbButton type="button" variant={formChanged ? 'success' : 'secondary'} disabled={saveDisabled || saving || !formChanged} onClick={onSave}>
    {saving ? 'Saving...' : 'Save and close'}
  </FbButton>
  <FbButton type="button" variant="danger" onClick={onCancel}>Cancel</FbButton>
</div>

<style>
  .fb-save-cancel-buttons {
    display: flex;
    gap: 0.4rem;
    align-items: center;
  }
</style>

// reactOrig/src/components/fbSaveCancelButtons.tsx
import React from 'react';
import { fbCancelFormButton as FbCancelFormButton } from './fbCancelFormButton';
import { fbButton as FbButton } from './fbButton';

interface SaveCancelButtonsProps {
  formChanged: boolean;
  onCancel: () => void;
  saveLabel?: string;
  cancelLabel?: string;
  isSaving?: boolean;
}

export const fbSaveCancelButtons: React.FC<SaveCancelButtonsProps> = ({
  formChanged,
  onCancel,
  saveLabel = 'Save',
  cancelLabel = 'Cancel',
  isSaving = false,
}) => {
  return (
    <>
      <FbButton
        type="submit"
        disabled={!formChanged || isSaving}
        variant={formChanged ? 'success' : 'secondary'}
        className="fb-bottom-btn-save"
        style={{
          marginLeft: '0.2rem',
          ...(formChanged ? {} : {
            backgroundColor: '#c0c0c0',
            borderColor: '#c0c0c0',
            color: 'white',
          })
        }}
      >
        {isSaving ? 'Saving...' : saveLabel}
      </FbButton>

      <FbCancelFormButton
        className="fb-bottom-btn-cancel"
        onClick={onCancel}
        style={{
          marginLeft: '0.2rem',
        }}
      />
    </>
  );
};
