// src/lib/components/fb/fbSaveCancelButtons.svelte
<script lang="ts">
  import FbButton from './fbButton.svelte';
  import FbCancelFormButton from './fbCancelFormButton.svelte';

  let {
    formChanged,
    onCancel,
    saveLabel = 'Save and close',
    isSaving = false,
    saving = isSaving,
    saveDisabled = false,
    onSave,
    showRov = true
  }: {
    formChanged: boolean;
    onCancel: () => void;
    saveLabel?: string;
    cancelLabel?: string;
    isSaving?: boolean;
    saving?: boolean;
    saveDisabled?: boolean;
    onSave?: () => void;
    showRov?: boolean;
  } = $props();

  const disabled = $derived(saveDisabled || !formChanged || saving);
</script>

  <FbButton
    type={onSave ? 'button' : 'submit'}
    onclick={onSave}
    disabled={disabled}
    variant={formChanged ? 'success' : 'secondary'}
    class="fb-bottom-btn-save"
    style="margin-left: 0.2rem"
  >
  {saving ? 'Saving...' : saveLabel}
</FbButton>

<FbCancelFormButton class="fb-bottom-btn-cancel" style="margin-left: 0.2rem" onclick={onCancel} />

// reactOrig/src/components/fbSaveCancelButtons.tsx
import React from 'react';
import { fbCancelFormButton as FbCancelFormButton } from './fbCancelFormButton';
import { fbButton as FbButton } from './fbButton';

interface SaveCancelButtonsProps {
  formChanged: boolean;
  onCancel: () => void;
  saveLabel?: string;
  cancelLabel?: string;
  isSaving?: boolean;
}

export const fbSaveCancelButtons: React.FC<SaveCancelButtonsProps> = ({
  formChanged,
  onCancel,
  saveLabel = 'Save',
  cancelLabel = 'Cancel',
  isSaving = false,
}) => {
  return (
    <>
      <FbButton
        type="submit"
        disabled={!formChanged || isSaving}
        variant={formChanged ? 'success' : 'secondary'}
        className="fb-bottom-btn-save"
        style={{
          marginLeft: '0.2rem',
          ...(formChanged ? {} : {
            backgroundColor: '#c0c0c0',
            borderColor: '#c0c0c0',
            color: 'white',
          })
        }}
      >
        {isSaving ? 'Saving...' : saveLabel}
      </FbButton>

      <FbCancelFormButton
        className="fb-bottom-btn-cancel"
        onClick={onCancel}
        style={{
          marginLeft: '0.2rem',
        }}
      />
    </>
  );
};
