// src/lib/components/fb/fbToolTipUser.svelte
<script lang="ts">
  import FbToolTip from './fbToolTip.svelte';

  export let user: {
    surname: string;
    firstNames: string;
    title: string;
    role: string;
    facility: string;
    nadexId: string;
  } | undefined = undefined;

  $: initials = user ? `${user.firstNames.charAt(0)}${user.surname.charAt(0)}`.toUpperCase() : '';
  $: tooltipText = user ? [
    `${user.surname.toUpperCase()}, ${user.firstNames}, ${user.title}`,
    user.role,
    user.facility,
    user.nadexId,
  ].join('\n') : '';
  let highlighted = false;
  $: userStyle = [
    'display: inline-block',
    'border-radius: 0.2rem',
    'padding: 0.05rem 0.2rem',
    'outline-offset: 0.1rem',
    highlighted ? 'background-color: #fee715' : ''
  ].filter(Boolean).join('; ');
</script>

{#if user}
  <FbToolTip
    as="span"
    className="fb-tooltip-user"
    text={tooltipText}
    tabindex={0}
    style={userStyle}
    onmouseenter={() => highlighted = true}
    onmouseleave={() => highlighted = false}
    onfocus={() => highlighted = true}
    onblur={() => highlighted = false}
  >
    {initials}: {user.nadexId}
  </FbToolTip>
{/if}

// reactOrig/src/components/fbToolTipUser.tsx
import React from 'react';
import { fbToolTip as FbToolTip } from './fbToolTip';

const fbDarkerYellow = '#fee715';

export interface fbToolTipUserUser {
  surname: string;
  firstNames: string;
  title: string;
  role: string;
  facility: string;
  nadexId: string;
}

export function fbToolTipUser({ user }: { user: fbToolTipUserUser }) {
  const [active, setActive] = React.useState(false);
  const [tooltipPosition, setTooltipPosition] = React.useState({ x: 0, y: 0 });

  const showTooltip = (element: HTMLElement) => {
    const rect = element.getBoundingClientRect();
    setTooltipPosition({
      x: Math.max(10, Math.min(rect.left, window.innerWidth - 250)),
      y: rect.bottom + 5,
    });
    setActive(true);
  };

  return (
    <>
      <span
        className="fb-tooltip-user"
        style={{ ...styles.badge, backgroundColor: active ? fbDarkerYellow : 'transparent' }}
        onMouseEnter={(event) => showTooltip(event.currentTarget)}
        onMouseLeave={() => setActive(false)}
        onFocus={(event) => showTooltip(event.currentTarget)}
        onBlur={() => setActive(false)}
        tabIndex={0}
      >
        {userInitials(user)}: {user.nadexId}
      </span>
      {active && (
        <FbToolTip
          x={tooltipPosition.x}
          y={tooltipPosition.y}
          text={userTooltipText(user)}
        />
      )}
    </>
  );
}

function userInitials(user: fbToolTipUserUser) {
  return `${user.firstNames.charAt(0)}${user.surname.charAt(0)}`.toUpperCase();
}

function userTooltipText(user: fbToolTipUserUser) {
  return [
    `${user.surname.toUpperCase()}, ${user.firstNames}, ${user.title}`,
    user.role,
    user.facility,
    user.nadexId,
  ].join('\n');
}

const styles = {
  badge: {
    display: 'inline-block',
    borderRadius: '0.2rem',
    padding: '0.05rem 0.2rem',
    outlineOffset: '0.1rem',
  } as React.CSSProperties,
};
