// svelte/src/components/fbValueError.svelte
<script lang="ts">
  export let message = '';
</script>

{#if message}
  <span class="fb-value-error" role="alert" aria-live="polite">
    <span class="material-icons" aria-hidden="true">error</span>
    <span>{message}</span>
  </span>
{/if}

<style>
  .fb-value-error {
    color: var(--fb-red);
    font-size: 0.8rem;
    font-weight: 500;
  }

  .fb-value-error .material-icons {
    color: var(--fb-red);
    background: white;
    font-size: 1rem;
    vertical-align: text-bottom;
    margin-right: 0.2rem;
  }
</style>

// reactOrig/src/components/fbValueError.tsx
import React from 'react';

interface fbValueErrorProps {
  message?: string;
}

export const fbValueError: React.FC<fbValueErrorProps> = ({ message }) => {
  if (!message) return null;

  return (
    <span
      className="fb-value-error"
      style={{
        color: '#d50000',
        fontFamily: "'Roboto', sans-serif",
        fontSize: '0.8rem',
        fontWeight: 500,
        lineHeight: 1.2,
      }}
    >
      <span
        className="material-icons"
        aria-hidden="true"
        style={{
          color: '#d50000',
          fontSize: '1rem',
        }}
      >
        error
      </span>
      <span>{message}</span>
    </span>
  );
};
