// src/caseNoteTracker/fbcntSelectedVolumes.tsx
import React from 'react';
import type { CntPickListEntry, CntStore, CntVolume } from './cntStore';
import { fbGreen } from './cntStyles';
import { locationDisplayText, FbcntLocationDisplay } from './fbcntLocationDisplay';
import { FbcntBadgeRequested } from './fbcntBadge';
import { FbcntTag } from './fbcntTag';

type LocationVolumeTree = Record<string, Record<string, Record<string, Record<string, CntVolume[]>>>>;

export function FbcntSelectedVolumes({ store, volumes }: { store?: CntStore; volumes: CntVolume[] }) {
  return <VolumeGroups store={store} volumes={volumes} />;
}

export function FbcntSelectedVolumesLocation({
  store,
  volumes,
  pickListEntries,
  requestedLocationUuid = '',
}: {
  store: CntStore;
  volumes: CntVolume[];
  pickListEntries: CntPickListEntry[];
  requestedLocationUuid?: string;
}) {
  const received = new Set(pickListEntries.filter((entry) => entry.received).map((entry) => entry.volumeUuid));
  const requested = new Set(
    store.requests
      .filter((request) => request.status === 'open' && (!requestedLocationUuid || request.toLocationUuid === requestedLocationUuid))
      .map((request) => request.volumeUuid),
  );
  if (!volumes.length) return <span style={styles.empty}>No volumes selected</span>;
  const tree = volumes.reduce<LocationVolumeTree>((acc, volume) => {
    acc[volume.healthBoard] ||= {};
    acc[volume.healthBoard][volume.locality] ||= {};
    acc[volume.healthBoard][volume.locality][volume.type] ||= {};
    const location = locationDisplayText(store, undefined, volume);
    acc[volume.healthBoard][volume.locality][volume.type][location] ||= [];
    acc[volume.healthBoard][volume.locality][volume.type][location].push(volume);
    return acc;
  }, {});
  return (
    <div style={styles.wrap}>
      {Object.entries(tree).map(([hb, localities]) => (
        <HighlightLevel key={hb} level={0}>
          <div>{hb}</div>
          {Object.entries(localities).map(([locality, types]) => (
            <HighlightLevel key={locality} level={1} style={styles.level1}>
              <div>{locality}</div>
              {Object.entries(types).map(([type, locations]) => (
                <HighlightLevel key={type} level={2} style={styles.level2}>
                  <div>{type}</div>
                  {Object.entries(locations).map(([location, items]) => {
                    const sortedItems = sortVolumes(items);
                    const allReceived = sortedItems.every((volume) => received.has(volume.uuid));
                    const anyRequested = sortedItems.some((volume) => requested.has(volume.uuid) && !received.has(volume.uuid));
                    return (
                      <HighlightLevel key={location} level={3} style={styles.volumeLocationGroup} tabIndex={0}>
                        <div>{volumeRangeLabel(sortedItems)}</div>
                        <div style={styles.locationUnderVolume}>
                          {anyRequested ? (
                            <FbcntBadgeRequested />
                          ) : (
                            <span
                              className="material-icons"
                              style={{ ...styles.tick, visibility: allReceived ? 'visible' : 'hidden' }}
                              aria-hidden="true"
                            >
                              check_circle
                            </span>
                          )}
                          <FbcntLocationDisplay store={store} volume={sortedItems[0]} withIcon compact />
                        </div>
                      </HighlightLevel>
                    );
                  })}
                </HighlightLevel>
              ))}
            </HighlightLevel>
          ))}
        </HighlightLevel>
      ))}
    </div>
  );
}

function VolumeGroups({
  volumes,
  store,
  renderVolumeDetail,
}: {
  volumes: CntVolume[];
  store?: CntStore;
  renderVolumeDetail?: (volume: CntVolume) => React.ReactNode;
}) {
  const tree = volumes.reduce<Record<string, Record<string, Record<string, CntVolume[]>>>>((acc, volume) => {
    acc[volume.healthBoard] ||= {};
    acc[volume.healthBoard][volume.locality] ||= {};
    acc[volume.healthBoard][volume.locality][volume.type] ||= [];
    acc[volume.healthBoard][volume.locality][volume.type].push(volume);
    return acc;
  }, {});
  if (!volumes.length) return <span style={styles.empty}>No volumes selected</span>;
  return (
    <div style={styles.wrap}>
      {Object.entries(tree).map(([hb, localities]) => (
        <HighlightLevel key={hb} level={0}>
          <div>{hb}</div>
          {Object.entries(localities).map(([locality, types]) => (
            <HighlightLevel key={locality} level={1} style={styles.locality}>
              <div>{locality}</div>
              {Object.entries(types).map(([type, items]) => (
                <HighlightLevel key={type} level={2} style={styles.type}>
                  <div>{type}</div>
                  {sortVolumes(items).map((volume) => (
                    <HighlightLevel
                      key={volume.uuid}
                      level={3}
                      style={renderVolumeDetail ? styles.volumeDetailWithAction : styles.volumeDetail}
                      tabIndex={0}
                    >
                      <span style={styles.volumeNameWithTag}>
                        {store && hasActiveTag(store, volume) && <FbcntTag />}
                        <span>{volumeLabel(volume)}</span>
                      </span>
                      {renderVolumeDetail?.(volume)}
                    </HighlightLevel>
                  ))}
                </HighlightLevel>
              ))}
            </HighlightLevel>
          ))}
        </HighlightLevel>
      ))}
    </div>
  );
}

function hasActiveTag(store: CntStore, volume: CntVolume) {
  return store.tags.some((tag) => tag.volumeUuid === volume.uuid && tag.status === 'active');
}

function HighlightLevel({
  level,
  style,
  tabIndex,
  children,
}: {
  key?: React.Key;
  level: number;
  style?: React.CSSProperties;
  tabIndex?: number;
  children: React.ReactNode;
}) {
  const [active, setActive] = React.useState(false);
  return (
    <div
      className={`fbcnt-highlight-level fbcnt-highlight-level-${level}`}
      style={{ ...style, ...highlightLevel(level, active) }}
      onMouseEnter={() => setActive(true)}
      onMouseLeave={() => setActive(false)}
      onFocusCapture={() => setActive(true)}
      onBlurCapture={() => setActive(false)}
      tabIndex={tabIndex}
    >
      {children}
    </div>
  );
}

function highlightLevel(level: number, active: boolean): React.CSSProperties {
  return {
    backgroundColor: active ? (level % 2 === 0 ? '#ffffcc' : '#fee715') : 'transparent',
    borderRadius: '0.2rem',
    padding: '0.08rem 0.2rem',
    marginTop: '0.08rem',
  };
}

function volumeLabel(volume: CntVolume) {
  return volume.temporary ? `Temporary volume ${volume.volumeNumber}` : `Volume ${volume.volumeNumber}`;
}

function sortVolumes(volumes: CntVolume[]) {
  return [...volumes].sort((a, b) => a.volumeNumber - b.volumeNumber || a.uuid.localeCompare(b.uuid));
}

function volumeRangeLabel(volumes: CntVolume[]) {
  if (volumes.length === 1) return volumeLabel(volumes[0]);
  const prefix = volumes.every((volume) => volume.temporary) ? 'Temporary volumes' : 'Volumes';
  return `${prefix} ${summariseNumberRanges(volumes.map((volume) => volume.volumeNumber))}`;
}

function summariseNumberRanges(numbers: number[]) {
  const uniqueNumbers = Array.from(new Set(numbers)).sort((a, b) => a - b);
  const ranges: string[] = [];
  for (let index = 0; index < uniqueNumbers.length; index += 1) {
    const start = uniqueNumbers[index];
    let end = start;
    while (index + 1 < uniqueNumbers.length && uniqueNumbers[index + 1] === end + 1) {
      index += 1;
      end = uniqueNumbers[index];
    }
    ranges.push(start === end ? String(start) : `${start}-${end}`);
  }
  return ranges.join(', ');
}

const styles = {
  wrap: {
    fontFamily: "'Roboto', sans-serif",
    fontSize: '0.95rem',
    lineHeight: 1.35,
  } as React.CSSProperties,
  locality: {
    marginLeft: '1rem',
  } as React.CSSProperties,
  type: {
    marginLeft: '1rem',
  } as React.CSSProperties,
  volumeDetail: {
    marginLeft: '1rem',
  } as React.CSSProperties,
  volumeDetailWithAction: {
    marginLeft: '1rem',
    display: 'grid',
    gridTemplateColumns: 'max-content 1fr',
    gap: '0.5rem',
    alignItems: 'start',
  } as React.CSSProperties,
  volumeNameWithTag: {
    display: 'inline-flex',
    gap: '0.25rem',
    alignItems: 'center',
  } as React.CSSProperties,
  level1: {
    marginLeft: '1rem',
  } as React.CSSProperties,
  level2: {
    marginLeft: '1rem',
  } as React.CSSProperties,
  level3: {
    marginLeft: '1rem',
  } as React.CSSProperties,
  level4: {
    marginLeft: '1rem',
    display: 'grid',
    gridTemplateColumns: '1.1rem 1fr',
    columnGap: '0.25rem',
    alignItems: 'start',
  } as React.CSSProperties,
  level4UnderVolume: {
    marginLeft: '2rem',
    display: 'grid',
    gridTemplateColumns: '1.1rem 1fr',
    columnGap: '0.25rem',
    alignItems: 'start',
  } as React.CSSProperties,
  volumeLocationGroup: {
    marginLeft: '1rem',
  } as React.CSSProperties,
  locationUnderVolume: {
    marginLeft: '1rem',
    display: 'grid',
    gridTemplateColumns: '1.1rem minmax(0, 1fr)',
    columnGap: '0.25rem',
    alignItems: 'start',
  } as React.CSSProperties,
  locationLine: {
    display: 'inline-flex',
    gap: '0.35rem',
    alignItems: 'flex-start',
  } as React.CSSProperties,
  tick: {
    fontFamily: 'Material Icons',
    backgroundColor: 'transparent',
    borderRadius: '50%',
    color: fbGreen,
    fontSize: '1rem',
    lineHeight: 1.2,
  } as React.CSSProperties,
  empty: {
    color: '#555',
    fontStyle: 'italic',
  } as React.CSSProperties,
};

// src/lib/caseNoteTracker/FbcntSelectedVolumes.svelte
<script lang="ts">
  import type { CntStore, CntVolume } from './cntStore';
  import FbcntTag from './FbcntTag.svelte';
  import HighlightBlock from './fbcntHighlightBlock.svelte';

  export let store: CntStore | undefined = undefined;
  export let volumes: CntVolume[] = [];
  export let compact = false;

  $: tree = buildTree(volumes);

  function buildTree(items: CntVolume[]) {
    const result: Record<string, Record<string, Record<string, CntVolume[]>>> = {};
    for (const volume of items) {
      result[volume.healthBoard] ||= {};
      result[volume.healthBoard][volume.locality] ||= {};
      result[volume.healthBoard][volume.locality][volume.type] ||= [];
      result[volume.healthBoard][volume.locality][volume.type].push(volume);
    }
    return result;
  }

  function volumeLabel(volume: CntVolume) {
    return volume.temporary ? `Temporary volume ${volume.volumeNumber}` : `Volume ${volume.volumeNumber}`;
  }

  function sortVolumes(items: CntVolume[]) {
    return [...items].sort((a, b) => a.volumeNumber - b.volumeNumber || a.uuid.localeCompare(b.uuid));
  }

  function hasActiveTag(volume: CntVolume) {
    return !!store?.tags?.some((tag) => tag.volumeUuid === volume.uuid && tag.status === 'active');
  }
</script>

{#if !volumes.length}
  <span class="empty">No volumes selected</span>
{:else}
  <div class="volume-tree" class:compact>
    {#each Object.entries(tree) as [hb, localities]}
      <div class="level">
        <HighlightBlock level={0} style={compact ? 'padding-top: 0; padding-bottom: 0; margin-top: 0;' : ''}>{hb}</HighlightBlock>
        {#each Object.entries(localities) as [locality, types]}
          <div class="level indented">
            <HighlightBlock level={1} style={compact ? 'padding-top: 0; padding-bottom: 0; margin-top: 0;' : ''}>{locality}</HighlightBlock>
            {#each Object.entries(types) as [type, items]}
              <div class="level indented">
                <HighlightBlock level={2} style={compact ? 'padding-top: 0; padding-bottom: 0; margin-top: 0;' : ''}>{type}</HighlightBlock>
                {#each sortVolumes(items) as volume (volume.uuid)}
                  <HighlightBlock level={3} style={`${compact ? 'padding-top: 0; padding-bottom: 0; margin-top: 0;' : ''} margin-left: 1rem;`}>
                    <span class="volume-name">
                      {#if hasActiveTag(volume)}<FbcntTag />{/if}
                      <span>{volumeLabel(volume)}</span>
                    </span>
                  </HighlightBlock>
                {/each}
              </div>
            {/each}
          </div>
        {/each}
      </div>
    {/each}
  </div>
{/if}

<style>
  .volume-tree { font-family: 'Roboto', sans-serif; font-size: 0.95rem; line-height: 1.35; }
  .volume-tree.compact { line-height: 1.05; }
  .level.indented { margin-left: 1rem; }
  .volume-name { display: inline-flex; gap: 0.25rem; align-items: center; }
  .empty { color: #555; font-style: italic; }
</style>
