// reactOrig/src/caseNoteTracker/fbcntLocationDisplay.tsx
import React from 'react';
import type { CntLocation, CntStore, CntVolume } from './cntStore';
import { fbBlue } from './cntStyles';

type LocationDisplayProps = {
  store: CntStore;
  locationUuid?: string;
  volume?: CntVolume;
  withIcon?: boolean;
  compact?: boolean;
};

export function FbcntLocationDisplay({ store, locationUuid, volume, withIcon = false, compact = false }: LocationDisplayProps) {
  const location = store.locations.find((item) => item.uuid === (locationUuid || volume?.currentLocationUuid));
  const lines = location ? locationDisplayLines(location, volume) : [];
  if (!lines.length) return null;
  return (
    <span style={styles.wrapper}>
      {withIcon && (
        <span className="material-icons" style={styles.icon} aria-hidden="true">
          view_list
        </span>
      )}
      <span style={{ ...styles.lines, ...(compact ? styles.compactLines : {}) }}>
        {lines.map((line, index) => (
          <span key={`${line}-${index}`} style={styles.line}>{line}</span>
        ))}
      </span>
    </span>
  );
}

export function locationDisplayText(store: CntStore, locationUuid?: string, volume?: CntVolume) {
  const location = store.locations.find((item) => item.uuid === (locationUuid || volume?.currentLocationUuid));
  return location ? locationDisplayLines(location, volume).join(' / ') : '';
}

export function locationDisplayLines(location: CntLocation, volume?: Pick<CntVolume, 'healthBoard' | 'locality'>) {
  return [
    location.extra,
    location.department,
    location.facility,
    location.healthBoard,
  ].filter(Boolean);
}

const styles = {
  wrapper: {
    display: 'inline-flex',
    gap: '0.25rem',
    alignItems: 'start',
    width: 'max-content',
    maxWidth: '100%',
    minWidth: 0,
  } as React.CSSProperties,
  icon: {
    fontFamily: 'Material Icons',
    color: fbBlue,
    fontSize: '1rem',
    lineHeight: 1.15,
    marginTop: '0.05rem',
  } as React.CSSProperties,
  lines: {
    display: 'grid',
    gap: '0.04rem',
    minWidth: 0,
    maxWidth: '100%',
  } as React.CSSProperties,
  compactLines: {
    gap: 0,
  } as React.CSSProperties,
  line: {
    display: 'block',
    overflowWrap: 'break-word',
  } as React.CSSProperties,
};

// src/lib/caseNoteTracker/FbcntLocationDisplay.svelte
<script lang="ts">
  import type { CntLocation, CntStore, CntVolume } from './cntStore';

  export let store: CntStore;
  export let locationUuid = '';
  export let volume: CntVolume | undefined = undefined;
  export let withIcon = false;
  export let compact = false;

  $: location = store?.locations.find((item) => item.uuid === (locationUuid || volume?.currentLocationUuid));
  $: lines = location ? locationDisplayLines(location, volume) : [];

  export function locationDisplayLines(locationValue: CntLocation, volumeValue?: Pick<CntVolume, 'healthBoard' | 'locality'>) {
    return [
      locationValue.extra,
      locationValue.department,
      locationValue.facility,
      locationValue.healthBoard,
    ].filter(Boolean);
  }
</script>

{#if lines.length}
  <span class="location-display">
    {#if withIcon}
      <span class="material-icons location-icon" aria-hidden="true">view_list</span>
    {/if}
    <span class="location-lines" class:compact>
      {#each lines as line, index (`${line}-${index}`)}
        <span>{line}</span>
      {/each}
    </span>
  </span>
{/if}

<style>
  .location-display {
    display: inline-flex;
    gap: 0.25rem;
    align-items: start;
    width: max-content;
    max-width: 100%;
    min-width: 0;
  }

  .location-icon {
    flex: 0 0 auto;
    width: 1rem;
    margin-top: 0.05rem;
    color: #1b6ec2;
    font-family: 'Material Icons';
    font-size: 1rem;
    line-height: 1.15;
  }

  .location-lines {
    display: grid;
    gap: 0.04rem;
    min-width: 0;
    max-width: 100%;
  }

  .location-lines.compact {
    gap: 0;
  }

  .location-lines span {
    display: block;
    overflow-wrap: break-word;
  }
</style>
