// src/lib/components/fb/fbAddButton.svelte
<script lang="ts">
  let {
    label,
    editable = false,
    class: className = '',
    onLabelChange,
    onClick,
    onclick
  }: {
    label: string;
    editable?: boolean;
    class?: string;
    onLabelChange?: (label: string) => void;
    onClick?: (event: MouseEvent) => void;
    onclick?: (event: MouseEvent) => void;
  } = $props();

  function commitLabel(event: FocusEvent) {
    onLabelChange?.((event.currentTarget as HTMLElement).textContent?.trim() || label);
  }

  let hovered = $state(false);
  let focused = $state(false);
  const active = $derived(hovered || focused);
  const componentStyle = $derived(
    [
      `background-color: ${active ? '#fee715' : 'white'}`,
      `color: ${active ? 'black' : '#1b6ec2'}`,
      `border: 0.1rem solid ${active ? 'black' : '#1b6ec2'}`,
      'border-radius: 0.4rem',
      'height: 2rem',
      'line-height: 1.8rem',
      'padding: 0 0.8rem',
      "font-family: 'Roboto', sans-serif",
      'font-size: 1rem',
      'font-weight: 300',
      'cursor: pointer',
      'transition: background-color 0.2s ease, color 0.2s ease, border-color 0.2s ease'
    ].join('; ')
  );
</script>

<button
  type="button"
  class={`fb-add-button ${className}`.trim()}
  style={componentStyle}
  onmouseenter={() => hovered = true}
  onmouseleave={() => hovered = false}
  onfocus={() => focused = true}
  onblur={() => focused = false}
  onclick={onClick || onclick}
>
  {#if editable}
    <span
      contenteditable="true"
      role="textbox"
      tabindex="0"
      onblur={commitLabel}
      onclick={(event) => event.stopPropagation()}
      onmousedown={(event) => event.stopPropagation()}
      onkeydown={(event) => {
        if (event.key === 'Escape' || event.key === 'Enter') {
          event.preventDefault();
          (event.currentTarget as HTMLElement).blur();
        }
      }}
    >{label}</span>
  {:else}
    {label}
  {/if}
</button>

<style>
  span {
    outline: none;
  }
</style>

// src/components/fbAddButton.tsx
import React from 'react';

interface AddButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  label: string;
  editable?: boolean;
  onLabelChange?: (label: string) => void;
}

export const fbAddButton: React.FC<AddButtonProps> = ({ label, editable = false, onLabelChange, style, className = '', ...props }) => {
  const [hovered, setHovered] = React.useState(false);

  return (
    <button
      type="button"
      className={`fb-add-button ${className}`}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{
        backgroundColor: hovered ? '#fee715' : 'white',
        color: hovered ? 'black' : '#1b6ec2',
        border: hovered ? '0.1rem solid black' : '0.1rem solid #1b6ec2',
        borderRadius: '0.4rem',
        height: '2.0rem',
        lineHeight: '1.8rem',
        padding: '0 0.8rem',
        fontFamily: "'Roboto', sans-serif",
        fontSize: '1rem',
        fontWeight: 300,
        cursor: 'pointer',
        transition: 'background-color 0.2s ease, color 0.2s ease, border-color 0.2s ease',
        ...style
      }}
      {...props}
    >
      {editable ? (
        <span
          contentEditable
          suppressContentEditableWarning
          onMouseDown={(event) => event.stopPropagation()}
          onClick={(event) => event.stopPropagation()}
          onBlur={(event) => onLabelChange?.(event.currentTarget.textContent?.trim() || label)}
          onKeyDown={(event) => {
            if (event.key === 'Escape' || event.key === 'Enter') {
              event.preventDefault();
              event.currentTarget.blur();
            }
          }}
          style={{ outline: 'none' }}
        >
          {label}
        </span>
      ) : label}
    </button>
  );
};
