// svelte/src/components/fbAddFormMenu.svelte
<script lang="ts">
  export let onSelectFormType: (formType: string) => void = () => {};
  export let onCancel: () => void = () => {};

  const items = [
    { value: 'outpatient_outcome', label: 'Outpatient outcome form' },
    { value: 'waiting_list', label: 'Waiting list card' },
    { value: 'treatment_summary', label: 'Treatment summary' },
    { value: 'operation_note', label: 'Operation note' },
  ];
</script>

<button type="button" class="fb-add-menu-overlay" aria-label="Close new form menu" onclick={onCancel}></button>
<div class="fb-add-form-menu" role="menu" aria-label="New form or document">
  {#each items as item}
    <button type="button" role="menuitem" onclick={() => onSelectFormType(item.value)}>{item.label}</button>
  {/each}
  <div class="fb-add-form-menu-rule"></div>
  <button type="button" role="menuitem" onclick={onCancel}>Cancel</button>
</div>

<style>
  .fb-add-menu-overlay {
    position: fixed;
    inset: 0;
    z-index: 1999;
    border: 0;
    background: transparent;
  }

  .fb-add-form-menu {
    position: absolute;
    left: 0;
    bottom: calc(100% + 0.4rem);
    min-width: 200px;
    padding: 0.5rem;
    border: 0.2rem solid var(--fb-blue);
    border-radius: 0.4rem;
    background: white;
    box-shadow: 0 2px 8px rgb(0 0 0 / 15%);
    z-index: 2000;
  }

  .fb-add-form-menu button {
    width: 100%;
    padding: 0.5rem;
    border: 0;
    background: white;
    cursor: pointer;
    text-align: left;
    font-size: 1rem;
    font-weight: 400;
  }

  .fb-add-form-menu button:hover,
  .fb-add-form-menu button:focus {
    background: #e3f2fd;
  }

  .fb-add-form-menu-rule {
    border-top: 0.1rem solid silver;
    margin: 0.5rem 0;
  }
</style>

// src/components/fbAddFormMenu.tsx
import React from 'react';

interface AddFormMenuProps {
  onSelectFormType: (formType: 'outpatient_outcome' | 'waiting_list' | 'operation_note' | 'treatment_summary') => void;
  onCancel: () => void;
  buttonRef: React.RefObject<HTMLButtonElement>;
}

export const fbAddFormMenu: React.FC<AddFormMenuProps> = ({ onSelectFormType, onCancel, buttonRef }) => {
  const [menuPosition, setMenuPosition] = React.useState<{ top: number; left: number }>({ top: 0, left: 0 });

  React.useEffect(() => {
    if (buttonRef.current) {
      const rect = buttonRef.current.getBoundingClientRect();
      setMenuPosition({
        top: rect.top - 4, // Position above button with small gap
        left: rect.left
      });
    }
  }, [buttonRef]);

  return (
    <>
      {/* Overlay to close menu on outside click */}
      <div
        onClick={onCancel}
        style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          zIndex: 1999
        }}
      />

      {/* Menu */}
      <div
        style={{
          position: 'fixed',
          top: `${menuPosition.top}px`,
          left: `${menuPosition.left}px`,
          transform: 'translateY(-100%)',
          backgroundColor: 'white',
          border: '0.2rem solid rgb(27, 110, 194)',
          borderRadius: '0.4rem',
          padding: '0.5rem',
          boxShadow: '0 2px 8px rgba(0,0,0,0.15)',
          zIndex: 2000,
          fontFamily: "'Roboto', sans-serif",
          minWidth: '200px'
        }}
      >
        <button
          type="button"
          onClick={() => onSelectFormType('outpatient_outcome')}
          style={{
            width: '100%',
            textAlign: 'left',
            padding: '0.5rem',
            border: 'none',
            backgroundColor: 'white',
            cursor: 'pointer',
            fontFamily: "'Roboto', sans-serif",
            fontSize: '1rem',
            fontWeight: 400,
            transition: 'background-color 0.2s ease-out'
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.backgroundColor = '#e3f2fd';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.backgroundColor = 'white';
          }}
        >
          Outpatient outcome form
        </button>
        <button
          type="button"
          onClick={() => onSelectFormType('waiting_list')}
          style={{
            width: '100%',
            textAlign: 'left',
            padding: '0.5rem',
            border: 'none',
            backgroundColor: 'white',
            cursor: 'pointer',
            fontFamily: "'Roboto', sans-serif",
            fontSize: '1rem',
            fontWeight: 400,
            transition: 'background-color 0.2s ease-out'
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.backgroundColor = '#e3f2fd';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.backgroundColor = 'white';
          }}
        >
          Waiting list card
        </button>
        <button
          type="button"
          onClick={() => onSelectFormType('treatment_summary')}
          style={{
            width: '100%',
            textAlign: 'left',
            padding: '0.5rem',
            border: 'none',
            backgroundColor: 'white',
            cursor: 'pointer',
            fontFamily: "'Roboto', sans-serif",
            fontSize: '1rem',
            fontWeight: 400,
            transition: 'background-color 0.2s ease-out'
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.backgroundColor = '#e3f2fd';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.backgroundColor = 'white';
          }}
        >
          Treatment summary
        </button>
        <button
          type="button"
          onClick={() => onSelectFormType('operation_note')}
          style={{
            width: '100%',
            textAlign: 'left',
            padding: '0.5rem',
            border: 'none',
            backgroundColor: 'white',
            cursor: 'pointer',
            fontFamily: "'Roboto', sans-serif",
            fontSize: '1rem',
            fontWeight: 400,
            transition: 'background-color 0.2s ease-out'
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.backgroundColor = '#e3f2fd';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.backgroundColor = 'white';
          }}
        >
          Operation note
        </button>
        <div style={{ borderTop: '1px solid silver', margin: '0.5rem 0' }} />
        <button
          type="button"
          onClick={onCancel}
          style={{
            width: '100%',
            textAlign: 'left',
            padding: '0.5rem',
            border: 'none',
            backgroundColor: 'white',
            cursor: 'pointer',
            fontFamily: "'Roboto', sans-serif",
            fontSize: '1rem',
            fontWeight: 400,
            transition: 'background-color 0.2s ease-out'
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.backgroundColor = '#e3f2fd';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.backgroundColor = 'white';
          }}
        >
          Cancel
        </button>
      </div>
    </>
  );
};
