// src/lib/components/fb/fbDateHeightWeightBMIRow.svelte
<script lang="ts">
  import FbDateExact from './fbDateExact.svelte';
  import FbGridCell from './fbGridCell.svelte';
  import FbGridRow from './fbGridRow.svelte';
  import FbNumberInputWithUnits from './fbNumberInputWithUnits.svelte';
  import FbQuestion from './fbQuestion.svelte';
  import FbReadOnly from './fbReadOnly.svelte';
  import { calculateBmi } from '$lib/utils/bmi';

  let {
    dateRecorded = $bindable(''),
    heightCm = $bindable(''),
    weightKg = $bindable(''),
    readonly = false,
    onDateRecordedChange,
    onHeightCmChange,
    onWeightKgChange
  }: {
    dateRecorded?: string;
    heightCm?: string;
    weightKg?: string;
    readonly?: boolean;
    onDateRecordedChange?: (value: string) => void;
    onHeightCmChange?: (value: string) => void;
    onWeightKgChange?: (value: string) => void;
  } = $props();

  const bmi = $derived(calculateBmi(heightCm, weightKg));
</script>

<FbGridRow cols={4}>
  <FbGridCell>
    <FbQuestion label="Date recorded" subfield>
      <FbDateExact name="dateRecorded" bind:value={dateRecorded} {readonly} onChange={onDateRecordedChange} />
    </FbQuestion>
  </FbGridCell>
  <FbGridCell>
    <FbNumberInputWithUnits label="Height" subfield bind:value={heightCm} units="cm" {readonly} onChange={onHeightCmChange} />
  </FbGridCell>
  <FbGridCell>
    <FbNumberInputWithUnits label="Weight" subfield bind:value={weightKg} units="kg" {readonly} onChange={onWeightKgChange} />
  </FbGridCell>
  <FbGridCell>
    <div title="This BMI calculation is not validated or certified for clinical use">
      <FbReadOnly label="Uncertified calculated BMI (kg/m2)" value={bmi === null ? '' : String(bmi)} preserveGridSpace bigLabel />
    </div>
  </FbGridCell>
</FbGridRow>

// src/components/fbDateHeightWeightBMIRow.tsx
import React from 'react';
import { fbGridRow as FbGridRow } from './fbGridRow';
import { fbGridCell as FbGridCell } from './fbGridCell';
import { fbQuestion as FbQuestion } from './fbQuestion';
import { fbDateExact as FbDateExact } from './fbDateExact';
import { fbNumberInputWithUnits as FbNumberInputWithUnits } from './fbNumberInputWithUnits';
import { fbRoVField as FbRoVField } from './fbRoVField';
import { calculateBmi } from '../utils/bmi';

interface fbDateHeightWeightBMIRowProps {
  dateRecorded: string;
  heightCm: string;
  weightKg: string;
  onDateRecordedChange: (value: string) => void;
  onHeightCmChange: (value: string) => void;
  onWeightKgChange: (value: string) => void;
}

export const fbDateHeightWeightBMIRow: React.FC<fbDateHeightWeightBMIRowProps> = ({
  dateRecorded,
  heightCm,
  weightKg,
  onDateRecordedChange,
  onHeightCmChange,
  onWeightKgChange,
}) => {
  const bmi = calculateBmi(heightCm, weightKg);
  return (
    <FbGridRow cols={4}>
      <FbGridCell>
        <FbQuestion label="Date recorded" labelStyle={{ fontWeight: 300 }}>
          <FbDateExact name="dateRecorded" value={dateRecorded} onChange={onDateRecordedChange} />
        </FbQuestion>
      </FbGridCell>
      <FbGridCell>
        <FbQuestion label="Height" labelStyle={{ fontWeight: 300 }}>
          <FbNumberInputWithUnits value={heightCm} onChange={onHeightCmChange} units="cm" />
        </FbQuestion>
      </FbGridCell>
      <FbGridCell>
        <FbQuestion label="Weight" labelStyle={{ fontWeight: 300 }}>
          <FbNumberInputWithUnits value={weightKg} onChange={onWeightKgChange} units="kg" />
        </FbQuestion>
      </FbGridCell>
      <FbGridCell>
        <div title="This BMI calculation is not validated or certified for clinical use">
          <FbRoVField label="Uncertified calculated BMI (kg/m2)" value={bmi === null ? '' : String(bmi)} preserveGridSpace labelProps={{ style: { fontSize: '1rem' } }} />
        </div>
      </FbGridCell>
    </FbGridRow>
  );
};
