// svelte/src/components/fbDropdown.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import FbQuestion from './fbQuestion.svelte';

  export let id = '';
  export let name = '';
  export let label = '';
  export let value = '';
  export let required = false;
  export let placeholder = '';
  export let options: Array<{ value: string; label: string }> = [];
  export let valueError = '';
  export let tooltip = '';
  export let onChange: (value: string) => void = () => {};
  export let change: (value: string) => void = () => {};

  const dispatch = createEventDispatcher<{ change: string }>();

  function emitValue() {
    onChange(value);
    change(value);
    dispatch('change', value);
  }
</script>

{#if label}
  <FbQuestion {label} {required} {valueError} {tooltip}>
    <select
      {id}
      {name}
      bind:value
      onchange={emitValue}
    >
      {#if placeholder}
        <option value="">{placeholder}</option>
      {/if}
      {#each options as option}
        <option value={option.value}>{option.label}</option>
      {/each}
    </select>
  </FbQuestion>
{:else}
  <select
    {id}
    {name}
    bind:value
    onchange={emitValue}
  >
    {#if placeholder}
      <option value="">{placeholder}</option>
    {/if}
    {#each options as option}
      <option value={option.value}>{option.label}</option>
    {/each}
  </select>
{/if}

<style>
  select {
    width: 100%;
    max-width: 24rem;
    height: 2rem;
    border: 0.1rem solid silver;
    border-radius: 0.4rem;
    padding: 0.2rem 0.4rem;
    font-size: 1rem;
  }
</style>

// src/components/fbDropdown.tsx
import React from 'react';
import { fbQuestion as FbQuestion } from './fbQuestion';

interface DropdownOption {
  value: string;
  label: string;
}

interface fbDropdownProps {
  label?: string;
  value: string;
  onChange: (value: string) => void;
  options: (DropdownOption | string)[];
  required?: boolean;
  id?: string;
  name?: string;
  className?: string;
  style?: React.CSSProperties;
  selectStyle?: React.CSSProperties;
  placeholder?: string;
  subfield?: boolean;
  valueError?: string;
}

export const fbDropdown: React.FC<fbDropdownProps> = ({
  label,
  value = '',
  onChange,
  options,
  required = false,
  id,
  name,
  className = '',
  style,
  selectStyle,
  placeholder,
  subfield = false,
  valueError,
}) => {
  const parsedOptions = options.map((opt) => {
    if (typeof opt === 'string') {
      return { value: opt, label: opt };
    }
    return opt;
  });

  const renderSelect = () => {
    return (
      <select
        id={id}
        name={name}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        required={required}
        className="w-full text-black"
        style={{
          fontFamily: "'Roboto', sans-serif",
          fontSize: '1rem',
          fontWeight: 400,
          border: '0.1rem solid silver',
          borderRadius: '0.4rem',
          boxSizing: 'border-box',
          height: '2rem',
          padding: '0.2rem 0.4rem',
          backgroundColor: 'white',
          ...selectStyle,
        }}
      >
        {placeholder !== undefined && (
          <option value="">{placeholder}</option>
        )}
        {parsedOptions.map((opt) => (
          <option key={opt.value} value={opt.value}>
            {opt.label}
          </option>
        ))}
      </select>
    );
  };

  if (!label) {
    return renderSelect();
  }

  return (
    <FbQuestion
      label={label}
      required={required}
      className={className}
      style={style}
      labelStyle={subfield ? { fontWeight: 300, fontSize: '1rem' } : undefined}
      valueError={valueError}
    >
      {renderSelect()}
    </FbQuestion>
  );
};
