// src/lib/components/fb/fbFormHistoryMenu.svelte
<script lang="ts">
  import FbButton from './fbButton.svelte';
  import FbTable from './fbTable.svelte';
  import FbTableBody from './fbTableBody.svelte';
  import FbTableCell from './fbTableCell.svelte';
  import FbTableHeader from './fbTableHeader.svelte';
  import FbTableHeaderCell from './fbTableHeaderCell.svelte';
  import FbTableRow from './fbTableRow.svelte';

  export type FbFormHistoryItem = {
    form_version: number;
    document_datetime?: string | null;
    event_datetime?: string | null;
    saved_by?: string | null;
    details?: string | null;
  };

  export let history: FbFormHistoryItem[] = [];
  export let onViewVersion: (version: number) => void = () => {};
  export let onClose: () => void = () => {};

  function formatDateTime(value?: string | null) {
    if (!value) return '';
    const date = new Date(value);
    if (Number.isNaN(date.getTime())) return value;
    const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    return `${String(date.getDate()).padStart(2, '0')}-${monthNames[date.getMonth()]}-${date.getFullYear()} ${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`;
  }
</script>

<button type="button" class="history-backdrop" aria-label="Close history" onclick={onClose}></button>
<section class="history-menu" aria-label="Form history">
  <h2>History</h2>
  <FbTable aria-label="Form history">
    <FbTableHeader>
      <FbTableRow>
        <FbTableHeaderCell>Date and time</FbTableHeaderCell>
        <FbTableHeaderCell>Saved by</FbTableHeaderCell>
        <FbTableHeaderCell></FbTableHeaderCell>
      </FbTableRow>
    </FbTableHeader>
    <FbTableBody>
      {#if history.length === 0}
        <FbTableRow>
          <FbTableCell colspan={3}><span class="empty">No saved versions found</span></FbTableCell>
        </FbTableRow>
      {:else}
        {#each history as item (item.form_version)}
          <FbTableRow>
            <FbTableCell>{formatDateTime(item.document_datetime || item.event_datetime)}</FbTableCell>
            <FbTableCell>{item.saved_by || item.details || ''}</FbTableCell>
            <FbTableCell><button type="button" class="view-old-version" onclick={() => onViewVersion(item.form_version)}>View old version</button></FbTableCell>
          </FbTableRow>
        {/each}
      {/if}
    </FbTableBody>
  </FbTable>
  <div class="history-actions">
    <FbButton type="button" onClick={onClose}>Close</FbButton>
  </div>
</section>

<style>
  .history-backdrop {
    position: fixed;
    inset: 0;
    z-index: 10000;
    border: 0;
    background: rgb(0 0 0 / 25%);
  }

  .history-menu {
    position: fixed;
    left: 1rem;
    bottom: 3.6rem;
    z-index: 10001;
    width: min(44rem, calc(100vw - 2rem));
    max-height: calc(100vh - 5rem);
    overflow: auto;
    box-sizing: border-box;
    padding: 0.8rem;
    border: 0.1rem solid var(--fb-blue);
    border-radius: 0.4rem;
    background: white;
    font-family: 'Roboto', sans-serif;
  }

  h2 {
    margin: 0 0 0.6rem;
    font-size: 1.2rem;
    font-weight: 500;
  }

  .empty {
    display: inline-block;
    padding: 0.3rem;
    font-style: italic;
  }

  .view-old-version {
    border: 0.1rem solid var(--fb-blue);
    border-radius: 0.25rem;
    background: var(--fb-blue);
    color: white;
    cursor: pointer;
    font-family: 'Roboto', sans-serif;
    font-size: 0.85rem;
    font-weight: 300;
    padding: 0.15rem 0.45rem;
  }

  .view-old-version:hover,
  .view-old-version:focus {
    border-color: var(--fb-active-darker-yellow);
    background: var(--fb-active-darker-yellow);
    color: black;
  }

  .history-actions {
    display: flex;
    justify-content: flex-end;
    margin-top: 0.8rem;
  }
</style>

// src/components/fbFormHistoryMenu.tsx
import * as React from 'react';
import { fbSmallerButton as FbSmallerButton } from './fbSmallerButton';
import { fbViewOldVersion as FbViewOldVersion } from './fbViewOldVersion';
import { fbTableHeaderCell as FbTableHeaderCell } from './fbTable';

export interface fbFormHistoryItem {
  form_version: number;
  document_datetime?: string | null;
  event_datetime?: string | null;
  saved_by?: string | null;
}

interface fbFormHistoryMenuProps {
  history: fbFormHistoryItem[];
  anchorRect: DOMRect | null;
  onViewVersion: (version: number) => void;
  onClose: () => void;
}

const formatDateTime = (value?: string | null) => {
  if (!value) return '';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${date.getDate().toString().padStart(2, '0')}-${monthNames[date.getMonth()]}-${date.getFullYear()} ${date.getHours().toString().padStart(2, '0')}:${date.getMinutes().toString().padStart(2, '0')}`;
};

export const fbFormHistoryMenu: React.FC<fbFormHistoryMenuProps> = ({
  history,
  anchorRect,
  onViewVersion,
  onClose,
}) => {
  const width = Math.min(44 * 16, Math.max(22 * 16, window.innerWidth - 16));
  const left = Math.max(8, Math.min(anchorRect?.left ?? 16, window.innerWidth - width - 8));
  const bottom = anchorRect ? Math.max(8, window.innerHeight - anchorRect.top + 4) : 16;
  const maxHeight = anchorRect ? Math.max(12 * 16, anchorRect.top - 12) : Math.max(12 * 16, window.innerHeight - 32);

  return (
  <div
    style={{
      position: 'fixed',
      inset: 0,
      backgroundColor: 'rgba(0,0,0,0.25)',
      zIndex: 10000,
    }}
    onMouseDown={(e) => {
      if (e.target === e.currentTarget) onClose();
    }}
  >
    <div
      style={{
        position: 'fixed',
        bottom,
        left,
        backgroundColor: 'white',
        border: '0.1rem solid #1b6ec2',
        borderRadius: '0.4rem',
        padding: '0.8rem',
        width,
        maxHeight,
        overflow: 'auto',
        fontFamily: "'Roboto', sans-serif",
      }}
    >
      <h2 style={{ fontSize: '1.2rem', fontWeight: 500, margin: '0 0 0.6rem 0' }}>History</h2>
      <table style={{ width: '100%', borderCollapse: 'collapse' }}>
        <thead>
          <tr>
            <FbTableHeaderCell>Date and time</FbTableHeaderCell>
            <FbTableHeaderCell>Saved by</FbTableHeaderCell>
            <FbTableHeaderCell></FbTableHeaderCell>
          </tr>
        </thead>
        <tbody>
          {history.length === 0 ? (
            <tr>
              <td colSpan={3} style={{ padding: '0.6rem 0.3rem', borderBottom: '0.1rem solid #eee', fontStyle: 'italic' }}>
                No saved versions found
              </td>
            </tr>
          ) : (
            history.map((item) => (
              <tr key={item.form_version}>
                <td style={{ padding: '0.3rem', borderBottom: '0.1rem solid #eee' }}>
                  {formatDateTime(item.document_datetime || item.event_datetime)}
                </td>
                <td style={{ padding: '0.3rem', borderBottom: '0.1rem solid #eee' }}>
                  {item.saved_by || ''}
                </td>
                <td style={{ padding: '0.3rem', borderBottom: '0.1rem solid #eee', textAlign: 'right' }}>
                  <FbViewOldVersion onClick={() => onViewVersion(item.form_version)} />
                </td>
              </tr>
            ))
          )}
        </tbody>
      </table>
      <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '0.8rem' }}>
        <FbSmallerButton onClick={onClose}>Close</FbSmallerButton>
      </div>
    </div>
  </div>
  );
};
