// svelte/src/components/fbHeader.svelte
<script lang="ts">
  import FbAddressograph from './fbAddressograph.svelte';
  import FbBadgeDraft from './fbBadgeDraft.svelte';
  import FbBadgeHighlySensitive from './fbBadgeHighlySensitive.svelte';
  import type { Patient } from '../lib/types';
  import { fbBlue } from '../lib/constants';

  export let title = '';
  export let patient: Patient | null = null;
  export let formStatus = '';
  export let highlySensitive = false;
</script>

<header class="fb-header" style="border-bottom: 0.2rem solid {fbBlue};">
  <div class="fb-header-title-block">
    <div class="fb-header-badges">
      {#if formStatus === 'draft'}<FbBadgeDraft />{/if}
      {#if highlySensitive}<FbBadgeHighlySensitive />{/if}
    </div>
    <h1>{title}</h1>
  </div>
  <FbAddressograph
    nhsNumber={patient?.nhs_number}
    surname={patient?.surname}
    forenames={patient?.forenames}
    title={patient?.title}
    addressLine1={patient?.address_line1}
    addressLine2={patient?.address_line2}
    addressLine3={patient?.address_line3}
    addressLine4={patient?.address_line4}
    crn={patient?.crn}
    dateOfBirth={patient?.date_of_birth}
    sex={patient?.sex}
  />
</header>

<style>
  .fb-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 1rem;
    padding: 0.4rem;
    background: white;
  }

  h1 {
    margin: 0;
    font-size: 2rem;
    font-weight: 500;
  }

  .fb-header-title-block {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
    align-items: flex-start;
  }

  .fb-header-badges {
    display: flex;
    gap: 0.4rem;
    align-items: center;
    min-height: 1.4rem;
  }

  @media (max-width: 767px) {
    .fb-header {
      flex-direction: column;
    }
  }
</style>

// src/components/fbHeader.tsx
import React from 'react';
import { fbAddressograph as Addressograph } from './fbAddressograph';
import { fbBadgeDraft as DraftBadge } from './fbBadgeDraft';
import { fbBadgeHighlySensitive as HighlySensitiveBadge } from './fbBadgeHighlySensitive';

interface fbHeaderProps {
  title: string;
  patient: any;
  formStatus: 'draft' | 'final' | string;
  badgeText?: string;
  highlySensitive?: boolean;
  style?: React.CSSProperties;
}

export const fbHeader: React.FC<fbHeaderProps> = ({
  title,
  patient,
  formStatus,
  badgeText = 'Draft',
  highlySensitive = false,
  style,
}) => {
  return (
    <div
      className="fb-header-with-divider"
      style={{
        backgroundColor: 'white',
        borderBottom: '0.2rem solid #1b6ec2',
        padding: '0.4rem 0.8rem',
        boxSizing: 'border-box',
        ...style
      }}
    >
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        {/* Title area with document badges */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
          <div style={{ display: 'flex', gap: '0.4rem', minHeight: formStatus === 'draft' || highlySensitive ? undefined : 0 }}>
            {formStatus === 'draft' && <DraftBadge text={badgeText} />}
            {highlySensitive && <HighlySensitiveBadge />}
          </div>
          <h1
            style={{
              fontFamily: "'Space Grotesk', sans-serif",
              fontSize: '1.8rem',
              fontWeight: 700,
              color: '#333',
              margin: 0,
              lineHeight: '2rem',
            }}
          >
            {title}
          </h1>
        </div>

        {/* Dynamic patient address block on the right */}
        {patient && (
          <div className="fb-addressograph-container" style={{ minWidth: '22rem' }}>
            <Addressograph patient={patient} />
          </div>
        )}
      </div>
    </div>
  );
};
