// src/lib/components/fb/fbOutpatientAppointmentTile.svelte
<script lang="ts">
  import FbHoverTooltipField from './fbHoverTooltipField.svelte';

  let {
    dateTime,
    clinicName,
    speciality,
    src
  }: {
    dateTime: string;
    clinicName: string;
    speciality: string;
    src: string;
  } = $props();
</script>

<div class="fb-outpatient-appointment-tile" data-lily-reference-component="description-list">
  <FbHoverTooltipField tooltipText="Appointment Date & Time">
    <div class="fb-outpatient-appointment-tile-light">{dateTime}</div>
  </FbHoverTooltipField>
  <div class="fb-outpatient-appointment-tile-title">Outpatient appointment</div>
  {#if clinicName}
    <FbHoverTooltipField tooltipText="Clinic Name">
      <div class="fb-outpatient-appointment-tile-light">{clinicName}</div>
    </FbHoverTooltipField>
  {/if}
  {#if speciality}
    <FbHoverTooltipField tooltipText="Speciality">
      <div class="fb-outpatient-appointment-tile-light">{speciality}</div>
    </FbHoverTooltipField>
  {/if}
  {#if src}
    <FbHoverTooltipField tooltipText="Senior Responsible Clinician">
      <div class="fb-outpatient-appointment-tile-light">{src}</div>
    </FbHoverTooltipField>
  {/if}
</div>

<style>
  .fb-outpatient-appointment-tile {
    display: flex;
    flex-direction: column;
    gap: 0;
    font-family: 'Roboto', sans-serif;
    color: black;
    font-size: 1rem;
    font-weight: 300;
    line-height: 1.15;
    text-align: left;
  }

  .fb-outpatient-appointment-tile-title {
    font-weight: 500;
  }

  .fb-outpatient-appointment-tile-light {
    font-weight: 300;
  }
</style>

// src/components/fbOutpatientAppointmentTile.tsx
import React, { useState } from 'react';

interface OutpatientAppointmentTileProps {
  dateTime: string;
  clinicName: string;
  speciality: string;
  src: string;
}

const HoverTooltipField: React.FC<{ tooltipText: string; children: React.ReactNode }> = ({ tooltipText, children }) => {
  const [hovered, setHovered] = useState(false);
  return (
    <div 
      style={{ position: 'relative', display: 'block', width: 'fit-content' }}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      {children}
      {hovered && (
        <div style={{
          position: 'absolute',
          left: '0px',
          bottom: '100%',
          marginBottom: '4px',
          border: '1px solid silver',
          borderRadius: '0.4rem',
          color: 'black',
          fontSize: '0.8rem',
          fontWeight: 300,
          lineHeight: '1.0rem',
          padding: '0.25rem 0.4rem',
          textAlign: 'left',
          width: '12rem',
          backgroundColor: '#8cd2e7',
          boxShadow: '0 2px 8px rgba(0,0,0,0.15)',
          zIndex: 50,
          pointerEvents: 'none',
          whiteSpace: 'normal'
        }}>
          {tooltipText}
        </div>
      )}
    </div>
  );
};

export const fbOutpatientAppointmentTile: React.FC<OutpatientAppointmentTileProps> = ({
  dateTime,
  clinicName,
  speciality,
  src
}) => {
  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        gap: '0px',
        fontFamily: "'Roboto', sans-serif",
        color: 'black',
        fontSize: '1rem',
        fontWeight: 300,
        lineHeight: '1.15',
        textAlign: 'left'
      }}
    >
      <HoverTooltipField tooltipText="Appointment Date & Time">
        <div style={{ fontWeight: 300 }}>
          {dateTime}
        </div>
      </HoverTooltipField>
      <div style={{ fontWeight: 500 }}>
        Outpatient appointment
      </div>
      {clinicName && (
        <HoverTooltipField tooltipText="Clinic Name">
          <div style={{ fontWeight: 300 }}>
            {clinicName}
          </div>
        </HoverTooltipField>
      )}
      {speciality && (
        <HoverTooltipField tooltipText="Speciality">
          <div style={{ fontWeight: 300 }}>
            {speciality}
          </div>
        </HoverTooltipField>
      )}
      {src && (
        <HoverTooltipField tooltipText="Senior Responsible Clinician">
          <div style={{ fontWeight: 300 }}>
            {src}
          </div>
        </HoverTooltipField>
      )}
    </div>
  );
};
