// src/lib/components/fb/fbQuestion.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { getContext, setContext } from 'svelte';
  import { fbQuestionRequiredMarkerContextKey, fbSubfieldContextKey } from './context';
  import FbRequiredForAudit from './fbRequiredForAudit.svelte';
  import FbValueError from './fbValueError.svelte';

  let {
    label,
    required = false,
    requiredForAudit = false,
    children,
    class: className = '',
    subfield = false,
    valueError = ''
  }: {
    label: string;
    required?: boolean;
    requiredForAudit?: boolean;
    children: Snippet;
    class?: string;
    subfield?: boolean;
    valueError?: string;
  } = $props();

  setContext(fbQuestionRequiredMarkerContextKey, {
    get value() {
      return required || requiredForAudit;
    }
  });

  const inheritedSubfield = getContext<{ value: boolean } | undefined>(fbSubfieldContextKey);
  const labelIsSubfield = $derived(subfield || !!inheritedSubfield?.value);

  const firstPart = $derived.by(() => {
    if (!required && !requiredForAudit) return label;
    const trimmed = label.trim();
    const lastSpaceIndex = trimmed.lastIndexOf(' ');
    return lastSpaceIndex === -1 ? '' : trimmed.substring(0, lastSpaceIndex + 1);
  });

  const lastWord = $derived.by(() => {
    if (!required && !requiredForAudit) return '';
    const trimmed = label.trim();
    const lastSpaceIndex = trimmed.lastIndexOf(' ');
    return lastSpaceIndex === -1 ? trimmed : trimmed.substring(lastSpaceIndex + 1);
  });
</script>

<div class={`fb-question-container ${className}`.trim()}>
  <FbValueError message={valueError} />
  <label class:subfield={labelIsSubfield}>
    {#if required || requiredForAudit}
      {firstPart}
      <span class="fb-question-label-last-word">
        {lastWord}
        {#if requiredForAudit}<FbRequiredForAudit />{/if}
        {#if required}<span class="fb-required-marker">*</span>{/if}
      </span>
    {:else}
      {label}
    {/if}
  </label>
  <div class="fb-question-child">
    {@render children()}
  </div>
</div>

<style>
  .fb-question-container {
    display: flex;
    flex-direction: column;
    gap: 0.2rem;
    padding: 0.2rem;
    border-radius: 0.4rem;
    box-sizing: border-box;
    transition: background-color 0.1s ease-out;
  }

  label {
    font-family: 'Roboto', sans-serif;
    font-size: 1rem;
    font-weight: 500;
    color: black;
    margin: 0;
    display: block;
    flex-shrink: 0;
  }

  label.subfield {
    font-weight: 300;
    font-size: 1rem;
  }

  .fb-question-label-last-word {
    display: inline-block;
    white-space: nowrap;
  }

  .fb-required-marker {
    color: #d50000;
    margin-left: 0.1rem;
  }

  .fb-question-child {
    width: 100%;
  }
</style>

// src/components/fbQuestion.tsx
import React from 'react';
import { fbRequiredForAudit as FbRequiredForAudit } from './fbRequiredForAudit';
import { fbValueError as FbValueError } from './fbValueError';

export const fbQuestionRequiredMarkerContext = React.createContext(false);

interface fbQuestionProps {
  label: string;
  required?: boolean;
  requiredForAudit?: boolean;
  children: React.ReactNode;
  style?: React.CSSProperties;
  className?: string;
  labelStyle?: React.CSSProperties;
  valueError?: string;
}

export const fbQuestion: React.FC<fbQuestionProps> = ({
  label,
  required = false,
  requiredForAudit = false,
  children,
  style,
  className = '',
  labelStyle,
  valueError,
}) => {
  const renderRequiredMarkers = () => (
    <>
      {requiredForAudit && <FbRequiredForAudit />}
      {required && <span style={{ color: '#d50000', marginLeft: '0.1rem' }}>*</span>}
    </>
  );

  // Gracefully parses the label string to group the last word and required markers
  const renderLabelText = () => {
    if (!required && !requiredForAudit) return label;

    const trimmed = label.trim();
    const lastSpaceIndex = trimmed.lastIndexOf(' ');

    if (lastSpaceIndex === -1) {
      // Single word label
      return (
        <span style={{ display: 'inline-block', whiteSpace: 'nowrap' }}>
          {trimmed}
          {renderRequiredMarkers()}
        </span>
      );
    }

    const firstPart = trimmed.substring(0, lastSpaceIndex + 1);
    const lastWord = trimmed.substring(lastSpaceIndex + 1);

    return (
      <>
        {firstPart}
        <span style={{ display: 'inline-block', whiteSpace: 'nowrap' }}>
          {lastWord}
          {renderRequiredMarkers()}
        </span>
      </>
    );
  };

  return (
    <div
      className={`fb-question-container ${className}`}
      style={{
        display: 'flex',
        flexDirection: 'column',
        gap: '0.2rem',
        padding: '0.2rem',
        borderRadius: '0.4rem',
        boxSizing: 'border-box',
        transition: 'background-color 0.1s ease-out',
        ...style
      }}
    >
      <FbValueError message={valueError} />
      <label
        style={{
          fontFamily: "'Roboto', sans-serif",
          fontSize: '1rem',
          fontWeight: 500,
          color: 'black',
          margin: 0,
          display: 'block',
          ...labelStyle
        }}
      >
        {renderLabelText()}
      </label>
      <fbQuestionRequiredMarkerContext.Provider value={required || requiredForAudit}>
        <div style={{ width: '100%' }}>
          {children}
        </div>
      </fbQuestionRequiredMarkerContext.Provider>
    </div>
  );
};
