// src/lib/components/fb/fbSCTSelector.svelte
<script lang="ts">
  import { onDestroy, untrack } from 'svelte';
  import FbQuestion from './fbQuestion.svelte';
  import { parseServerResponse } from '$lib/utils/shadesOfPaleParser';

  type SearchCommand = 'findProcedure' | 'findDisorder';
  type SelectorMode = 'procedure' | 'diagnosis';

  let {
    id = '',
    name = '',
    label = '',
    value = $bindable(''),
    required = false,
    requiredForAudit = false,
    coded,
    valueError = '',
    subfield = false,
    placeholder = 'Type to search SNOMED CT',
    searchCommand,
    mode,
    inputClassName = '',
    readonly = false,
    onChange,
    change
  }: {
    id?: string;
    name?: string;
    label?: string;
    value?: string;
    required?: boolean;
    requiredForAudit?: boolean;
    coded?: boolean;
    valueError?: string;
    subfield?: boolean;
    placeholder?: string;
    searchCommand: SearchCommand;
    mode: SelectorMode;
    inputClassName?: string;
    readonly?: boolean;
    onChange?: (value: string, coded: boolean) => void;
    change?: (value: string, coded: boolean) => void;
  } = $props();

  type ParsedSct = {
    orderedMatches?: unknown[];
    parents?: Array<{ pt?: string }>;
    children?: Array<{ pt?: string }>;
    synonyms?: string[];
    pt?: string;
    fst?: string;
    id?: string;
  };

  let searchText = $state(value || '');
  let localCoded = $state(Boolean(value));
  let isOpen = $state(false);
  let isSearching = $state(false);
  let error = $state('');
  let results = $state<string[]>([]);
  let fullData = $state<ParsedSct | null>(null);
  let highlightedIndex = $state(-1);
  let searchHistory = $state<string[]>([]);
  let historyIndex = $state(-1);
  let selectorElement = $state<HTMLDivElement | undefined>();
  let popupTop = $state(0);
  let popupLeft = $state(0);
  let popupMaxHeight = $state(300);
  let searchTimer: number | undefined = undefined;
  let blurTimer: number | undefined = undefined;
  let scrollParents: Array<Window | HTMLElement> = [];
  let popupListenersAttached = false;

  const effectiveCoded = $derived(coded !== undefined ? coded : localCoded);
  const selectableConcept = $derived(fullData?.pt || fullData?.fst || searchText);
  const inputId = $derived(id || `${name || mode}-sct-input`);
  const popupId = $derived(`${inputId}-results`);
  const activeOptionId = $derived(isOpen && highlightedIndex >= 0 ? `${popupId}-option-${highlightedIndex}` : undefined);

  $effect(() => {
    if (value !== searchText && !isOpen) {
      searchText = value || '';
      localCoded = Boolean(value);
    }
  });

  function updatePopupPosition() {
    if (!selectorElement) return;
    const rect = selectorElement.getBoundingClientRect();
    const preferredHeight = 300;
    const spaceBelow = window.innerHeight - rect.bottom - 20;
    const spaceAbove = rect.top - 20;
    const nextMaxHeight = Math.min(preferredHeight, Math.max(100, spaceBelow >= spaceAbove ? spaceBelow : spaceAbove));
    popupMaxHeight = nextMaxHeight;
    popupTop = spaceBelow >= preferredHeight || spaceBelow >= spaceAbove ? rect.bottom + 2 : rect.top - nextMaxHeight - 2;
    const width = Math.min(45 * 16, window.innerWidth - 40);
    const nextLeft = Math.min(rect.left, window.innerWidth - width - 20);
    popupLeft = nextLeft < 20 ? 20 : nextLeft;
  }

  function collectScrollParents(element: HTMLElement) {
    const parents: Array<Window | HTMLElement> = [window];
    let current = element.parentElement;
    while (current) {
      const style = window.getComputedStyle(current);
      if (/(auto|scroll|overlay)/.test(`${style.overflow}${style.overflowY}${style.overflowX}`)) parents.push(current);
      current = current.parentElement;
    }
    return parents;
  }

  function attachPopupListeners() {
    if (popupListenersAttached || !selectorElement) return;
    scrollParents = collectScrollParents(selectorElement);
    for (const parent of scrollParents) parent.addEventListener('scroll', updatePopupPosition, { passive: true });
    window.addEventListener('resize', updatePopupPosition);
    popupListenersAttached = true;
  }

  function detachPopupListeners() {
    if (!popupListenersAttached) return;
    for (const parent of scrollParents) parent.removeEventListener('scroll', updatePopupPosition);
    window.removeEventListener('resize', updatePopupPosition);
    scrollParents = [];
    popupListenersAttached = false;
  }

  $effect(() => {
    if (isOpen) {
      untrack(() => {
        updatePopupPosition();
        attachPopupListeners();
      });
    } else {
      detachPopupListeners();
    }
  });

  onDestroy(() => {
    window.clearTimeout(searchTimer);
    window.clearTimeout(blurTimer);
    detachPopupListeners();
  });

  function emit(nextValue: string, nextCoded: boolean) {
    onChange?.(nextValue, nextCoded);
    change?.(nextValue, nextCoded);
  }

  function matchText(item: unknown) {
    if (typeof item === 'string') return item;
    const record = item as { pt?: string; term?: string; display?: string };
    return record?.pt || record?.term || record?.display || '';
  }

  async function searchSct(term: string, addToHistory = true) {
    if (readonly) return;
    const trimmed = term.trim();
    if (trimmed.length < 1) {
      results = [];
      fullData = null;
      isOpen = false;
      return;
    }

    try {
      isSearching = true;
      isOpen = true;
      error = '';
      const url = `https://www.shadesofpale.net/SCTSearch?cmd=${searchCommand}&st=${encodeURIComponent(trimmed)}&count=30`;
      const response = await fetch(url);
      const text = await response.text();
      const parsed = parseServerResponse(text) as ParsedSct;
      const matches = parsed?.orderedMatches || [];
      results = Array.isArray(matches) ? matches.map(matchText).filter(Boolean) : [];
      fullData = parsed;
      highlightedIndex = -1;
      updatePopupPosition();
      if (addToHistory) {
        const nextHistory = searchHistory.slice(0, historyIndex + 1);
        if (nextHistory[nextHistory.length - 1] !== trimmed) {
          searchHistory = [...nextHistory, trimmed];
          historyIndex = searchHistory.length - 1;
        }
      }
    } catch (err) {
      error = err instanceof Error ? err.message : String(err);
      results = [];
      fullData = null;
    } finally {
      isSearching = false;
    }
  }

  function queueSearch(nextText: string) {
    if (readonly) return;
    searchText = nextText;
    localCoded = false;
    isOpen = nextText.trim().length > 0;
    emit(nextText, false);
    window.clearTimeout(searchTimer);
    searchTimer = window.setTimeout(() => searchSct(nextText), 250);
  }

  function selectValue(nextValue: string) {
    if (readonly) return;
    searchText = nextValue;
    localCoded = true;
    isOpen = false;
    emit(nextValue, true);
  }

  function handleMatchClick(conceptName: string) {
    if (readonly) return;
    searchText = conceptName;
    localCoded = false;
    emit(searchText, false);
    searchSct(conceptName);
  }

  function handleBack() {
    if (readonly) return;
    if (historyIndex <= 0) return;
    historyIndex -= 1;
    searchText = searchHistory[historyIndex];
    searchSct(searchText, false);
  }

  function handleNext() {
    if (readonly) return;
    if (historyIndex >= searchHistory.length - 1) return;
    historyIndex += 1;
    searchText = searchHistory[historyIndex];
    searchSct(searchText, false);
  }

  function clearValue() {
    if (readonly) return;
    searchText = '';
    localCoded = false;
    results = [];
    fullData = null;
    highlightedIndex = -1;
    emit('', false);
  }

  function toggleOpen() {
    if (readonly) return;
    isOpen = !isOpen;
    if (isOpen) {
      updatePopupPosition();
      searchSct(searchText);
    }
  }

  function closeAfterBlur() {
    window.clearTimeout(blurTimer);
    blurTimer = window.setTimeout(() => isOpen = false, 200);
  }

  function handleKeydown(event: KeyboardEvent) {
    if (readonly) return;
    if (event.key === 'Escape') {
      event.preventDefault();
      isOpen = false;
      highlightedIndex = -1;
      return;
    }

    if (event.key === 'ArrowDown') {
      event.preventDefault();
      if (!isOpen) {
        isOpen = true;
        updatePopupPosition();
        if (searchText.trim()) searchSct(searchText);
      }
      highlightedIndex = results.length ? Math.min(highlightedIndex + 1, results.length - 1) : -1;
    } else if (event.key === 'ArrowUp') {
      event.preventDefault();
      if (!isOpen) {
        isOpen = true;
        updatePopupPosition();
      }
      highlightedIndex = results.length ? Math.max(highlightedIndex - 1, 0) : -1;
    } else if (event.key === 'Enter' && isOpen && highlightedIndex >= 0 && results[highlightedIndex]) {
      event.preventDefault();
      selectValue(results[highlightedIndex]);
    }
  }
</script>

{#snippet selectorControl()}
  <div class="fb-selector" bind:this={selectorElement}>
    <div class="fb-selector-input-wrap">
      <input
        id={inputId}
        {name}
        class={inputClassName}
        bind:value={searchText}
        {placeholder}
        autocomplete="off"
        {readonly}
        onfocus={() => { if (!readonly) { window.clearTimeout(blurTimer); isOpen = true; } }}
        oninput={(event) => queueSearch(event.currentTarget.value)}
        onkeydown={handleKeydown}
        onblur={closeAfterBlur}
        role="combobox"
        aria-autocomplete="list"
        aria-expanded={isOpen && !readonly}
        aria-controls={popupId}
        aria-activedescendant={activeOptionId}
        data-lily-reference-component="combobox"
      />
      <div class="fb-selector-actions">
        {#if searchText && !readonly}
          <button type="button" class="fb-selector-button fb-clear" aria-label="Clear" onmousedown={(event) => event.preventDefault()} onclick={clearValue}>{'\u2715'}</button>
        {/if}
        {#if !readonly}
          <button type="button" class="fb-selector-button fb-arrow" aria-label="Search" onmousedown={(event) => event.preventDefault()} onclick={toggleOpen}>{isOpen ? '\u25b2' : '\u25bc'}</button>
        {/if}
      </div>
    </div>
    {#if searchText}
      <span class="material-icons fb-coded-icon" class:coded={effectiveCoded} aria-hidden="true">{effectiveCoded ? 'check_circle_outline' : 'warning'}</span>
    {/if}
    {#if isOpen && !readonly}
      <div id={popupId} class="fb-selector-popup" style={`top: ${popupTop}px; left: ${popupLeft}px; max-height: ${popupMaxHeight}px;`}>
        {#if isSearching && results.length === 0}
          <div class="fb-selector-empty">Searching...</div>
        {:else if error}
          <div class="fb-selector-empty">Search unavailable</div>
        {:else if results.length === 0}
          <div class="fb-selector-empty">No matches</div>
        {:else}
          <div class="fb-selector-results">
            <div class="fb-selector-left" role="listbox">
              {#each results as result, index}
                <button
                  type="button"
                  class:highlighted={highlightedIndex === index}
                  class="fb-selector-result"
                  id={`${popupId}-option-${index}`}
                  role="option"
                  aria-selected={highlightedIndex === index}
                  onmouseenter={() => highlightedIndex = index}
                  onmousedown={(event) => event.preventDefault()}
                  onclick={() => mode === 'procedure' ? selectValue(result) : handleMatchClick(result)}
                >
                  {result}
                </button>
              {/each}
            </div>
            <div class="fb-selector-detail">
              {#if fullData?.parents?.length}
                <div class="fb-detail-block">
                  <div class="fb-detail-heading">Parent concepts</div>
                  <div class="fb-detail-links">
                    {#each fullData.parents as parent, index}
                      {#if index > 0}<span> | </span>{/if}
                      <button type="button" class="fb-detail-link fb-sct-popup-hoverable" onmousedown={(event) => event.preventDefault()} onclick={() => parent.pt && handleMatchClick(parent.pt)}>{parent.pt}</button>
                    {/each}
                  </div>
                </div>
              {/if}
              {#if fullData?.fst}
                <div class="fb-detail-block">
                  <div class="fb-detail-heading">Concept</div>
                  <div class="fb-detail-concept">{fullData.fst}</div>
                </div>
              {/if}
              <div class="fb-detail-actions">
                <button type="button" disabled={historyIndex <= 0} onmousedown={(event) => event.preventDefault()} onclick={handleBack}>&lt;</button>
                <button type="button" disabled={historyIndex >= searchHistory.length - 1} onmousedown={(event) => event.preventDefault()} onclick={handleNext}>&gt;</button>
                <button type="button" class="select" onmousedown={(event) => event.preventDefault()} onclick={() => selectValue(selectableConcept)}>Select</button>
                <button type="button" class="close" onmousedown={(event) => event.preventDefault()} onclick={() => isOpen = false}>Close</button>
              </div>
              <div class="fb-detail-scroll">
                {#if fullData?.synonyms?.length}
                  <div class="fb-detail-block">
                    <div class="fb-detail-heading">Synonyms</div>
                    <div>
                      {#each fullData.synonyms as synonym, index}
                        {#if index > 0}<span> | </span>{/if}
                        <span class="fb-sct-popup-hoverable">{synonym}</span>
                      {/each}
                    </div>
                  </div>
                {/if}
                {#if fullData?.children?.length}
                  <div class="fb-detail-block">
                    <div class="fb-detail-heading">Child concepts</div>
                    {#each fullData.children as child}
                      <div><button type="button" class="fb-detail-link fb-sct-popup-hoverable" onmousedown={(event) => event.preventDefault()} onclick={() => child.pt && handleMatchClick(child.pt)}>{child.pt}</button></div>
                    {/each}
                  </div>
                {/if}
              </div>
            </div>
          </div>
        {/if}
      </div>
    {/if}
  </div>
{/snippet}

{#if label}
  <FbQuestion {label} {required} {requiredForAudit} {valueError} {subfield}>
    {@render selectorControl()}
  </FbQuestion>
{:else}
  {@render selectorControl()}
{/if}

<style>
  .fb-selector {
    position: relative;
    display: flex;
    gap: 0.3rem;
    align-items: center;
    width: 100%;
  }

  .fb-selector-input-wrap {
    position: relative;
    flex: 1;
    min-width: 0;
  }

  input {
    width: 100%;
    height: 2rem;
    min-width: 0;
    border: 0.1rem solid silver;
    border-radius: 0.4rem;
    padding: 0.2rem 2.5rem 0.2rem 0.4rem;
    font-size: 1rem;
    font-weight: 400;
    box-sizing: border-box;
    background: white;
  }

  input::placeholder {
    color: #777;
    font-weight: 400;
    opacity: 1;
  }

  .fb-selector-actions {
    position: absolute;
    right: 0.2rem;
    top: 50%;
    transform: translateY(-50%);
    display: flex;
    gap: 0.1rem;
    align-items: center;
  }

  .fb-selector-button {
    border: none;
    background: none;
    color: #666;
    cursor: pointer;
    line-height: 1;
    padding: 0.1rem;
  }

  .fb-clear {
    font-size: 0.9rem;
  }

  .fb-arrow {
    font-size: 1rem;
  }

  .fb-coded-icon {
    color: #fd8a10;
    font-size: 1.2rem;
  }

  .fb-coded-icon.coded {
    color: #008000;
  }

  .fb-selector-popup {
    position: fixed;
    z-index: 10000;
    width: 45rem;
    max-width: 100vw;
    overflow: hidden;
    border: 0.1rem solid silver;
    border-radius: 0.4rem;
    background: white;
    box-shadow: 0 0.2rem 0.5rem rgb(0 0 0 / 20%);
  }

  .fb-selector-empty {
    padding: 0.5rem;
    color: #666;
  }

  .fb-selector-results {
    display: flex;
    width: 100%;
    max-height: 19rem;
  }

  .fb-selector-left {
    width: 33.333%;
    border-right: 0.1rem solid silver;
    overflow: auto;
  }

  .fb-selector-detail {
    width: 66.667%;
    padding: 0.25rem;
    overflow: hidden;
    font-size: 0.9rem;
    line-height: 1.2;
    display: flex;
    flex-direction: column;
    box-sizing: border-box;
  }

  .fb-selector-result,
  .fb-selector-empty {
    display: block;
    width: 100%;
    padding: 0.2rem 0.5rem;
    border: none;
    border-bottom: 0.1rem solid #eee;
    background: white;
    color: #111;
    text-align: left;
    font-size: 0.9rem;
    line-height: 1.2;
    white-space: nowrap;
    font-family: 'Roboto', sans-serif;
  }

  .fb-selector-result {
    cursor: pointer;
  }

  .fb-selector-result:hover,
  .fb-selector-result.highlighted {
    background: #ffffcc;
  }

  .fb-detail-block {
    margin-bottom: 0.25rem;
  }

  .fb-detail-heading {
    background: #8cd2e7;
    color: black;
    font-size: 0.6rem;
    padding: 0.2rem 0.5rem;
  }

  .fb-detail-concept {
    font-size: 1.5rem;
    margin: 0.25rem 0;
    font-weight: 500;
  }

  .fb-detail-link {
    border: none;
    background: none;
    color: #1b6ec2;
    padding: 0;
    cursor: pointer;
    text-align: left;
    text-decoration: underline;
    font: inherit;
  }

  .fb-sct-popup-hoverable {
    display: inline-block;
    padding: 0.1rem 0.3rem;
    margin: 0.1rem;
    border-radius: 0.2rem;
  }

  .fb-sct-popup-hoverable:hover,
  .fb-sct-popup-hoverable:focus,
  .fb-sct-popup-hoverable:focus-visible {
    background-color: #ffffcc;
    outline: none;
  }

  .fb-detail-actions {
    display: flex;
    gap: 0.3rem;
    margin: 0.25rem 0;
  }

  .fb-detail-actions button {
    border: none;
    border-radius: 0.25rem;
    background: #1b6ec2;
    color: white;
    cursor: pointer;
    font-weight: 500;
    padding: 0.2rem 0.5rem;
  }

  .fb-detail-actions button:disabled {
    background: silver;
    cursor: not-allowed;
  }

  .fb-detail-actions button.select {
    background: #008000;
  }

  .fb-detail-actions button.close {
    background: #d50000;
    color: white;
  }

  .fb-detail-scroll {
    flex: 1;
    overflow-y: auto;
    overflow-x: hidden;
  }
</style>

// src/components/fbSCTSelector.tsx
import * as React from 'react';
import { parseServerResponse } from '../utils/shadesOfPaleParser';
import { fbQuestion as FbQuestion } from './fbQuestion';
import { fbValueError as FbValueError } from './fbValueError';

type SCTSearchCommand = 'findDisorder' | 'findProcedure';
type SCTSelectorMode = 'diagnosis' | 'procedure';

interface fbSCTSelectorProps {
  label?: string;
  name: string;
  value: string;
  onChange: (value: string, coded: boolean) => void;
  onFocus?: (e: React.FocusEvent<HTMLInputElement>) => void;
  onBlur?: () => void;
  placeholder?: string;
  required?: boolean;
  coded?: boolean;
  valueError?: string;
  labelStyle?: React.CSSProperties;
  searchCommand: SCTSearchCommand;
  mode: SCTSelectorMode;
  inputClassName?: string;
}

export const fbSCTSelector: React.FC<fbSCTSelectorProps> = ({
  label,
  name,
  value,
  onChange,
  onFocus,
  onBlur,
  placeholder = 'Type to search SNOMED CT',
  required,
  coded,
  valueError,
  labelStyle,
  searchCommand,
  mode,
  inputClassName = '',
}) => {
  const [searchTerm, setSearchTerm] = React.useState<string>(value);
  const [results, setResults] = React.useState<string[]>([]);
  const [fullData, setFullData] = React.useState<any>(null);
  const [showDropdown, setShowDropdown] = React.useState<boolean>(false);
  const [isLoading, setIsLoading] = React.useState<boolean>(false);
  const [highlightedIndex, setHighlightedIndex] = React.useState<number>(-1);
  const [dropdownLeft, setDropdownLeft] = React.useState<number>(0);
  const [dropdownTop, setDropdownTop] = React.useState<number>(0);
  const [dropdownMaxHeight, setDropdownMaxHeight] = React.useState<number>(300);
  const [justSelected, setJustSelected] = React.useState<boolean>(false);
  const [searchHistory, setSearchHistory] = React.useState<string[]>([]);
  const [historyIndex, setHistoryIndex] = React.useState<number>(-1);
  const [hasSelected, setHasSelected] = React.useState<boolean>(false);
  const [lastSelectedValue, setLastSelectedValue] = React.useState<string>(value);
  const [selectedId, setSelectedId] = React.useState<string>('');
  const [hasInteracted, setHasInteracted] = React.useState<boolean>(false);
  const inputRef = React.useRef<HTMLInputElement>(null);
  const dropdownRef = React.useRef<HTMLDivElement>(null);
  const containerRef = React.useRef<HTMLDivElement>(null);
  const isInitialMount = React.useRef<boolean>(true);
  const skipHistoryRef = React.useRef<boolean>(false);

  React.useEffect(() => {
    if (value !== searchTerm) {
      setSearchTerm(value);
      if (mode === 'procedure') {
        setLastSelectedValue(value);
      }
    }
  }, [value]);

  const performSearch = (term?: string, addToHistory: boolean = true) => {
    const searchValue = term !== undefined ? term : searchTerm;

    if (searchValue.length > 0) {
      setIsLoading(true);

      if (term !== undefined) {
        setSearchTerm(term);
      }

      if (addToHistory) {
        const newHistory = searchHistory.slice(0, historyIndex + 1);
        if (mode === 'procedure') {
          if (newHistory[newHistory.length - 1] !== searchValue) {
            newHistory.push(searchValue);
            setSearchHistory(newHistory);
            setHistoryIndex(newHistory.length - 1);
          }
        } else {
          newHistory.push(searchValue);
          setSearchHistory(newHistory);
          setHistoryIndex(newHistory.length - 1);
        }
      }

      fetch(`https://www.shadesofpale.net/SCTSearch?cmd=${searchCommand}&st=${encodeURIComponent(searchValue)}&count=30`, {
        method: 'GET'
      })
        .then(response => response.text())
        .then(text => {
          try {
            const data = parseServerResponse(text);
            const matches = data.orderedMatches || [];
            setResults(matches);
            setFullData(data);
            if (hasInteracted) {
              setShowDropdown(matches.length > 0);
            }
            setHighlightedIndex(-1);
          } catch (e) {
            console.error('Failed to parse SCTSearch response:', e);
            setResults([]);
            setFullData(null);
          }
          setIsLoading(false);
        })
        .catch(error => {
          console.error('SCTSearch error:', error);
          setResults([]);
          setFullData(null);
          setIsLoading(false);
        });
    } else {
      setResults([]);
      setFullData(null);
      setShowDropdown(false);
      setHighlightedIndex(-1);
    }
  };

  React.useEffect(() => {
    if (isInitialMount.current) {
      isInitialMount.current = false;
      return;
    }
    if (!justSelected) {
      const addToHistory = mode === 'procedure' ? !skipHistoryRef.current : true;
      skipHistoryRef.current = false;
      performSearch(undefined, addToHistory);
    }
  }, [searchTerm]);

  const updateDropdownPosition = React.useCallback(() => {
    if (containerRef.current) {
      const dropdownWidthPx = 45 * 16;
      const maxDropdownWidth = Math.min(dropdownWidthPx, window.innerWidth - 40);
      const containerRect = containerRef.current.getBoundingClientRect();

      const spaceBelow = window.innerHeight - containerRect.bottom - 20;
      const spaceAbove = containerRect.top - 20;
      const preferredHeight = 300;

      let topPos: number;
      let maxHeight: number;

      if (spaceBelow >= preferredHeight || spaceBelow >= spaceAbove) {
        topPos = containerRect.bottom + 2;
        maxHeight = Math.min(preferredHeight, Math.max(100, spaceBelow));
      } else {
        maxHeight = Math.min(preferredHeight, Math.max(100, spaceAbove));
        topPos = containerRect.top - maxHeight - 2;
      }

      setDropdownTop(topPos);
      setDropdownMaxHeight(maxHeight);

      const dropdownRight = containerRect.left + maxDropdownWidth;

      if (dropdownRight > window.innerWidth) {
        const shift = dropdownRight - window.innerWidth + 20;
        setDropdownLeft(containerRect.left - shift);
      } else {
        setDropdownLeft(containerRect.left);
      }
    }
  }, []);

  React.useEffect(() => {
    if (showDropdown && results.length > 0) {
      setHighlightedIndex(-1);
      updateDropdownPosition();

      const scrollContainer = document.querySelector('.flex-1.overflow-y-auto');
      if (scrollContainer) {
        scrollContainer.addEventListener('scroll', updateDropdownPosition);
        return () => {
          scrollContainer.removeEventListener('scroll', updateDropdownPosition);
        };
      }
    } else if (!showDropdown) {
      setHighlightedIndex(-1);
    }
  }, [showDropdown, results, updateDropdownPosition]);

  const handleSelect = (conceptName: string) => {
    setJustSelected(true);
    setSearchTerm(conceptName);
    onChange(conceptName, true);
    setShowDropdown(false);
    setHighlightedIndex(-1);
    setHasSelected(true);
    setLastSelectedValue(conceptName);
    setSelectedId(fullData?.id || '');
    setTimeout(() => setJustSelected(false), 100);
  };

  const handleMatchClick = (conceptName: string) => {
    if (mode === 'procedure') {
      setSearchTerm(conceptName);
    } else {
      performSearch(conceptName, true);
      setHasSelected(false);
    }
    setSelectedId('');
  };

  const handleBack = () => {
    if (historyIndex > 0) {
      const newIndex = historyIndex - 1;
      setHistoryIndex(newIndex);
      if (mode === 'procedure') {
        skipHistoryRef.current = true;
        setSearchTerm(searchHistory[newIndex]);
      } else {
        performSearch(searchHistory[newIndex], false);
        setHasSelected(false);
      }
      setSelectedId('');
    }
  };

  const handleNext = () => {
    if (historyIndex < searchHistory.length - 1) {
      const newIndex = historyIndex + 1;
      setHistoryIndex(newIndex);
      if (mode === 'procedure') {
        skipHistoryRef.current = true;
        setSearchTerm(searchHistory[newIndex]);
      } else {
        performSearch(searchHistory[newIndex], false);
        setHasSelected(false);
      }
      setSelectedId('');
    }
  };

  const handleConceptClick = (conceptText: string) => {
    if (mode === 'procedure') {
      setSearchTerm(conceptText);
    } else {
      performSearch(conceptText, true);
      setHasSelected(false);
    }
    setSelectedId('');
  };

  const handleClose = () => {
    setShowDropdown(false);
    setHighlightedIndex(-1);
  };

  const handleClear = () => {
    setSearchTerm('');
    onChange('', false);
    setShowDropdown(false);
    setResults([]);
    setHighlightedIndex(-1);
    setHasSelected(false);
    setLastSelectedValue('');
    setSelectedId('');
    if (inputRef.current) {
      inputRef.current.focus();
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Escape') {
      e.preventDefault();
      setShowDropdown(false);
      setHighlightedIndex(-1);
      return;
    }

    if (!showDropdown || results.length === 0) return;

    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setHighlightedIndex(prev => {
        if (prev === -1) return 0;
        return Math.min(prev + 1, results.length - 1);
      });
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setHighlightedIndex(prev => {
        return Math.max(prev - 1, -1);
      });
    } else if (e.key === 'Enter' && highlightedIndex >= 0) {
      e.preventDefault();
      handleSelect(results[highlightedIndex]);
    }
  };

  const isCoded = coded !== undefined
    ? coded
    : mode === 'procedure'
      ? searchTerm === lastSelectedValue
      : hasSelected;

  const renderContent = () => (
    <div style={{display: 'flex', alignItems: 'center', width: '100%', gap: '0.3rem'}}>
      <div ref={containerRef} style={{position: 'relative', flex: 1}}>
        <div style={{position: 'relative', display: 'flex', alignItems: 'center'}}>
          <input
            ref={inputRef}
            type="text"
            name={name}
            value={searchTerm}
            onChange={(e) => {
              setHasInteracted(true);
              setSearchTerm(e.target.value);
              onChange(e.target.value, false);
              setHasSelected(false);
              setSelectedId('');
            }}
            onFocus={(e) => {
              setHasInteracted(true);
              if (results.length > 0 && !justSelected) setShowDropdown(true);
              if (onFocus) onFocus(e);
            }}
            onBlur={() => {
              setTimeout(() => {
                setShowDropdown(false);
                if (onBlur) onBlur();
              }, 200);
            }}
            onKeyDown={handleKeyDown}
            className={`w-full p-2 fb-hide-border-in-rov ${inputClassName}`}
            style={{
              border: '0.1rem solid silver',
              borderRadius: '0.4rem',
              paddingRight: '2.5rem',
              height: '2rem',
              boxSizing: 'border-box',
              backgroundColor: 'white'
            }}
            placeholder={placeholder}
            required={required}
            autoComplete="off"
          />
          <div style={{
            position: 'absolute',
            right: '0.2rem',
            display: 'flex',
            gap: '0.1rem',
            alignItems: 'center'
          }}>
            {searchTerm && (
              <button
                type="button"
                onClick={handleClear}
                onMouseDown={(e) => e.preventDefault()}
                style={{
                  border: 'none',
                  background: 'none',
                  cursor: 'pointer',
                  color: '#666',
                  fontSize: '0.9rem',
                  padding: '0.1rem',
                  lineHeight: 1
                }}
              >
                ✕
              </button>
            )}
            <button
              type="button"
              onClick={() => {
                setHasInteracted(true);
                if (showDropdown) {
                  setShowDropdown(false);
                  setHighlightedIndex(-1);
                } else {
                  setHighlightedIndex(-1);
                  if (results.length > 0) {
                    setShowDropdown(true);
                  } else {
                    performSearch(undefined, true);
                  }
                }
              }}
              onMouseDown={(e) => e.preventDefault()}
              style={{
                border: 'none',
                background: 'none',
                cursor: 'pointer',
                color: '#666',
                fontSize: '1rem',
                padding: '0.1rem',
                lineHeight: 1
              }}
            >
              {showDropdown ? '▲' : '▼'}
            </button>
          </div>
        </div>
        {showDropdown && results.length > 0 && fullData && (
          <div
            ref={dropdownRef}
            style={{
              position: 'fixed',
              top: `${dropdownTop}px`,
              left: `${dropdownLeft}px`,
              width: '45rem',
              maxWidth: '100vw',
              maxHeight: `${dropdownMaxHeight}px`,
              backgroundColor: 'white',
              border: '0.1rem solid silver',
              borderRadius: '0.4rem',
              zIndex: 10000,
              boxShadow: '0 2px 8px rgba(0,0,0,0.15)',
              display: 'flex'
            }}
          >
            <div style={{
              width: '33.333%',
              borderRight: '0.1rem solid silver',
              overflowY: 'auto',
              overflowX: 'auto'
            }}>
              {results.map((conceptName, index) => (
                <div
                  key={index}
                  onMouseDown={(e) => {
                    e.preventDefault();
                    handleMatchClick(conceptName);
                  }}
                  onMouseEnter={() => setHighlightedIndex(index)}
                  style={{
                    padding: '0.2rem 0.5rem',
                    cursor: 'pointer',
                    fontSize: '0.9rem',
                    whiteSpace: 'nowrap',
                    backgroundColor: highlightedIndex === index ? '#ffffcc' : 'white',
                    transition: 'background-color 0.2s',
                    lineHeight: '1.2'
                  }}
                >
                  {conceptName}
                </div>
              ))}
            </div>

            <div style={{
              width: '66.666%',
              padding: '0.25rem',
              overflowY: 'hidden',
              fontSize: '0.9rem',
              lineHeight: 1.2,
              display: 'flex',
              flexDirection: 'column'
            }}>
              {fullData.parents && Array.isArray(fullData.parents) && fullData.parents.length > 0 && (
                <div style={{marginBottom: '0.25rem'}}>
                  <div style={{backgroundColor: '#8cd2e7', color: 'black', fontSize: '0.6rem', width: '100%', padding: '0.2rem 0.5rem'}}>
                    Parent concepts
                  </div>
                  <div style={{marginTop: '0.3rem'}}>
                    {fullData.parents.map((parent: any, idx: number) => (
                      <span key={idx}>
                        {idx > 0 && ' | '}
                        <span
                          className="fb-sct-popup-hoverable"
                          tabIndex={0}
                          onMouseDown={(e) => {
                            e.preventDefault();
                            handleConceptClick(parent.pt);
                          }}
                          onKeyDown={(e) => {
                            if (e.key === 'Enter') {
                              e.preventDefault();
                              handleConceptClick(parent.pt);
                            }
                          }}
                          style={{color: '#1b6ec2', cursor: 'pointer', textDecoration: 'underline'}}
                        >
                          {parent.pt}
                        </span>
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {fullData.fst && (
                <div style={{marginBottom: '0.25rem'}}>
                  <div style={{backgroundColor: '#8cd2e7', color: 'black', fontSize: '0.6rem', width: '100%', padding: '0.2rem 0.5rem'}}>
                    Concept
                  </div>
                  <div style={{fontSize: '1.5rem', margin: '0.25rem 0', fontWeight: 500}}>
                    {fullData.fst}
                  </div>
                </div>
              )}

              <div style={{margin: '0.25rem 0', display: 'flex', gap: '0.3rem'}}>
                <button
                  type="button"
                  onMouseDown={(e) => {
                    e.preventDefault();
                    if (historyIndex > 0) handleBack();
                  }}
                  disabled={historyIndex <= 0}
                  className="fb-sct-popup-btn"
                  style={{ backgroundColor: '#1b6ec2' }}
                >
                  &lt;
                </button>
                <button
                  type="button"
                  onMouseDown={(e) => {
                    e.preventDefault();
                    if (historyIndex < searchHistory.length - 1) handleNext();
                  }}
                  disabled={historyIndex >= searchHistory.length - 1}
                  className="fb-sct-popup-btn"
                  style={{ backgroundColor: '#1b6ec2' }}
                >
                  &gt;
                </button>
                <button
                  type="button"
                  onMouseDown={(e) => {
                    e.preventDefault();
                    if (fullData.pt) handleSelect(fullData.pt);
                  }}
                  className="fb-sct-popup-btn"
                  style={{ backgroundColor: '#008000' }}
                >
                  Select
                </button>
                <button
                  type="button"
                  onMouseDown={(e) => {
                    e.preventDefault();
                    handleClose();
                  }}
                  className="fb-sct-popup-btn"
                  style={{ backgroundColor: '#d50000' }}
                >
                  Close
                </button>
              </div>

              <div style={{flex: 1, overflowY: 'auto', overflowX: 'hidden'}}>
                {fullData.synonyms && Array.isArray(fullData.synonyms) && fullData.synonyms.length > 0 && (
                  <div style={{marginBottom: '0.25rem'}}>
                    <div style={{backgroundColor: '#8cd2e7', color: 'black', fontSize: '0.6rem', width: '100%', padding: '0.2rem 0.5rem'}}>
                      Synonyms
                    </div>
                    <div style={{marginTop: '0.3rem'}}>
                      {fullData.synonyms.map((synonym: string, idx: number) => (
                        <span key={idx}>
                          {idx > 0 && ' | '}
                          <span
                            className="fb-sct-popup-hoverable"
                            tabIndex={0}
                            style={{ color: 'black' }}
                          >
                            {synonym}
                          </span>
                        </span>
                      ))}
                    </div>
                  </div>
                )}

                {fullData.children && Array.isArray(fullData.children) && fullData.children.length > 0 && (
                  <div>
                    <div style={{backgroundColor: '#8cd2e7', color: 'black', fontSize: '0.6rem', width: '100%', padding: '0.2rem 0.5rem'}}>
                      Child concepts
                    </div>
                    <div style={{marginTop: '0.3rem'}}>
                      {fullData.children.map((child: any, idx: number) => (
                        <div key={idx} style={{ marginBottom: '0.1rem' }}>
                          <span
                            className="fb-sct-popup-hoverable"
                            tabIndex={0}
                            onMouseDown={(e) => {
                              e.preventDefault();
                              handleConceptClick(child.pt);
                            }}
                            onKeyDown={(e) => {
                              if (e.key === 'Enter') {
                                e.preventDefault();
                                handleConceptClick(child.pt);
                              }
                            }}
                            style={{color: '#1b6ec2', cursor: 'pointer', textDecoration: 'underline'}}
                          >
                            {child.pt}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        )}
        {isLoading && (
          <div style={{
            position: 'absolute',
            right: '2.5rem',
            top: '50%',
            transform: 'translateY(-50%)',
            fontSize: '0.8rem',
            color: '#666'
          }}>
            Searching...
          </div>
        )}
      </div>
      {searchTerm && isCoded && (
        <span className="material-icons" style={{
          color: '#008000',
          fontSize: '1.2rem'
        }} title={`Coded: ${selectedId}`}>
          check_circle_outline
        </span>
      )}
      {searchTerm && !isCoded && (
        <span className="material-icons" style={{
          color: '#fd8a10',
          fontSize: '1.2rem'
        }} title="Not coded">
          warning
        </span>
      )}
    </div>
  );

  if (label) {
    return (
      <FbQuestion label={label} required={required} valueError={valueError} labelStyle={labelStyle}>
        {renderContent()}
      </FbQuestion>
    );
  }

  const content = renderContent();
  if (!valueError && !required) return content;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.2rem', width: '100%' }}>
      <FbValueError message={valueError} />
      {required ? (
        <div style={{ display: 'flex', alignItems: 'flex-start', gap: '0.2rem', width: '100%', boxSizing: 'border-box' }}>
          <div style={{ flex: 1, width: '100%' }}>
            {content}
          </div>
          <span style={{ color: '#d50000', fontSize: '1rem', fontWeight: 'bold', lineHeight: '1.2rem', marginTop: '0.15rem', display: 'inline-block', userSelect: 'none' }}>*</span>
        </div>
      ) : content}
    </div>
  );
};
