// src/lib/components/fb/fbSection.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  let {
    id,
    title,
    children,
    class: className = ''
  }: {
    id: string;
    title: string;
    children: Snippet;
    class?: string;
  } = $props();
</script>

<section {id} class={`fb-section-block ${className}`.trim()}>
  <h3 class="font-bold text-white shadow-sm">{title}</h3>
  <div class="bg-white fb-section-body">
    {@render children()}
  </div>
</section>

<style>
  .fb-section-block {
    display: flex;
    flex-direction: column;
    margin-bottom: 0.8rem;
  }

  h3 {
    background-color: rgb(27 110 194);
    color: white;
    font-family: 'Roboto', sans-serif;
    font-size: 1rem;
    font-weight: 500;
    line-height: 1.2rem;
    padding: 0.2rem 0.2rem 0.2rem 0.4rem;
    margin: 0;
    text-transform: none;
    border-radius: 0.2rem 0.2rem 0 0;
  }

  .fb-section-body {
    padding: 0.4rem 0;
    margin-top: 0.4rem;
    margin-bottom: 0.6rem;
  }
</style>

// src/components/fbSection.tsx
import React from 'react';

interface fbSectionProps {
  id: string;
  title: string;
  children: React.ReactNode;
  style?: React.CSSProperties;
  className?: string;
}

export const fbSection: React.FC<fbSectionProps> = ({
  id,
  title,
  children,
  style,
  className = '',
}) => {
  return (
    <div
      id={id}
      className={`fb-section-block ${className}`}
      style={{
        display: 'flex',
        flexDirection: 'column',
        marginBottom: '0.8rem',
        ...style
      }}
    >
      <h3
        className="font-bold text-white shadow-sm"
        style={{
          backgroundColor: 'rgb(27, 110, 194)',
          color: 'white',
          fontFamily: "'Roboto', sans-serif",
          fontSize: '1rem',
          fontWeight: 500,
          lineHeight: '1.2rem',
          padding: '0.2rem 0.2rem 0.2rem 0.4rem',
          margin: 0,
          textTransform: 'none',
          borderRadius: '0.2rem 0.2rem 0 0',
        }}
      >
        {title}
      </h3>
      <div
        className="bg-white"
        style={{
          padding: '0.4rem 0rem',
          marginTop: '0.4rem',
          marginBottom: '0.6rem',
        }}
      >
        {children}
      </div>
    </div>
  );
};
