// svelte/src/components/fbSearchInput.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  export let id = '';
  export let label = 'Search for';
  export let value = '';
  export let placeholder = '';
  export let autoFocus = false;
  export let onChange: (value: string) => void = () => {};
  let inputElement: HTMLInputElement;

  function emitValue(nextValue: string) {
    value = nextValue;
    onChange(value);
  }

  onMount(() => {
    if (autoFocus) inputElement?.focus();
  });
</script>

<label class="fb-search-input" for={id}>
  <span>{label}</span>
  <input
    {id}
    bind:this={inputElement}
    type="search"
    bind:value
    {placeholder}
    oninput={(event) => emitValue((event.currentTarget as HTMLInputElement).value)}
  />
</label>

<style>
  .fb-search-input {
    display: grid;
    grid-template-columns: max-content 1fr;
    align-items: center;
    gap: 0.6rem;
    width: 100%;
    font-size: 1rem;
    font-weight: 500;
  }

  input {
    width: 100%;
    height: 2rem;
    padding: 0 0.5rem;
    border: 0.1rem solid silver;
    border-radius: 0.4rem;
    font-size: 1rem;
    font-weight: 300;
    box-sizing: border-box;
  }

  input:hover,
  input:focus {
    background: var(--fb-active-darker-yellow);
    outline: none;
  }
</style>

// src/components/fbSearchInput.tsx
import React from 'react';
import { fbQuestion as FbQuestion } from './fbQuestion';

interface fbSearchInputProps {
  label?: string;
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
  id?: string;
  autoFocus?: boolean;
}

export const fbSearchInput: React.FC<fbSearchInputProps> = ({
  label,
  value,
  onChange,
  placeholder = '',
  id,
  autoFocus = false,
}) => {
  const inputRef = React.useRef<HTMLInputElement>(null);

  React.useEffect(() => {
    if (autoFocus && inputRef.current) {
      inputRef.current.focus();
    }
  }, [autoFocus]);

  const handleClear = () => {
    onChange('');
    if (inputRef.current) {
      inputRef.current.focus();
    }
  };

  const renderInput = () => {
    return (
      <div style={{ position: 'relative', display: 'flex', alignItems: 'center', width: '100%' }}>
        <input
          ref={inputRef}
          type="text"
          id={id}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          placeholder={placeholder}
          className="w-full text-black font-sans"
          style={{
            fontFamily: "'Roboto', sans-serif",
            fontWeight: 400,
            border: '0.1rem solid silver',
            borderRadius: '0.4rem',
            padding: '0.3rem 2.2rem 0.3rem 0.5rem',
            fontSize: '1rem',
            boxSizing: 'border-box',
            height: '2rem',
            backgroundColor: 'white',
          }}
        />
        {value && (
          <button
            type="button"
            onClick={handleClear}
            onMouseDown={(e) => e.preventDefault()}
            style={{
              position: 'absolute',
              right: '0.5rem',
              border: 'none',
              background: 'none',
              cursor: 'pointer',
              color: 'silver',
              fontSize: '1.2rem',
              padding: '0.1rem',
              lineHeight: 1,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              height: '100%'
            }}
          >
            ✕
          </button>
        )}
      </div>
    );
  };

  if (!label) {
    return renderInput();
  }

  return (
    <FbQuestion
      label={label}
      required={false}
      style={{ width: '100%' }}
    >
      {renderInput()}
    </FbQuestion>
  );
};
