// svelte/src/components/fbSmartDropdown.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte';
  import FbQuestion from './fbQuestion.svelte';
  import { matchSmartDropdownOptions, normaliseSmartDropdownOptions, type SmartDropdownOption } from '../lib/smartDropdown';

  export let id = '';
  export let name = '';
  export let label = '';
  export let value = '';
  export let options: Array<SmartDropdownOption | string> = [];
  export let required = false;
  export let requiredForAudit = false;
  export let placeholder = 'Type here to search';
  export let subfield = false;
  export let valueError = '';
  export let noWidthConstraint = false;
  export let fullWidth = false;
  export let onChange: (value: string) => void = () => {};
  export let change: (value: string) => void = () => {};

  const dispatch = createEventDispatcher<{ change: string }>();
  let wrapper: HTMLDivElement;
  let inputValue = '';
  let open = false;
  $: listId = `${id || name || 'fb-smart-dropdown'}-list`;

  $: parsedOptions = normaliseSmartDropdownOptions(options);
  $: selected = parsedOptions.find((option) => option.value === value);
  $: if (!open) inputValue = selected?.label || value || '';
  $: matches = matchSmartDropdownOptions(parsedOptions, inputValue, 20);

  function emitValue(nextValue: string) {
    value = nextValue;
    onChange(nextValue);
    change(nextValue);
    dispatch('change', nextValue);
  }

  function choose(option: SmartDropdownOption) {
    inputValue = option.label;
    emitValue(option.value);
    open = false;
  }

  onMount(() => {
    const close = (event: PointerEvent) => {
      if (wrapper && event.target instanceof Node && !wrapper.contains(event.target)) open = false;
    };
    document.addEventListener('pointerdown', close);
    return () => document.removeEventListener('pointerdown', close);
  });
</script>

{#if label}
  <FbQuestion {label} {required} {requiredForAudit} {subfield} {valueError}>
    <div class="fb-smart-dropdown" class:unconstrained={noWidthConstraint || fullWidth} bind:this={wrapper}>
      <input
        {id}
        {name}
        type="text"
        role="combobox"
        aria-expanded={open}
        aria-controls={listId}
        aria-autocomplete="list"
        {placeholder}
        {required}
        value={inputValue}
        onfocus={() => (open = true)}
        oninput={(event) => {
          inputValue = (event.currentTarget as HTMLInputElement).value;
          emitValue(inputValue);
          open = true;
        }}
      />
      {#if open && matches.length > 0}
        <div id={listId} class="fb-smart-dropdown-list" role="listbox">
          {#each matches as option}
            <button type="button" role="option" aria-selected={option.value === value} class:selected={option.value === value} onmousedown={(event) => event.preventDefault()} onclick={() => choose(option)}>
              {option.label}
            </button>
          {/each}
        </div>
      {/if}
    </div>
    <slot selectedValue={value} />
  </FbQuestion>
{:else}
  <div class="fb-smart-dropdown" class:unconstrained={noWidthConstraint || fullWidth} bind:this={wrapper}>
    <input
      {id}
      {name}
      type="text"
      role="combobox"
      aria-expanded={open}
      aria-controls={listId}
      aria-autocomplete="list"
      {placeholder}
      {required}
      value={inputValue}
      onfocus={() => (open = true)}
      oninput={(event) => {
        inputValue = (event.currentTarget as HTMLInputElement).value;
        emitValue(inputValue);
        open = true;
      }}
    />
    {#if open && matches.length > 0}
      <div id={listId} class="fb-smart-dropdown-list" role="listbox">
        {#each matches as option}
          <button type="button" role="option" aria-selected={option.value === value} class:selected={option.value === value} onmousedown={(event) => event.preventDefault()} onclick={() => choose(option)}>
            {option.label}
          </button>
        {/each}
      </div>
    {/if}
  </div>
  <slot selectedValue={value} />
{/if}

<style>
  .fb-smart-dropdown {
    position: relative;
    width: 100%;
    max-width: 35rem;
  }

  .fb-smart-dropdown.unconstrained {
    max-width: none;
  }

  input {
    width: 100%;
    height: 2rem;
    border: 0.1rem solid silver;
    border-radius: 0.4rem;
    box-sizing: border-box;
    padding: 0.2rem 0.4rem;
    font-size: 1rem;
    font-weight: 400;
  }

  .fb-smart-dropdown-list {
    position: absolute;
    z-index: 1000;
    top: 2.1rem;
    left: 0;
    right: 0;
    max-height: 16rem;
    overflow-y: auto;
    background: white;
    border: 0.1rem solid silver;
    border-radius: 0.4rem;
    box-shadow: 0 2px 8px rgb(0 0 0 / 15%);
  }

  .fb-smart-dropdown-list button {
    display: block;
    width: 100%;
    border: 0;
    background: white;
    padding: 0.25rem 0.4rem;
    text-align: left;
    font-size: 1rem;
    cursor: pointer;
  }

  .fb-smart-dropdown-list button:hover,
  .fb-smart-dropdown-list button:focus,
  .fb-smart-dropdown-list button.selected {
    background: var(--fb-active-lighter-yellow);
  }
</style>

// src/components/fbSmartDropdown.tsx
import React from 'react';
import { fbQuestion as FbQuestion } from './fbQuestion';
import { matchSmartDropdownOptions, normaliseSmartDropdownOptions, SmartDropdownOption } from '../utils/smartDropdown';

interface fbSmartDropdownProps {
  label?: string;
  value: string;
  onChange: (value: string) => void;
  options: (SmartDropdownOption | string)[];
  required?: boolean;
  requiredForAudit?: boolean;
  placeholder?: string;
  subfield?: boolean;
  valueError?: string;
  id?: string;
  name?: string;
  children?: React.ReactNode;
  noWidthConstraint?: boolean;
  fullWidth?: boolean;
}

export const fbSmartDropdown: React.FC<fbSmartDropdownProps> = ({
  label,
  value,
  onChange,
  options,
  required,
  requiredForAudit,
  placeholder = 'Type here to search',
  subfield = false,
  valueError,
  id,
  name,
  children,
  noWidthConstraint = false,
  fullWidth = false,
}) => {
  const parsedOptions = React.useMemo(() => normaliseSmartDropdownOptions(options), [options]);
  const selected = parsedOptions.find((option) => option.value === value);
  const [inputValue, setInputValue] = React.useState(selected?.label || value || '');
  const [open, setOpen] = React.useState(false);
  const wrapperRef = React.useRef<HTMLDivElement>(null);

  React.useEffect(() => {
    const nextSelected = parsedOptions.find((option) => option.value === value);
    setInputValue(nextSelected?.label || value || '');
  }, [parsedOptions, value]);

  React.useEffect(() => {
    const handlePointerDown = (event: PointerEvent) => {
      if (!wrapperRef.current?.contains(event.target as Node)) setOpen(false);
    };
    document.addEventListener('pointerdown', handlePointerDown);
    return () => document.removeEventListener('pointerdown', handlePointerDown);
  }, []);

  const matches = matchSmartDropdownOptions(parsedOptions, inputValue, 20);
  const childContent = React.Children.map(children, (child) => React.isValidElement(child) ? React.cloneElement(child as React.ReactElement<any>, { selectedValue: value }) : child);

  const control = (
    <>
      <div ref={wrapperRef} style={{ position: 'relative', width: '100%', maxWidth: fullWidth || noWidthConstraint ? undefined : '35rem' }}>
        <input
          id={id}
          name={name}
          type="text"
          role="combobox"
          aria-expanded={open}
          aria-autocomplete="list"
          value={inputValue}
          placeholder={placeholder}
          required={required}
          onFocus={() => setOpen(true)}
          onChange={(event) => {
            setInputValue(event.target.value);
            onChange(event.target.value);
            setOpen(true);
          }}
          style={{
            width: '100%',
            height: '2rem',
            border: '0.1rem solid silver',
            borderRadius: '0.4rem',
            boxSizing: 'border-box',
            padding: '0.2rem 0.4rem',
            fontFamily: "'Roboto', sans-serif",
            fontSize: '1rem',
            fontWeight: 400,
          }}
        />
        {open && matches.length > 0 && (
          <div
            role="listbox"
            style={{
              position: 'absolute',
              zIndex: 1000,
              top: '2.1rem',
              left: 0,
              right: 0,
              maxHeight: '16rem',
              overflowY: 'auto',
              backgroundColor: 'white',
              border: '0.1rem solid silver',
              borderRadius: '0.4rem',
              boxShadow: '0 2px 8px rgba(0,0,0,0.15)',
            }}
          >
            {matches.map((option) => (
              <button
                key={option.value}
                type="button"
                role="option"
                aria-selected={option.value === value}
                onClick={() => {
                  onChange(option.value);
                  setInputValue(option.label);
                  setOpen(false);
                }}
                style={{
                  display: 'block',
                  width: '100%',
                  border: 'none',
                  backgroundColor: option.value === value ? '#ffffcc' : 'white',
                  padding: '0.25rem 0.4rem',
                  textAlign: 'left',
                  fontFamily: "'Roboto', sans-serif",
                  fontSize: '1rem',
                  cursor: 'pointer',
                }}
              >
                {option.label}
              </button>
            ))}
          </div>
        )}
      </div>
      {childContent}
    </>
  );

  if (!label) return control;
  return (
    <FbQuestion
      label={label}
      required={required}
      requiredForAudit={requiredForAudit}
      labelStyle={subfield ? { fontWeight: 300, fontSize: '1rem' } : undefined}
      valueError={valueError}
    >
      {control}
    </FbQuestion>
  );
};
