// src/components/fbCancelPopup.tsx
import React from 'react';
import { fbButton as FbButton } from './fbButton';
import { fbPopup as FbPopup } from './fbPopup';

interface CancelPopupProps {
  onDiscard: () => void;
  onReturnToForm: () => void;
}

export const fbCancelPopup: React.FC<CancelPopupProps> = ({
  onDiscard,
  onReturnToForm
}) => {
  return (
    <FbPopup
      title="Confirm cancel"
      footer={
        <div style={{ display: 'flex', gap: '0.5rem', justifyContent: 'flex-end' }}>
          <FbButton
            type="button"
            variant="danger"
            onClick={onDiscard}
          >
            Discard changes
          </FbButton>
          <FbButton
            type="button"
            variant="success"
            onClick={onReturnToForm}
          >
            Return to form
          </FbButton>
        </div>
      }
    >
      <p style={{ marginBottom: '1.5rem', lineHeight: '1.4', color: '#333333' }}>
        Any changes you have made will be lost
      </p>
    </FbPopup>
  );
};

// svelte/src/components/fbCancelPopup.svelte
<script lang="ts">
  import FbPopup from './fbPopup.svelte';
  import FbButton from './fbButton.svelte';
  export let onDiscard: () => void = () => {};
  export let onReturnToForm: () => void = () => {};
</script>

<FbPopup title="Discard changes?">
  <p>Changes have not been saved.</p>
  <div class="actions">
    <FbButton onClick={onDiscard}>Discard changes</FbButton>
    <FbButton variant="green" onClick={onReturnToForm}>Return to form</FbButton>
  </div>
</FbPopup>

<style>.actions { display: flex; gap: 0.4rem; justify-content: flex-end; }</style>
