// src/components/fbCheck.tsx
import React from 'react';
import { fbGroupRequiredMarkerContext } from './fbGroup';
import { fbQuestionRequiredMarkerContext } from './fbQuestion';

interface fbCheckProps {
  id?: string;
  name: string;
  value?: string;
  checked: boolean;
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  label: string;
  required?: boolean;
  requiredForAudit?: boolean;
  showRequiredMarkers?: boolean;
  disabled?: boolean;
  children?: React.ReactNode; // For subquestions or nested content
  style?: React.CSSProperties;
  onMouseEnter?: (e: React.MouseEvent<HTMLLabelElement>) => void;
  onMouseLeave?: (e: React.MouseEvent<HTMLLabelElement>) => void;
  onFocus?: (e: React.FocusEvent<HTMLInputElement>) => void;
  onBlur?: (e: React.FocusEvent<HTMLInputElement>) => void;
}

export const fbCheck: React.FC<fbCheckProps> = ({
  id,
  name,
  value,
  checked,
  onChange,
  label,
  required,
  requiredForAudit,
  showRequiredMarkers = true,
  disabled,
  children,
  style,
  onMouseEnter,
  onMouseLeave,
  onFocus,
  onBlur,
}) => {
  const groupOwnsRequiredMarkers = React.useContext(fbGroupRequiredMarkerContext);
  const questionOwnsRequiredMarkers = React.useContext(fbQuestionRequiredMarkerContext);
  const renderRequiredMarkers = showRequiredMarkers && !groupOwnsRequiredMarkers && !questionOwnsRequiredMarkers;

  return (
    <div className="fb-subquestion-wrapper" style={style}>
      <label
        className="flex items-start gap-2 fb-radio-checkbox-item w-full"
        onMouseEnter={onMouseEnter}
        onMouseLeave={onMouseLeave}
        style={{
          paddingTop: 0,
          paddingBottom: 0,
          marginTop: 0,
          marginBottom: 0,
          cursor: 'pointer',
          fontFamily: "'Roboto', sans-serif",
          fontSize: '1rem',
          fontWeight: 300,
          userSelect: 'none',
          display: 'flex',
          alignItems: 'flex-start',
          borderRadius: '0.4rem',
          boxSizing: 'border-box'
        }}
      >
        <input
          id={id}
          type="checkbox"
          name={name}
          value={value}
          checked={checked}
          onChange={onChange}
          required={required}
          disabled={disabled}
          onFocus={onFocus}
          onBlur={onBlur}
          style={{
            cursor: 'pointer',
            flexShrink: 0,
            outline: 'none',
            boxShadow: 'none'
          }}
        />
        <span style={{ fontWeight: 300 }}>
          {label}
          {renderRequiredMarkers && requiredForAudit && <span style={{ backgroundColor: '#fd8a10', color: 'white', fontSize: '0.8rem', fontWeight: 300, lineHeight: 1, marginLeft: '0.1rem', padding: '0.05rem 0.2rem', display: 'inline-block', whiteSpace: 'nowrap' }}>RfA</span>}
          {renderRequiredMarkers && required && <span style={{ color: '#d50000', marginLeft: '0.1rem', fontWeight: 500 }}>*</span>}
        </span>
      </label>
      {checked && children && (
        <div className="pl-6 pb-1">
          {children}
        </div>
      )}
    </div>
  );
};

// svelte/src/components/fbCheck.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import FbToolTip from './fbToolTip.svelte';
  export let name = '';
  export let checked = false;
  export let label = '';
  export let required = false;
  export let requiredForAudit = false;
  export let tooltip = '';
  export let disabled = false;
  export let onChange: (checked: boolean) => void = () => {};
  export let change: (checked: boolean) => void = () => {};
  const dispatch = createEventDispatcher<{ change: boolean }>();

  function emitValue(nextChecked: boolean) {
    onChange(nextChecked);
    change(nextChecked);
    dispatch('change', nextChecked);
  }
</script>

<div class="fb-subquestion-wrapper">
  <FbToolTip text={tooltip} as="label" className="fb-radio-checkbox-item">
    <input
      type="checkbox"
      {name}
      {disabled}
      {required}
      checked={checked}
      onchange={(event) => emitValue((event.currentTarget as HTMLInputElement).checked)}
    />
    <span class="choice-label">{label}{#if requiredForAudit}<span class="fb-required-for-audit">RfA</span>{/if}{#if required}<span class="required">*</span>{/if}</span>
  </FbToolTip>
  {#if checked}
    <div class="fb-subquestion-wrapper"><slot /></div>
  {/if}
</div>

<style>
  .fb-subquestion-wrapper {
    padding: 0;
  }

  :global(.fb-radio-checkbox-item) {
    display: flex;
    align-items: flex-start;
    gap: 0.5rem;
    width: 100%;
    padding: 0 0.2rem;
    margin: 0;
    border-radius: 0.4rem;
    box-sizing: border-box;
    cursor: pointer;
    font-size: 1rem;
    font-weight: 300;
    line-height: 1.2;
    user-select: none;
  }

  input {
    margin: 0;
  }

  .choice-label {
    font-weight: 300;
  }

  .fb-required-for-audit {
    display: inline-block;
    margin-left: 0.1rem;
    padding: 0.05rem 0.2rem;
    background: var(--fb-orange);
    color: white;
    font-size: 1rem;
    font-weight: 500;
    line-height: 1;
    white-space: nowrap;
  }

  .required {
    margin-left: 0.1rem;
    color: var(--fb-red);
    font-weight: 500;
  }

  .fb-subquestion-wrapper .fb-subquestion-wrapper {
    padding-left: 1.5rem;
  }
</style>
