// src/components/fbMSISelector.tsx
import React from 'react';
import { parseServerResponse } from '../utils/shadesOfPaleParser';
import { fbQuestion as FbQuestion } from './fbQuestion';
import { fbValueError as FbValueError } from './fbValueError';

interface MSISelectorProps {
  label?: string;
  name: string;
  value: string;
  onChange: (value: string, coded: boolean) => void;
  onFocus?: (e: React.FocusEvent<HTMLInputElement>) => void;
  onBlur?: () => void;
  required?: boolean;
  coded?: boolean;
  placeholder?: string;
  hasLabel?: boolean;
  valueError?: string;
  labelStyle?: React.CSSProperties;
}

export const fbMSISelector: React.FC<MSISelectorProps> = ({ 
  label,
  name, 
  value, 
  onChange, 
  onFocus, 
  onBlur, 
  required, 
  coded,
  placeholder = "Type to search staff index",
  hasLabel = true,
  valueError,
  labelStyle
}) => {
  const [searchTerm, setSearchTerm] = React.useState<string>(value);
  const [results, setResults] = React.useState<Array<{score: number, ie: {line: string}}>>([]);
  const [showDropdown, setShowDropdown] = React.useState<boolean>(false);
  const [isLoading, setIsLoading] = React.useState<boolean>(false);
  const [highlightedIndex, setHighlightedIndex] = React.useState<number>(-1);
  const [dropdownLeft, setDropdownLeft] = React.useState<number>(0);
  const [dropdownTop, setDropdownTop] = React.useState<number>(0);
  const [dropdownMaxHeight, setDropdownMaxHeight] = React.useState<number>(300);
  const [justSelected, setJustSelected] = React.useState<boolean>(false);
  const [hasInteracted, setHasInteracted] = React.useState<boolean>(false);
  const [lastSelectedValue, setLastSelectedValue] = React.useState<string>(value);

  React.useEffect(() => {
    if (value !== searchTerm) {
      setSearchTerm(value);
      setLastSelectedValue(value);
    }
  }, [value]);
  const inputRef = React.useRef<HTMLInputElement>(null);
  const dropdownRef = React.useRef<HTMLDivElement>(null);
  const containerRef = React.useRef<HTMLDivElement>(null);

  const performSearch = () => {
    if (searchTerm.length > 0) {
      setIsLoading(true);
      const authHeader = 'Basic ' + btoa('dhcw:dhcw');

      fetch(`https://www.shadesofpale.net/MSISearch?st=${encodeURIComponent(searchTerm)}`, {
        method: 'GET',
        headers: {
          'Authorization': authHeader,
          'Accept': 'application/json'
        }
      })
        .then(response => response.text())
        .then(text => {
          try {
            const data = parseServerResponse(text);
            setResults(data || []);
            if (hasInteracted) {
              setShowDropdown(true);
            }
            setHighlightedIndex(-1);
          } catch (e) {
            console.error('Failed to parse response:', e);
            setResults([]);
          }
          setIsLoading(false);
        })
        .catch(error => {
          console.error('MSISearch error:', error);
          setResults([]);
          setIsLoading(false);
        });
    } else {
      setResults([]);
      setShowDropdown(false);
      setHighlightedIndex(-1);
    }
  };

  React.useEffect(() => {
    if (!justSelected) {
      performSearch();
    }
  }, [searchTerm]);

  const updateDropdownPosition = React.useCallback(() => {
    if (containerRef.current) {
      const dropdownWidthPx = 45 * 16;
      const maxDropdownWidth = Math.min(dropdownWidthPx, window.innerWidth - 40);
      const containerRect = containerRef.current.getBoundingClientRect();

      const spaceBelow = window.innerHeight - containerRect.bottom - 20;
      const spaceAbove = containerRect.top - 20;
      const preferredHeight = 300;

      let topPos: number;
      let maxHeight: number;

      if (spaceBelow >= preferredHeight || spaceBelow >= spaceAbove) {
        topPos = containerRect.bottom + 2;
        maxHeight = Math.min(preferredHeight, Math.max(100, spaceBelow));
      } else {
        maxHeight = Math.min(preferredHeight, Math.max(100, spaceAbove));
        topPos = containerRect.top - maxHeight - 2;
      }

      setDropdownTop(topPos);
      setDropdownMaxHeight(maxHeight);

      const dropdownRight = containerRect.left + maxDropdownWidth;

      if (dropdownRight > window.innerWidth) {
        const shift = dropdownRight - window.innerWidth + 20;
        setDropdownLeft(containerRect.left - shift);
      } else {
        setDropdownLeft(containerRect.left);
      }
    }
  }, []);

  React.useEffect(() => {
    if (showDropdown && results.length > 0) {
      setHighlightedIndex(-1);
      updateDropdownPosition();

      const scrollContainer = document.querySelector('.flex-1.overflow-y-auto');
      if (scrollContainer) {
        scrollContainer.addEventListener('scroll', updateDropdownPosition);
        return () => {
          scrollContainer.removeEventListener('scroll', updateDropdownPosition);
        };
      }
    } else if (!showDropdown) {
      setHighlightedIndex(-1);
    }
  }, [showDropdown, results, updateDropdownPosition]);

  const handleSelect = (line: string) => {
    setJustSelected(true);
    setSearchTerm(line);
    onChange(line, true);
    setShowDropdown(false);
    setHighlightedIndex(-1);
    setLastSelectedValue(line);
    setTimeout(() => setJustSelected(false), 100);
  };

  const handleClear = () => {
    setSearchTerm('');
    onChange('', false);
    setShowDropdown(false);
    setResults([]);
    setHighlightedIndex(-1);
    setLastSelectedValue('');
    if (inputRef.current) {
      inputRef.current.focus();
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Escape') {
      e.preventDefault();
      setShowDropdown(false);
      setHighlightedIndex(-1);
      return;
    }

    if (!showDropdown || results.length === 0) return;

    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setHighlightedIndex(prev => {
        if (prev === -1) return 0;
        return Math.min(prev + 1, results.length - 1);
      });
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setHighlightedIndex(prev => {
        return Math.max(prev - 1, -1);
      });
    } else if (e.key === 'Enter' && highlightedIndex >= 0) {
      e.preventDefault();
      handleSelect(results[highlightedIndex].ie.line);
    }
  };

  const renderContent = () => {
    return (
      <div style={{display: 'flex', alignItems: 'center', width: '100%', gap: '0.3rem'}}>
        <div ref={containerRef} style={{position: 'relative', flex: 1}}>
          <div style={{position: 'relative', display: 'flex', alignItems: 'center'}}>
            <input
              ref={inputRef}
              type="text"
              name={name}
              value={searchTerm}
              onChange={(e) => {
                setHasInteracted(true);
                setSearchTerm(e.target.value);
                onChange(e.target.value, false);
              }}
              onFocus={(e) => {
                setHasInteracted(true);
                if (results.length > 0 && !justSelected) setShowDropdown(true);
                if (onFocus) onFocus(e);
              }}
              onBlur={() => {
                setTimeout(() => {
                  setShowDropdown(false);
                  if (onBlur) onBlur();
                }, 200);
              }}
              onKeyDown={handleKeyDown}
              className="w-full p-2 fb-hide-border-in-rov fb-msi-selector-input"
              style={{
                border: '0.1rem solid silver',
                borderRadius: '0.4rem',
                paddingRight: '2.5rem',
                height: '2rem',
                boxSizing: 'border-box',
                backgroundColor: 'white'
              }}
              required={required}
              placeholder={placeholder}
              autoComplete="off"
            />
            <div style={{
              position: 'absolute',
              right: '0.2rem',
              display: 'flex',
              gap: '0.1rem',
              alignItems: 'center'
            }}>
              {searchTerm && (
                <button
                  type="button"
                  onClick={handleClear}
                  onMouseDown={(e) => e.preventDefault()}
                  style={{
                    border: 'none',
                    background: 'none',
                    cursor: 'pointer',
                    color: '#666',
                    fontSize: '0.9rem',
                    padding: '0.1rem',
                    lineHeight: 1
                  }}
                >
                  ✕
                </button>
              )}
              <button
                type="button"
                onClick={() => {
                  setHasInteracted(true);
                  if (showDropdown) {
                    setShowDropdown(false);
                    setHighlightedIndex(-1);
                  } else {
                    setHighlightedIndex(-1);
                    if (results.length > 0) {
                      setShowDropdown(true);
                    } else {
                      performSearch();
                    }
                  }
                }}
                onMouseDown={(e) => e.preventDefault()}
                style={{
                  border: 'none',
                  background: 'none',
                  cursor: 'pointer',
                  color: '#666',
                  fontSize: '1rem',
                  padding: '0.1rem',
                  lineHeight: 1
                }}
              >
                {showDropdown ? '▲' : '▼'}
              </button>
            </div>
          </div>
          {showDropdown && results.length > 0 && (
            <div
              ref={dropdownRef}
              style={{
                position: 'fixed',
                top: `${dropdownTop}px`,
                left: `${dropdownLeft}px`,
                width: '45rem',
                maxWidth: '100vw',
                maxHeight: `${dropdownMaxHeight}px`,
                overflowY: 'auto',
                overflowX: 'auto',
                backgroundColor: 'white',
                border: '0.1rem solid silver',
                borderRadius: '0.4rem',
                zIndex: 10000,
                boxShadow: '0 2px 8px rgba(0,0,0,0.15)'
              }}
            >
              {results.map((result, index) => (
                <div
                  key={index}
                  onMouseDown={() => handleSelect(result.ie.line)}
                  onMouseEnter={() => setHighlightedIndex(index)}
                  style={{
                    padding: '0.2rem 0.5rem',
                    cursor: 'pointer',
                    fontSize: '0.9rem',
                    whiteSpace: 'nowrap',
                    backgroundColor: highlightedIndex === index ? '#ffffcc' : 'white',
                    transition: 'background-color 0.2s',
                    lineHeight: '1.2'
                  }}
                >
                  {result.ie.line}
                </div>
              ))}
            </div>
          )}
          {isLoading && (
            <div style={{
              position: 'absolute',
              right: '2.5rem',
              top: '50%',
              transform: 'translateY(-50%)',
              fontSize: '0.8rem',
              color: '#666'
            }}>
              Searching...
            </div>
          )}
        </div>
        {searchTerm && (coded !== undefined ? coded : (searchTerm === lastSelectedValue)) && (
          <span className="material-icons" style={{
            color: '#008000',
            fontSize: '1.2rem'
          }} title="Coded">
            check_circle_outline
          </span>
        )}
        {searchTerm && !(coded !== undefined ? coded : (searchTerm === lastSelectedValue)) && (
          <span className="material-icons" style={{
            color: '#fd8a10',
            fontSize: '1.2rem'
          }} title="Not coded">
            warning
          </span>
        )}
      </div>
    );
  };

  const renderWithStandaloneValueError = (content: React.ReactNode) => {
    if (!valueError) return content;
    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.2rem', width: '100%' }}>
        <FbValueError message={valueError} />
        {content}
      </div>
    );
  };

  if (label) {
    return (
      <FbQuestion label={label} required={required} valueError={valueError} labelStyle={labelStyle}>
        {renderContent()}
      </FbQuestion>
    );
  }

  if (required && !hasLabel) {
    return renderWithStandaloneValueError(
      <div style={{ display: 'flex', alignItems: 'flex-start', gap: '0.2rem', width: '100%', boxSizing: 'border-box' }}>
        <div style={{ flex: 1, width: '100%' }}>
          {renderContent()}
        </div>
        <span style={{ color: '#d50000', fontSize: '1rem', fontWeight: 'bold', lineHeight: '1.2rem', marginTop: '0.15rem', display: 'inline-block', userSelect: 'none' }}>*</span>
      </div>
    );
  }

  return renderWithStandaloneValueError(renderContent());
};

// svelte/src/components/fbMSISelector.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import FbQuestion from './fbQuestion.svelte';
  import { parseServerResponse } from '../lib/shadesOfPaleParser';

  export let id = '';
  export let name = '';
  export let label = '';
  export let value = '';
  export let required = false;
  export let coded: boolean | undefined = undefined;
  export let valueError = '';
  export let tooltip = '';
  export let onChange: (value: string, coded: boolean) => void = () => {};
  export let change: (value: string, coded: boolean) => void = () => {};

  type StaffResult = {
    display?: string;
    name?: string;
    fullName?: string;
    id?: string;
    code?: string;
    jobTitle?: string;
    specialty?: string;
  };

  const dispatch = createEventDispatcher<{ change: { value: string; coded: boolean } }>();

  let searchText = value;
  let localCoded = Boolean(value);
  let isOpen = false;
  let isSearching = false;
  let error = '';
  let results: StaffResult[] = [];
  let searchTimer: number | undefined;
  let blurTimer: number | undefined;

  $: if (value !== searchText && !isOpen) {
    searchText = value || '';
    localCoded = Boolean(value);
  }

  function displayFor(result: StaffResult) {
    return result.display || result.name || result.fullName || (result as any).ie?.line || result.id || result.code || '';
  }

  function detailFor(result: StaffResult) {
    return [result.jobTitle, result.specialty, result.code || result.id].filter(Boolean).join(' - ');
  }

  async function searchStaff(term: string) {
    const trimmed = term.trim();
    if (trimmed.length < 1) {
      results = [];
      isOpen = false;
      return;
    }

    try {
      isSearching = true;
      isOpen = true;
      error = '';
      const response = await fetch(`https://www.shadesofpale.net/MSISearch?st=${encodeURIComponent(trimmed)}`, {
        headers: { Authorization: `Basic ${btoa('dhcw:dhcw')}` },
      });
      const text = await response.text();
      const parsed = parseServerResponse(text);
      results = Array.isArray(parsed) ? parsed : Array.isArray(parsed?.results) ? parsed.results : [];
    } catch (err) {
      error = err instanceof Error ? err.message : String(err);
      results = [];
    } finally {
      isSearching = false;
    }
  }

  function queueSearch() {
    localCoded = false;
    isOpen = searchText.trim().length > 0;
    onChange(searchText, false);
    change(searchText, false);
    dispatch('change', { value: searchText, coded: false });
    window.clearTimeout(searchTimer);
    searchTimer = window.setTimeout(() => searchStaff(searchText), 250);
  }

  function selectResult(result: StaffResult) {
    searchText = displayFor(result);
    localCoded = true;
    isOpen = false;
    onChange(searchText, true);
    change(searchText, true);
    dispatch('change', { value: searchText, coded: true });
  }

  function clearValue() {
    searchText = '';
    localCoded = false;
    results = [];
    onChange('', false);
    change('', false);
    dispatch('change', { value: '', coded: false });
  }

  function toggleOpen() {
    isOpen = !isOpen;
    if (isOpen) searchStaff(searchText);
  }

  function closeAfterBlur() {
    window.clearTimeout(blurTimer);
    blurTimer = window.setTimeout(() => (isOpen = false), 200);
  }

  $: effectiveCoded = coded !== undefined ? coded : localCoded;
</script>

{#if label}
  <FbQuestion {label} {required} {valueError} {tooltip}>
    <div class="fb-selector">
      <div class="fb-selector-input-wrap">
        <input
          {id}
          {name}
          bind:value={searchText}
          placeholder="Type to search staff index"
          autocomplete="off"
          onfocus={() => { window.clearTimeout(blurTimer); isOpen = true; }}
          oninput={queueSearch}
          onblur={closeAfterBlur}
        />
        <div class="fb-selector-actions">
          {#if searchText}
            <button type="button" class="fb-selector-button fb-clear" aria-label="Clear" onmousedown={(event) => event.preventDefault()} onclick={clearValue}>✕</button>
          {/if}
          <button type="button" class="fb-selector-button fb-arrow" aria-label="Search" onmousedown={(event) => event.preventDefault()} onclick={toggleOpen}>{isOpen ? '▲' : '▼'}</button>
        </div>
      </div>
      {#if searchText}
        <span class="material-icons fb-coded-icon" class:coded={effectiveCoded} aria-hidden="true">{effectiveCoded ? 'check_circle_outline' : 'warning'}</span>
      {/if}
      {#if isOpen}
        <div class="fb-selector-popup">
          {#if isSearching && results.length === 0}
            <div class="fb-selector-empty">Searching...</div>
          {:else if error}
            <div class="fb-selector-empty">Search unavailable</div>
          {:else if results.length === 0}
            <div class="fb-selector-empty">No matches</div>
          {:else}
            {#each results as result}
              <button type="button" class="fb-selector-result" onclick={() => selectResult(result)}>
                <span>{displayFor(result)}</span>
                {#if detailFor(result)}<small>{detailFor(result)}</small>{/if}
              </button>
            {/each}
          {/if}
        </div>
      {/if}
    </div>
  </FbQuestion>
{:else}
  <div class="fb-selector">
    <div class="fb-selector-input-wrap">
      <input
        {id}
        {name}
        bind:value={searchText}
        placeholder="Type to search staff index"
        autocomplete="off"
        onfocus={() => { window.clearTimeout(blurTimer); isOpen = true; }}
        oninput={queueSearch}
        onblur={closeAfterBlur}
      />
      <div class="fb-selector-actions">
        {#if searchText}
          <button type="button" class="fb-selector-button fb-clear" aria-label="Clear" onmousedown={(event) => event.preventDefault()} onclick={clearValue}>✕</button>
        {/if}
        <button type="button" class="fb-selector-button fb-arrow" aria-label="Search" onmousedown={(event) => event.preventDefault()} onclick={toggleOpen}>{isOpen ? '▲' : '▼'}</button>
      </div>
    </div>
    {#if searchText}
      <span class="material-icons fb-coded-icon" class:coded={effectiveCoded} aria-hidden="true">{effectiveCoded ? 'check_circle_outline' : 'warning'}</span>
    {/if}
    {#if isOpen}
      <div class="fb-selector-popup">
        {#if isSearching && results.length === 0}
          <div class="fb-selector-empty">Searching...</div>
        {:else if error}
          <div class="fb-selector-empty">Search unavailable</div>
        {:else if results.length === 0}
          <div class="fb-selector-empty">No matches</div>
        {:else}
          {#each results as result}
            <button type="button" class="fb-selector-result" onclick={() => selectResult(result)}>
              <span>{displayFor(result)}</span>
              {#if detailFor(result)}<small>{detailFor(result)}</small>{/if}
            </button>
          {/each}
        {/if}
      </div>
    {/if}
  </div>
{/if}

<style>
  .fb-selector {
    position: relative;
    display: flex;
    gap: 0.3rem;
    align-items: center;
    width: 100%;
    max-width: 30rem;
  }

  .fb-selector-input-wrap {
    position: relative;
    flex: 1;
    min-width: 0;
  }

  input {
    width: 100%;
    height: 2rem;
    min-width: 0;
    border: 0.1rem solid silver;
    border-radius: 0.4rem;
    padding: 0.2rem 2.5rem 0.2rem 0.4rem;
    font-size: 1rem;
    font-weight: 400;
    box-sizing: border-box;
  }

  input::placeholder {
    color: #777;
    font-weight: 400;
    opacity: 1;
  }

  .fb-selector-actions {
    position: absolute;
    right: 0.2rem;
    top: 50%;
    transform: translateY(-50%);
    display: flex;
    gap: 0.1rem;
    align-items: center;
  }

  .fb-selector-button {
    border: none;
    background: none;
    color: #666;
    cursor: pointer;
    line-height: 1;
    padding: 0.1rem;
  }

  .fb-clear {
    font-size: 0.9rem;
  }

  .fb-arrow {
    font-size: 1rem;
  }

  .fb-coded-icon {
    color: #fd8a10;
    font-size: 1.2rem;
    text-align: center;
  }

  .fb-coded-icon.coded {
    color: #008000;
  }

  .fb-selector-popup {
    position: absolute;
    z-index: 50;
    top: 2.1rem;
    left: 0;
    width: 45rem;
    max-width: 100vw;
    max-height: 16rem;
    overflow: auto;
    border: 0.1rem solid silver;
    background: white;
    box-shadow: 0 0.2rem 0.5rem rgb(0 0 0 / 20%);
  }

  .fb-selector-result,
  .fb-selector-empty {
    display: block;
    width: 100%;
    padding: 0.35rem 0.5rem;
    border: none;
    border-bottom: 0.1rem solid #eee;
    background: white;
    color: #111;
    text-align: left;
    font-size: 0.95rem;
  }

  .fb-selector-result {
    cursor: pointer;
  }

  .fb-selector-result:hover,
  .fb-selector-result:focus {
    background: #ffffcc;
  }

  small {
    display: block;
    color: #555;
    font-size: 0.75rem;
  }
</style>
