// src/components/fbRoVField.tsx
import * as React from 'react';

const defaultEmptyValues = ['', 'select', 'Select side'];

interface fbRoVFieldProps {
  label: string;
  value: any;
  lookupTable?: Record<string, string>;
  units?: string;
  coded?: boolean;
  emptyValues?: any[];
  preserveGridSpace?: boolean;
  labelProps?: React.LabelHTMLAttributes<HTMLLabelElement>;
}

interface fbRoVTableCellProps extends React.TdHTMLAttributes<HTMLTableCellElement> {
  tone?: 'standard' | 'muted';
  verticalAlign?: React.CSSProperties['verticalAlign'];
}

export const isFbRoVEmptyValue = (value: any, emptyValues: any[] = defaultEmptyValues) => (
  value === undefined ||
  value === null ||
  emptyValues.includes(value)
);

export const fbRoVCodedIcon: React.FC<{ coded: boolean }> = ({ coded }) => (
  <span
    className="material-icons fb-rov-coded-icon"
    title={coded ? 'Coded' : 'Not coded'}
  >
    {coded ? 'check_circle_outline' : 'warning'}
  </span>
);

export const fbRoVField: React.FC<fbRoVFieldProps> = ({
  label,
  value,
  lookupTable,
  units,
  coded,
  emptyValues = defaultEmptyValues,
  preserveGridSpace = true,
  labelProps,
}) => {
  if (isFbRoVEmptyValue(value, emptyValues)) {
    return preserveGridSpace ? <div></div> : null;
  }

  const displayValue = lookupTable && lookupTable[value] ? lookupTable[value] : value;
  const hasInlineDetails = !!units || coded !== undefined;

  return (
    <div className="space-y-2 fb-question-container fb-rov-field">
      <label className="fb-rov-field-label" {...labelProps}>{label}</label>
      <div className={hasInlineDetails ? 'fb-rov-field-value fb-rov-field-value-inline' : 'fb-rov-field-value'}>
        <span>{displayValue}</span>
        {units && <span className="fb-rov-field-units"> {units}</span>}
        {coded !== undefined && React.createElement(fbRoVCodedIcon, { coded })}
      </div>
    </div>
  );
};

export const fbRoVTableCell: React.FC<fbRoVTableCellProps> = ({
  tone = 'standard',
  verticalAlign = 'top',
  className = '',
  style,
  children,
  ...rest
}) => (
  <td
    className={`fb-rov-table-cell ${tone === 'muted' ? 'fb-rov-table-cell-muted' : 'fb-rov-table-cell-standard'} ${className}`.trim()}
    style={{ verticalAlign, ...style }}
    {...rest}
  >
    {children}
  </td>
);

// svelte/src/components/fbRoVField.svelte
<script lang="ts">
  import FbToolTip from './fbToolTip.svelte';
  export let label = '';
  export let value: any = '';
  export let lookupTable: Record<string, string> | undefined = undefined;
  export let units = '';
  export let coded: boolean | undefined = undefined;
  export let tooltip = '';
  export let preserveGridSpace = false;
  $: displayValue = lookupTable && value ? lookupTable[value] || value : value;
</script>

<FbToolTip text={tooltip} as="div" className="fb-question-container">
  {#if preserveGridSpace || (value !== undefined && value !== null && value !== '')}
    <div class="fb-rov-field-label">{label}</div>
    <div class="fb-rov-field-value-inline">
      <div class="fb-rov-field-value">{displayValue || ''}{displayValue && units ? ` ${units}` : ''}</div>
      {#if coded !== undefined}
        <span class="material-icons fb-rov-coded-icon" title={coded ? 'Coded' : 'Not coded'}>{coded ? 'check_circle_outline' : 'warning'}</span>
      {/if}
    </div>
  {/if}
</FbToolTip>
