// reactOrig/src/components/fbSCTDiagnosis.tsx
import * as React from 'react';
import { fbSCTSelector as FbSCTSelector } from './fbSCTSelector';

interface SCTDiagnosisProps {
  label?: string;
  name: string;
  value: string;
  onChange: (value: string, coded: boolean) => void;
  onFocus?: (e: React.FocusEvent<HTMLInputElement>) => void;
  onBlur?: () => void;
  placeholder?: string;
  required?: boolean;
  requiredForAudit?: boolean;
  coded?: boolean;
  valueError?: string;
  labelStyle?: React.CSSProperties;
  subfield?: boolean;
}

export const fbSCTDiagnosis: React.FC<SCTDiagnosisProps> = ({
  label,
  name,
  value,
  onChange,
  onFocus,
  onBlur,
  placeholder = 'Type to search SNOMED CT',
  required,
  requiredForAudit,
  coded,
  valueError,
  labelStyle,
  subfield,
}) => (
  <FbSCTSelector
    label={label}
    name={name}
    value={value}
    onChange={onChange}
    onFocus={onFocus}
    onBlur={onBlur}
    placeholder={placeholder}
    required={required}
    requiredForAudit={requiredForAudit}
    coded={coded}
    valueError={valueError}
    labelStyle={labelStyle}
    subfield={subfield}
    searchCommand="findDisorder"
    mode="diagnosis"
  />
);

// svelte/src/components/fbSCTDiagnosis.svelte
<script lang="ts">
  import FbSCTProcedure from './fbSCTProcedure.svelte';

  export let id = '';
  export let name = '';
  export let label = '';
  export let value = '';
  export let required = false;
  export let requiredForAudit = false;
  export let coded: boolean | undefined = undefined;
  export let valueError = '';
  export let tooltip = '';
  export let subfield = false;
  export let onChange: (value: string, coded: boolean) => void = () => {};
  export let change: (value: string, coded: boolean) => void = () => {};
</script>

<FbSCTProcedure searchCommand="findDisorder" {id} {name} {label} {value} {required} {requiredForAudit} {coded} {valueError} {tooltip} {subfield} {onChange} {change} on:change />
