// src/components/fbTableCell.tsx
import React from 'react';

interface fbTableCellProps extends React.TdHTMLAttributes<HTMLTableCellElement> {
  children: React.ReactNode;
}

export const fbTableCell: React.FC<fbTableCellProps> = ({
  children,
  className = '',
  style,
  ...props
}) => {
  return (
    <td
      className={`bg-white hover:bg-[#ffffcc] focus-within:bg-[#ffffcc] transition-colors ${className}`}
      style={{
        padding: '0.4rem',
        borderBottom: '1px solid silver',
        verticalAlign: 'top',
        ...style
      }}
      {...props}
    >
      {children}
    </td>
  );
};

// svelte/src/components/fbTableCell.svelte
<script lang="ts">
  export let width = '';
  export let style = '';
  export let className = '';
</script>

<td class={className} style={`${width ? `width: ${width}; ` : ''}${style}`} {...$$restProps}><slot /></td>

<style>
  td {
    padding: 0.4rem;
    border-bottom: 0.1rem solid silver;
    vertical-align: top;
    background: white;
    transition: background-color 0.2s ease;
  }

  td:hover,
  td:focus-within {
    background: #ffffcc;
  }
</style>
