// reactOrig/src/components/fbButtonSmaller.tsx
import * as React from 'react';

interface fbButtonSmallerProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  children: React.ReactNode;
}

export const fbButtonSmaller: React.FC<fbButtonSmallerProps> = ({
  children,
  style,
  ...props
}) => (
  <button
    type="button"
    style={{
      height: 'auto',
      lineHeight: 'normal',
      padding: '0.15rem 0.45rem',
      fontFamily: "'Roboto', sans-serif",
      fontSize: '0.85rem',
      fontWeight: 500,
      border: '0.1rem solid #1b6ec2',
      borderRadius: '0.25rem',
      backgroundColor: '#1b6ec2',
      color: 'white',
      cursor: props.disabled ? 'not-allowed' : 'pointer',
      opacity: props.disabled ? 0.6 : 1,
      ...style,
    }}
    {...props}
  >
    {children}
  </button>
);

// svelteOrig/src/components/fbButtonSmaller.svelte
<script lang="ts">
  export let type: 'button' | 'submit' = 'button';
  export let disabled = false;
  export let onClick: () => void = () => {};
</script>

<button {type} {disabled} onclick={onClick}>
  <slot />
</button>

<style>
  button {
    height: auto;
    line-height: normal;
    padding: 0.15rem 0.45rem;
    border: 0.1rem solid #1b6ec2;
    border-radius: 0.25rem;
    background: #1b6ec2;
    color: white;
    font-family: 'Roboto', sans-serif;
    font-size: 0.85rem;
    font-weight: 500;
    cursor: pointer;
  }

  button:disabled {
    cursor: not-allowed;
    opacity: 0.6;
  }
</style>
