// svelte/src/pages/PatientSearch.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import FbAddressograph from '../components/fbAddressograph.svelte';
  import FbButton from '../components/fbButton.svelte';
  import FbSearchInput from '../components/fbSearchInput.svelte';
  import FbUserName from '../components/fbUserName.svelte';
  import PatientRecord from './PatientRecord.svelte';
  import { searchPatients } from '../lib/api';
  import type { Patient } from '../lib/types';

  let patients: Patient[] = [];
  let loading = false;
  let activePatientUuid: string | null = null;
  let searchQuery = '';
  let username = 'demoUser';
  let querySerial = 0;

  onMount(() => {
    sessionStorage.setItem('fb_prev_main_page', '/patient-search');
  });

  async function runSearch(nextQuery: string) {
    searchQuery = nextQuery;
    const trimmed = nextQuery.trim();
    if (!trimmed) {
      patients = [];
      loading = false;
      querySerial += 1;
      return;
    }
    const current = ++querySerial;
    patients = [];
    loading = true;
    try {
      const data = await searchPatients(trimmed);
      if (current === querySerial) patients = data || [];
    } catch (error) {
      if (current === querySerial) {
        console.error('Fuzzy search query failed:', error);
        patients = [];
      }
    } finally {
      if (current === querySerial) loading = false;
    }
  }
</script>

{#if activePatientUuid}
  <PatientRecord inline patientUuid={activePatientUuid} bind:username onClose={() => (activePatientUuid = null)} />
{:else}
  <main class="patient-list-page">
    <header class="patient-search-header">
      <button type="button" class="patient-list-title" onclick={() => (window.location.href = 'index.html')}>Patient search</button>
      <FbSearchInput id="patient-search-query-input" label="Search for" bind:value={searchQuery} placeholder="Type to search patient index" autoFocus onChange={runSearch} />
    </header>
    <section class="patient-list-main" aria-label="Patient search results">
      {#if loading}
        <div class="patient-list-muted">Querying clinical registry...</div>
      {:else if patients.length === 0}
        {#if searchQuery.trim()}<div class="patient-list-muted italic">No matches found</div>{/if}
      {:else}
        <table class="patient-list-table">
          <tbody>
            {#each patients as patient (patient.uuid)}
              <tr>
                <td>
                  <div class="patient-list-row">
                    <button type="button" class="patient-addressograph-button" onclick={() => (activePatientUuid = patient.uuid)}>
                      <FbAddressograph
                        nhsNumber={patient.nhs_number || ''}
                        surname={patient.surname || ''}
                        forenames={patient.forenames || ''}
                        title={patient.title || ''}
                        addressLine1={patient.address_line1 || ''}
                        addressLine2={patient.address_line2 || ''}
                        addressLine3={patient.address_line3 || ''}
                        addressLine4={patient.address_line4 || ''}
                        crn={patient.crn || ''}
                        dateOfBirth={patient.date_of_birth || ''}
                        sex={patient.sex || ''}
                      />
                    </button>
                    <div class="patient-list-open"><FbButton type="button" onClick={() => (activePatientUuid = patient.uuid)}>Open record</FbButton></div>
                  </div>
                </td>
              </tr>
            {/each}
          </tbody>
        </table>
      {/if}
    </section>
    <footer class="patient-list-footer">
      <FbUserName bind:value={username} />
      <FbButton type="button" onClick={() => (window.location.href = 'index.html')}>Back</FbButton>
    </footer>
  </main>
{/if}

<style>
  .patient-list-page {
    height: 100vh;
    display: flex;
    flex-direction: column;
    background: white;
  }

  .patient-search-header {
    display: flex;
    flex-direction: column;
    gap: 0.8rem;
    padding: 0.8rem;
    border-bottom: 0.2rem solid var(--fb-blue);
    background: white;
  }

  .patient-list-title {
    border: 0;
    background: transparent;
    color: #333;
    cursor: pointer;
    font-size: 1.8rem;
    font-weight: 700;
    line-height: 2.2rem;
    margin: 0;
    padding: 0;
    text-align: left;
  }

  .patient-list-main {
    flex: 1;
    overflow-y: auto;
    padding: 1.5rem;
  }

  .patient-list-muted {
    color: #666;
    font-size: 1rem;
    font-weight: 300;
  }

  .italic {
    font-style: italic;
  }

  .patient-list-table {
    width: 100%;
    border-collapse: collapse;
    background: white;
  }

  td {
    padding: 0.8rem 0;
    border-bottom: 0.1rem solid #e2e8f0;
  }

  .patient-list-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 1rem;
    width: 100%;
  }

  .patient-addressograph-button {
    display: inline-block;
    border: 0;
    background: transparent;
    cursor: pointer;
    padding: 0;
  }

  .patient-addressograph-button:hover :global(.fb-addressograph-card),
  .patient-addressograph-button:focus :global(.fb-addressograph-card) {
    box-shadow: 0 0.2rem 0.5rem rgb(0 0 0 / 8%);
    transform: scale(1.01);
  }

  .patient-list-open {
    padding-right: 1rem;
  }

  .patient-list-footer {
    display: flex;
    align-items: center;
    justify-content: flex-end;
    gap: 0.8rem;
    min-height: 2.8rem;
    padding: 0.4rem 0.8rem;
    border-top: 0.2rem solid var(--fb-blue);
    background: white;
    box-sizing: border-box;
  }
</style>

// src/PatientSearch.tsx
import * as React from 'react';
import { useNavigate } from 'react-router';
import { fbAddressograph as Addressograph } from './components/fbAddressograph';
import { fbButton as FbButton } from './components/fbButton';
import { fbUserName as FbUserName } from './components/fbUserName';
import { fbSearchInput as FbSearchInput } from './components/fbSearchInput';
import { createClient } from './restClient';
import PatientRecord from './PatientRecord';

const restClient = createClient();

interface Patient {
  uuid: string;
  nhs_number: string;
  surname: string;
  forenames: string;
  title: string;
  address_line1: string;
  address_line2: string;
  address_line3: string;
  address_line4: string;
  crn: string;
  date_of_birth: string;
  sex: string;
}

export default function PatientSearch() {
  const navigate = useNavigate();

  const [patients, setPatients] = React.useState<Patient[]>([]);
  const [loading, setLoading] = React.useState<boolean>(false);
  const [activePatientUuid, setActivePatientUuid] = React.useState<string | null>(null);
  const [searchQuery, setSearchQuery] = React.useState<string>('');

  const queryRef = React.useRef<number>(0);
  const [username, setUsername] = React.useState<string>('demoUser');

  React.useEffect(() => {
    sessionStorage.setItem('fb_prev_main_page', '/patient-search');
  }, []);

  const handleUsernameChange = (val: string) => {
    setUsername(val);
  };

  React.useEffect(() => {
    // 1. When the page is first opened, or when the search query is empty,
    // the list should be empty and the database should not be queried.
    if (!searchQuery.trim()) {
      setPatients([]);
      setLoading(false);
      return;
    }

    // 2. When query changes, clear results of previous searches immediately,
    // and ignore earlier pending queries
    setPatients([]);
    setLoading(true);

    const currentQueryId = ++queryRef.current;

    const performSearch = async () => {
      try {
        const { data, error } = await restClient.rpc('search_patients_fuzzy', {
          search_term: searchQuery
        });

        // 3. When query returns (and a more recent query has not been sent), display matches
        if (currentQueryId === queryRef.current) {
          if (error) {
            console.error('Fuzzy search query failed:', error);
          } else {
            setPatients(data || []);
          }
          setLoading(false);
        }
      } catch (err) {
        if (currentQueryId === queryRef.current) {
          console.error('Fuzzy search execution failed:', err);
          setLoading(false);
        }
      }
    };

    performSearch();
  }, [searchQuery]);

  const handleOpenRecord = (patientUuid: string) => {
    setActivePatientUuid(patientUuid);
  };

  return (
    <>
      {/* Search UI container - visibility is toggled by setting style.display */}
      <div
        id="patient-search-container"
        style={{
          height: '100vh',
          display: activePatientUuid ? 'none' : 'flex',
          flexDirection: 'column',
          fontFamily: "'Roboto', sans-serif",
          backgroundColor: 'white'
        }}
      >
        {/* Top Banner section with wide full-width Search for input inside the header */}
        <div style={{
          backgroundColor: 'white',
          borderBottom: '0.2rem solid rgb(27, 110, 194)',
          padding: '0.8rem',
          boxSizing: 'border-box',
          display: 'flex',
          flexDirection: 'column',
          gap: '0.8rem'
        }} className="flex-shrink-0">
          <div style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between'
          }}>
            <h1
              style={{
                fontFamily: "'Roboto', sans-serif",
                fontSize: '1.8rem',
                fontWeight: 700,
                color: '#333',
                margin: 0,
                lineHeight: '2.2rem',
                cursor: 'pointer'
              }}
              onClick={() => navigate('/')}
            >
              Patient search
            </h1>
          </div>
          
          <div style={{ width: '100%' }}>
            <FbSearchInput
              label="Search for"
              value={searchQuery}
              onChange={setSearchQuery}
              placeholder="Type to search patient index"
              id="patient-search-query-input"
              autoFocus
            />
          </div>
        </div>

        {/* Main content container */}
        <div style={{
          flex: 1,
          padding: '1.5rem',
          overflowY: 'auto'
        }}>

          {!searchQuery.trim() ? null : loading ? (
            <div style={{ fontSize: '1.1rem', color: '#666' }}>Querying clinical registry...</div>
          ) : patients.length === 0 ? (
            <div style={{
              fontFamily: "'Roboto', sans-serif",
              fontSize: '1rem',
              fontWeight: 300,
              fontStyle: 'italic',
              color: '#666'
            }}>
              No matches found
            </div>
          ) : (
            <table style={{
              width: '100%',
              borderCollapse: 'collapse',
              backgroundColor: 'white'
            }}>
              <tbody>
                {patients.map((pat) => (
                  <tr
                    key={pat.uuid}
                    style={{
                      borderBottom: '0.1rem solid #e2e8f0'
                    }}
                  >
                    <td style={{ padding: '0.8rem 0' }}>
                      <div style={{
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                        width: '100%'
                      }}>
                        <div
                          className="fb-addressograph-wrapper"
                          onClick={() => handleOpenRecord(pat.uuid)}
                          style={{
                            display: 'inline-block',
                            cursor: 'pointer'
                          }}
                          onMouseEnter={(e) => {
                            const card = e.currentTarget.querySelector('.fb-addressograph-card');
                            if (card) {
                              (card as HTMLElement).style.transform = 'scale(1.01)';
                              (card as HTMLElement).style.boxShadow = '0 0.2rem 0.5rem rgba(0,0,0,0.08)';
                            }
                          }}
                          onMouseLeave={(e) => {
                            const card = e.currentTarget.querySelector('.fb-addressograph-card');
                            if (card) {
                              (card as HTMLElement).style.transform = 'none';
                              (card as HTMLElement).style.boxShadow = 'none';
                            }
                          }}
                        >
                          <Addressograph
                            nhsNumber={pat.nhs_number}
                            surname={pat.surname}
                            forenames={pat.forenames}
                            title={pat.title}
                            addressLine1={pat.address_line1}
                            addressLine2={pat.address_line2}
                            addressLine3={pat.address_line3}
                            addressLine4={pat.address_line4}
                            crn={pat.crn}
                            dateOfBirth={pat.date_of_birth}
                            sex={pat.sex}
                          />
                        </div>
                        <div style={{ paddingRight: '1rem' }}>
                          <FbButton
                            variant="primary"
                            onClick={() => handleOpenRecord(pat.uuid)}
                            id={`open-record-${pat.uuid}`}
                          >
                            Open record
                          </FbButton>
                        </div>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}

        </div>

        {/* Footer Area with right-aligned userName input and blue/white Back button */}
        <div
          className="bottom-control-bar"
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'flex-end',
            gap: '0.8rem',
            padding: '0.4rem 0.8rem',
            backgroundColor: 'white',
            borderTop: '0.2rem solid rgb(27, 110, 194)',
            minHeight: '2.8rem',
            boxSizing: 'border-box'
          }}
        >
          <div>
            <FbUserName
              value={username}
              onChange={handleUsernameChange}
            />
          </div>
          <div>
            <FbButton variant="primary" onClick={() => navigate('/')}>
              Back
            </FbButton>
          </div>
        </div>
      </div>

      {/* Conditionally render PatientRecord to remove/add it from the DOM */}
      {activePatientUuid && (
        <PatientRecord
          inline
          patientUuid={activePatientUuid}
          username={username}
          onClose={() => setActivePatientUuid(null)}
        />
      )}
    </>
  );
}
