// svelte/src/pages/PatientRecord.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import FbAddressograph from '../components/fbAddressograph.svelte';
  import FbAddButtonForPage from '../components/fbAddButtonForPage.svelte';
  import FbAddFormMenu from '../components/fbAddFormMenu.svelte';
  import FbButton from '../components/fbButton.svelte';
  import FbDraftBadge from '../components/fbBadgeDraft.svelte';
  import FbFormTile from '../components/fbFormTile.svelte';
  import FbOutpatientAppointmentTile from '../components/fbOutpatientAppointmentTile.svelte';
  import FbUserName from '../components/fbUserName.svelte';
  import OperationNote from './OperationNote.svelte';
  import OutpatientOutcome from './OutpatientOutcome.svelte';
  import TreatmentSummary from './TreatmentSummary.svelte';
  import WaitingListCard from './WaitingListCard.svelte';
  import CardiologyTestRequest from './CardiologyTestRequest.svelte';
  import { getPatient, getPatientAppointments, getPatientForms } from '../lib/api';
  import { specialityLabels } from '../lib/constants';
  import type { Patient } from '../lib/types';

  export let patientUuid = new URLSearchParams(window.location.search).get('patientUuid') || sessionStorage.getItem('fb_prev_patient_uuid') || 'fd55880a-7ada-47a8-adbb-65850af6f7e2';
  export let inline = false;
  export let username = 'demoUser';
  export let onClose: () => void = () => {};

  type FormIndexItem = {
    form_uuid: string;
    form_version?: number;
    form_type: string;
    patient_uuid: string;
    event_datetime: string;
    document_datetime?: string | null;
    form_status: string;
    speciality?: string;
    senior_responsible_clinician?: string;
  };

  let patient: Patient | null = null;
  let forms: FormIndexItem[] = [];
  let appointments: any[] = [];
  let loading = true;
  let showAddMenu = false;
  let inlineActiveForm: {
    formType: 'waiting_list_card' | 'operation_note' | 'outpatient_outcome' | 'treatment_summary' | 'cardiology_test_request';
    formUuid?: string;
    appointmentUuid?: string;
    openInRoV?: boolean;
  } | null = null;

  onMount(() => {
    sessionStorage.setItem('fb_prev_main_page', '/patient-record');
    sessionStorage.setItem('fb_prev_patient_uuid', patientUuid);
    void fetchPatientRecord();
  });

  async function fetchPatientRecord() {
    loading = true;
    try {
      const [patientData, formData, appointmentData] = await Promise.all([
        getPatient(patientUuid),
        getPatientForms(patientUuid),
        getPatientAppointments(patientUuid),
      ]);
      patient = patientData;
      forms = formData || [];
      appointments = appointmentData || [];
    } catch (error) {
      console.error('Error fetching patient record:', error);
      forms = [];
      appointments = [];
    } finally {
      loading = false;
    }
  }

  function closeRecord() {
    if (inline) onClose();
    else window.location.href = 'index.html';
  }

  function closeInlineForm() {
    inlineActiveForm = null;
    void fetchPatientRecord();
  }

  function formTypeDisplay(type: string) {
    if (type === 'waiting_list_card') return 'Waiting list card';
    if (type === 'operation_note') return 'Operation note';
    if (type === 'outpatient_outcome') return 'Outpatient outcome';
    if (type === 'treatment_summary') return 'Treatment summary';
    if (type === 'cardiology_test_request') return 'Cardiology test request';
    if (type === 'outpatient_appointment') return 'Outpatient appointment';
    return type;
  }

  function formTypeHref(type: string) {
    if (type === 'waiting_list_card') return 'waitingListCard.html';
    if (type === 'operation_note') return 'operationNote.html';
    if (type === 'outpatient_outcome') return 'outpatientOutcome.html';
    if (type === 'treatment_summary') return 'treatmentSummary.html';
    if (type === 'cardiology_test_request') return 'cardiologyTestRequest.html';
    return '';
  }

  function openForm(form: FormIndexItem) {
    const href = formTypeHref(form.form_type);
    if (!href) return;
    inlineActiveForm = {
      formType: form.form_type as any,
      formUuid: form.form_uuid,
      openInRoV: true,
    };
  }

  function openAppointmentOutcome(form: FormIndexItem) {
    const appt = appointments.find((item) => item.uuid === form.form_uuid);
    const outcomeUuid = appt?.outcome_form_uuid;
    if (outcomeUuid) {
      const matchingForm = forms.find((item) => item.form_uuid === outcomeUuid);
      inlineActiveForm = {
        formType: 'outpatient_outcome',
        formUuid: outcomeUuid,
        openInRoV: matchingForm?.form_status === 'final',
      };
    } else {
      inlineActiveForm = {
        formType: 'outpatient_outcome',
        appointmentUuid: form.form_uuid,
        openInRoV: false,
      };
    }
  }

  function addNewForm(type: string) {
    showAddMenu = false;
    const mapped = type === 'waiting_list' ? 'waiting_list_card' : type;
    const href = formTypeHref(mapped);
    if (href) {
      inlineActiveForm = {
        formType: mapped as any,
        openInRoV: false,
      };
    }
  }

  function formatDateTime(value?: string | null) {
    if (!value) return '';
    const date = new Date(value);
    if (Number.isNaN(date.getTime())) return value;
    const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    const day = String(date.getDate()).padStart(2, '0');
    const month = monthNames[date.getMonth()];
    const year = date.getFullYear();
    const hours = String(date.getHours()).padStart(2, '0');
    const minutes = String(date.getMinutes()).padStart(2, '0');
    return `${day}-${month}-${year} ${hours}:${minutes}`;
  }

  function specialityDisplay(value?: string) {
    if (!value) return '';
    return specialityLabels[value] || specialityLabels[value.toLowerCase()] || value;
  }

  function appointmentFor(form: FormIndexItem) {
    return appointments.find((item) => item.uuid === form.form_uuid);
  }

  function isFutureAppointment(form: FormIndexItem) {
    return form.form_type === 'outpatient_appointment' && new Date(form.event_datetime) > new Date();
  }

  function needsOutcome(form: FormIndexItem) {
    const appt = appointmentFor(form);
    const matchingForm = forms.find((item) => item.form_uuid === appt?.outcome_form_uuid);
    return form.form_type === 'outpatient_appointment' && !isFutureAppointment(form) && matchingForm?.form_status !== 'final';
  }
</script>

{#if inlineActiveForm}
  <div class="patient-record-inline-form">
    {#if inlineActiveForm.formType === 'waiting_list_card'}
      <WaitingListCard {patientUuid} formUuid={inlineActiveForm.formUuid || ''} openInRoV={!!inlineActiveForm.openInRoV} inline onClose={closeInlineForm} />
    {:else if inlineActiveForm.formType === 'operation_note'}
      <OperationNote {patientUuid} formUuid={inlineActiveForm.formUuid || ''} openInRoV={!!inlineActiveForm.openInRoV} inline onClose={closeInlineForm} />
    {:else if inlineActiveForm.formType === 'outpatient_outcome'}
      <OutpatientOutcome {patientUuid} formUuid={inlineActiveForm.formUuid || ''} appointmentUuid={inlineActiveForm.appointmentUuid || ''} openInRoV={!!inlineActiveForm.openInRoV} inline onClose={closeInlineForm} />
    {:else if inlineActiveForm.formType === 'treatment_summary'}
      <TreatmentSummary {patientUuid} formUuid={inlineActiveForm.formUuid || ''} openInRoV={!!inlineActiveForm.openInRoV} inline onClose={closeInlineForm} />
    {:else if inlineActiveForm.formType === 'cardiology_test_request'}
      <CardiologyTestRequest {patientUuid} formUuid={inlineActiveForm.formUuid || ''} openInRoV={!!inlineActiveForm.openInRoV} inline onClose={closeInlineForm} />
    {/if}
  </div>
{:else}
<main class="patient-record-page">
  <header class="patient-record-header">
    <button type="button" class="patient-record-title" onclick={() => (window.location.href = 'index.html')}>Patient record</button>
    <div class="patient-record-spacer"></div>
    {#if patient}
      <FbAddressograph
        nhsNumber={patient.nhs_number || ''}
        surname={patient.surname || ''}
        forenames={patient.forenames || ''}
        title={patient.title || ''}
        addressLine1={patient.address_line1 || ''}
        addressLine2={patient.address_line2 || ''}
        addressLine3={patient.address_line3 || ''}
        addressLine4={patient.address_line4 || ''}
        crn={patient.crn || ''}
        dateOfBirth={patient.date_of_birth || ''}
        sex={patient.sex || ''}
      />
    {:else}
      <FbAddressograph />
    {/if}
  </header>

  <section class="patient-record-main" aria-label="Patient documents">
    {#if loading}
      <div class="patient-record-muted">Loading forms...</div>
    {:else if forms.length === 0}
      <div class="patient-record-muted italic">No forms recorded for this patient yet. Use the button in the bottom left corner to add a form.</div>
    {:else}
      <div class="patient-record-list">
        {#each forms as form, index (`${form.form_uuid}-${form.form_version ?? index}`)}
          <div class="patient-record-row">
            <div class="patient-record-badge">
              {#if form.form_type === 'outpatient_appointment'}
                {#if isFutureAppointment(form)}
                  <div class="patient-record-badge-box future">Future appt</div>
                {:else if needsOutcome(form)}
                  <div class="patient-record-badge-box overdue">Not outcomed</div>
                {/if}
              {:else if form.form_status === 'draft'}
                <FbDraftBadge />
              {/if}
              {#if form.highly_sensitive || form.form_data?.highlySensitive}
                <span class="patient-record-sensitive-badge">Highly sensitive</span>
              {/if}
            </div>
            <div>
              {#if form.form_type === 'outpatient_appointment'}
                <FbOutpatientAppointmentTile
                  dateTime={formatDateTime(form.event_datetime)}
                  clinicName={appointmentFor(form)?.clinic_name || ''}
                  speciality={specialityDisplay(form.speciality)}
                  src={form.senior_responsible_clinician || ''}
                />
              {:else}
                <FbFormTile
                  dateTime={formatDateTime(form.document_datetime || form.event_datetime)}
                  formTypeName={formTypeDisplay(form.form_type)}
                  speciality={specialityDisplay(form.speciality)}
                  src={form.senior_responsible_clinician || ''}
                />
              {/if}
            </div>
            <div class="patient-record-row-button">
              {#if form.form_type === 'outpatient_appointment'}
                {#if !isFutureAppointment(form)}
                  <FbButton type="button" onClick={() => openAppointmentOutcome(form)}>Outcome form</FbButton>
                {/if}
              {:else}
                <FbButton type="button" onClick={() => openForm(form)}>Open</FbButton>
              {/if}
            </div>
          </div>
        {/each}
      </div>
    {/if}
  </section>

  <footer class="patient-record-footer">
    <div class="patient-record-add-wrap">
      <FbAddButtonForPage id="new-form-document-button" label="New form or document" onClick={() => (showAddMenu = !showAddMenu)} />
      {#if showAddMenu}
        <FbAddFormMenu onSelectFormType={addNewForm} onCancel={() => (showAddMenu = false)} />
      {/if}
    </div>
    <div class="patient-record-footer-right">
      <FbUserName bind:value={username} />
      <FbButton type="button" onClick={closeRecord}>Close</FbButton>
    </div>
  </footer>
</main>
{/if}

<style>
  .patient-record-page {
    height: 100vh;
    display: flex;
    flex-direction: column;
    background: white;
  }

  .patient-record-inline-form {
    height: 100vh;
    overflow: hidden;
  }

  .patient-record-header {
    display: flex;
    align-items: center;
    gap: 1rem;
    padding: 0.4rem;
    border-bottom: 0.2rem solid var(--fb-blue);
    background: white;
    flex: 0 0 auto;
  }

  .patient-record-title {
    border: 0;
    background: transparent;
    color: black;
    cursor: pointer;
    font-size: 2rem;
    font-weight: 500;
    margin: 0;
    padding: 0;
  }

  .patient-record-spacer {
    flex: 1;
  }

  .patient-record-main {
    flex: 1;
    overflow-y: auto;
    padding: 1.5rem;
  }

  .patient-record-muted {
    color: #666;
    font-size: 1.1rem;
  }

  .italic {
    font-style: italic;
  }

  .patient-record-list {
    display: flex;
    flex-direction: column;
  }

  .patient-record-row {
    display: grid;
    grid-template-columns: 170px 1fr auto;
    align-items: start;
    gap: 1.5rem;
    padding: 0.2rem 0;
    border-bottom: 0.1rem solid silver;
  }

  .patient-record-badge {
    display: flex;
    align-items: start;
    justify-content: flex-start;
    gap: 0.4rem;
    flex-wrap: wrap;
  }

  .patient-record-badge-box {
    display: inline-block;
    padding: 0.2rem 0.4rem;
    color: white;
    font-size: 1rem;
    font-weight: 700;
    line-height: 1.2;
  }

  .patient-record-sensitive-badge {
    display: inline-block;
    padding: 0.2rem 0.4rem;
    background: var(--fb-red);
    color: white;
    font-size: 1rem;
    font-weight: 700;
    line-height: 1.2;
  }

  .future {
    background: #2e7d32;
  }

  .overdue {
    background: var(--fb-red);
  }

  .patient-record-row-button {
    min-width: 8rem;
    text-align: right;
  }

  .patient-record-footer {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 0.8rem;
    min-height: 2.8rem;
    padding: 0.4rem 0.8rem;
    border-top: 0.2rem solid var(--fb-blue);
    background: white;
    box-sizing: border-box;
  }

  .patient-record-add-wrap {
    position: relative;
  }

  .patient-record-footer-right {
    display: flex;
    align-items: center;
    gap: 0.8rem;
  }

  @media (max-width: 767px) {
    .patient-record-header {
      align-items: flex-start;
      flex-direction: column;
    }

    .patient-record-row {
      grid-template-columns: 1fr;
      gap: 0.4rem;
    }

    .patient-record-row-button {
      text-align: left;
    }
  }
</style>

// src/PatientRecord.tsx
import * as React from 'react';
import { useNavigate, useLocation } from 'react-router';
import { fbAddressograph as Addressograph } from './components/fbAddressograph';
import { fbAddFormMenu as AddFormMenu } from './components/fbAddFormMenu';
import { fbButton as FbButton } from './components/fbButton';
import { fbUserName as FbUserName } from './components/fbUserName';
import { fbOutpatientAppointmentTile as OutpatientAppointmentTile } from './components/fbOutpatientAppointmentTile';
import { fbFormTile as FormTile } from './components/fbFormTile';
import { fbBadgeDraft as DraftBadge } from './components/fbBadgeDraft';
import { fbAddButtonForPage as AddButtonForPage } from './components/fbAddButtonForPage';
import WaitingListCard from './WaitingListCard';
import OperationNote from './OperationNote';
import OutpatientOutcome from './OutpatientOutcome';
import TreatmentSummary from './TreatmentSummary';
import CardiologyTestRequest from './etr/CardiologyTestRequest';
import { specialities } from './data/specialities';
import { createClient } from './restClient';
import { popCntNavigation } from './caseNoteTracker/cntNavigation';
import { fbBadgeHighlySensitive as HighlySensitiveBadge } from './components/fbBadgeHighlySensitive';

// Create REST client
const restClient = createClient();
const DONALD_DUCK_PATIENT_UUID = 'fd55880a-7ada-47a8-adbb-65850af6f7e2';

interface Patient {
  uuid: string;
  nhs_number: string;
  surname: string;
  forenames: string;
  title: string;
  address_line1: string;
  address_line2: string;
  address_line3: string;
  address_line4: string;
  crn: string;
  date_of_birth: string;
  sex: string;
}

interface FormIndexItem {
  form_uuid: string;
  form_version: number;
  form_type: string;
  patient_uuid: string;
  event_datetime: string;
  document_datetime: string | null;
  form_status: string;
  event_or_document?: 'Event' | 'Document';
  details?: string;
  speciality?: string;
  organisation?: string;
  hospital?: string;
  senior_responsible_clinician?: string;
  highly_sensitive?: boolean;
}

interface PatientRecordProps {
  patientUuid?: string;
  username?: string;
  onClose?: () => void;
  inline?: boolean;
}

export default function PatientRecord({
  patientUuid: propPatientUuid,
  username: propUsername,
  onClose,
  inline = false
}: PatientRecordProps = {}) {
  const navigate = useNavigate();
  const location = useLocation();

  const [patient, setPatient] = React.useState<Patient | null>(null);
  const [forms, setForms] = React.useState<FormIndexItem[]>([]);
  const [appointments, setAppointments] = React.useState<any[]>([]);
  const [loading, setLoading] = React.useState<boolean>(true);
  const [username, setUsername] = React.useState<string>(propUsername || 'demoUser');

  const handleUsernameChange = (val: string) => {
    setUsername(val);
  };

  // State & Ref for the AddFormMenu dropdown (bottom-left AddButton trigger)
  const [showAddMenu, setShowAddMenu] = React.useState<boolean>(false);
  const addButtonRef = React.useRef<HTMLButtonElement>(null);

  // Local state to keep track of actively opened forms/documents inline
  const [inlineActiveForm, setInlineActiveForm] = React.useState<{
    formType: 'waiting_list_card' | 'operation_note' | 'outpatient_outcome' | 'treatment_summary' | 'cardiology_test_request';
    formUuid?: string;
    appointmentUuid?: string;
    openInRoV?: boolean;
  } | null>(null);

  // Parse location state to see if patientUuid was passed
  const state = location.state as { patientUuid?: string; from?: string } | null;
  const queryPatientUuid = new URLSearchParams(location.search || '').get('patientUuid') || '';
  const bridgedPatientUuid = sessionStorage.getItem('fbcntPatientRecordPatientUuid') || '';
  const patientUuid = inline ? propPatientUuid : (state?.patientUuid || queryPatientUuid || bridgedPatientUuid || DONALD_DUCK_PATIENT_UUID);

  const fetchPatientAndForms = async (options: { showLoading?: boolean } = {}) => {
    const showLoading = options.showLoading !== false;
    try {
      if (showLoading) {
        setLoading(true);
      }

      // Fetch latest version of patient
      const { data: patientData, error: patientError } = await restClient
        .from('patients')
        .select('*')
        .eq('uuid', patientUuid)
        .order('version', { ascending: false })
        .limit(1)
        .single();

      if (patientError) {
        console.error('Error fetching patient:', patientError);
      } else {
        setPatient(patientData);
      }

      // Fetch forms for patient_uuid via forms_index
      const { data: formIndexData, error: formIndexError } = await restClient
        .from('forms_index_current')
        .select('*')
        .eq('patient_uuid', patientUuid)
        .order('event_datetime', { ascending: false });

      if (formIndexError) {
        console.error('Error fetching form index:', formIndexError);
      } else {
        setForms(formIndexData || []);

        // Lazy/targeted secondary query: Fetch metadata ONLY for the specific appointments found in the main forms list
        const apptUuids = (formIndexData || [])
          .filter(f => f.form_type === 'outpatient_appointment')
          .map(f => f.form_uuid);

        if (apptUuids.length > 0) {
          const { data: apptsData, error: apptsError } = await restClient
            .from('outpatient_appointments')
            .select('*')
            .in('uuid', apptUuids);

          if (apptsError) {
            console.error('Error fetching targeted appointment details:', apptsError);
          } else {
            setAppointments(apptsData || []);
          }
        } else {
          setAppointments([]);
        }
      }

    } catch (err) {
      console.error('Exception fetching patient record data:', err);
    } finally {
      if (showLoading) {
        setLoading(false);
      }
    }
  };

  React.useEffect(() => {
    fetchPatientAndForms();
  }, [patientUuid]);

  React.useEffect(() => {
    sessionStorage.setItem('fb_prev_main_page', '/patient-record');
    if (patientUuid) {
      sessionStorage.setItem('fb_prev_patient_uuid', patientUuid);
    }
  }, [patientUuid]);

  // Translate form type to display name
  const getFormTypeDisplay = (type: string) => {
    if (type === 'waiting_list_card') return 'Waiting list card';
    if (type === 'operation_note') return 'Operation note';
    if (type === 'outpatient_outcome') return 'Outpatient outcome';
    if (type === 'treatment_summary') return 'Treatment summary';
    if (type === 'cardiology_test_request') return 'Cardiology test request';
    if (type === 'outpatient_appointment') return 'Outpatient appointment';
    return type;
  };

  const handleFormClick = (form: FormIndexItem) => {
    setInlineActiveForm({
      formType: form.form_type as any,
      formUuid: form.form_uuid,
      openInRoV: true // clicking directly on standard record always opens in Read-Only unless otherwise selected
    });
  };

  const handleAppointmentClick = (form: FormIndexItem) => {
    const appt = appointments.find(a => a.uuid === form.form_uuid);
    if (!appt) {
      console.error('Appointment not found:', form.form_uuid);
      return;
    }

    if (appt.outcome_form_uuid) {
      const matchingForm = forms.find(f => f.form_uuid === appt.outcome_form_uuid);
      const isFinal = matchingForm?.form_status === 'final';
      setInlineActiveForm({
        formType: 'outpatient_outcome',
        formUuid: appt.outcome_form_uuid,
        openInRoV: isFinal
      });
    } else {
      setInlineActiveForm({
        formType: 'outpatient_outcome',
        appointmentUuid: appt.uuid,
        openInRoV: false
      });
    }
  };

  const handleAddNewForm = (formType: string) => {
    let resolvedType: any = formType;
    if (formType === 'waiting-list') resolvedType = 'waiting_list_card';
    if (formType === 'operation-note') resolvedType = 'operation_note';
    if (formType === 'outpatient-outcome') resolvedType = 'outpatient_outcome';
    if (formType === 'treatment-summary') resolvedType = 'treatment_summary';
    if (formType === 'cardiology-test-request') resolvedType = 'cardiology_test_request';

    setInlineActiveForm({
      formType: resolvedType,
      openInRoV: false
    });
  };

  const formatDateTime = (isoString: string) => {
    try {
      const date = new Date(isoString);
      const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
      const day = date.getDate().toString().padStart(2, '0');
      const month = monthNames[date.getMonth()];
      const year = date.getFullYear();
      const hours = date.getHours().toString().padStart(2, '0');
      const minutes = date.getMinutes().toString().padStart(2, '0');
      return `${day}-${month}-${year} ${hours}:${minutes}`;
    } catch {
      return isoString;
    }
  };

  const handleClose = () => {
    if (inline && onClose) {
      onClose();
      return;
    }
    const entry = popCntNavigation();
    if (entry?.kind === 'cnt-view') {
      const returnState = sessionStorage.getItem('fbcntReturnState');
      if (returnState) {
        sessionStorage.setItem('fbcntRestoreState', returnState);
        sessionStorage.removeItem('fbcntReturnState');
      } else if (entry.view) {
        sessionStorage.setItem('fbcntRestoreState', JSON.stringify({ view: entry.view }));
      }
      window.location.href = '/formBuilder2/caseNoteTracker.html';
      return;
    }
    if (entry?.kind === 'url' && entry.url) {
      window.location.href = entry.url;
      return;
    }
    const fromPath = (location.state as any)?.from || '/';
    navigate(fromPath);
  };

  const getSpecialityDisplay = (specVal?: string) => {
    if (!specVal) return '';
    const found = specialities.find(s => s.value === specVal || s.value.toLowerCase() === specVal.toLowerCase());
    return found ? found.label : specVal;
  };

  const renderBadge = (form: FormIndexItem) => {
    if (form.form_type === 'outpatient_appointment') {
      const appt = appointments.find(a => a.uuid === form.form_uuid);
      const isFuture = new Date(form.event_datetime) > new Date();

      if (isFuture) {
        return (
          <div style={{
            backgroundColor: '#2e7d32', // green
            color: 'white',
            fontWeight: 700,
            padding: '0.2rem 0.4rem',
            fontFamily: "'Roboto', sans-serif",
            fontSize: '1rem',
            display: 'inline-block',
            lineHeight: 1.2
          }}>
            Future appt
          </div>
        );
      } else {
        const outcomeFormUuid = appt?.outcome_form_uuid;
        const matchingFormStatus = forms.find(f => f.form_uuid === outcomeFormUuid)?.form_status;
        const hasFinalOutcome = matchingFormStatus === 'final';

        if (!hasFinalOutcome) {
          return (
            <div style={{
              backgroundColor: '#d50000', // red
              color: 'white',
              fontWeight: 700,
              padding: '0.2rem 0.4rem',
              fontFamily: "'Roboto', sans-serif",
              fontSize: '1rem',
              display: 'inline-block',
              lineHeight: 1.2
            }}>
              Not outcomed
            </div>
          );
        }
      }
      return null;
    }

    if (form.form_status === 'draft' || form.highly_sensitive) {
      return (
        <div style={{ display: 'inline-flex', alignItems: 'center', gap: '0.4rem', flexWrap: 'wrap' }}>
          {form.form_status === 'draft' && <DraftBadge />}
          {form.highly_sensitive && <HighlySensitiveBadge />}
        </div>
      );
    }

    return null;
  };

  return (
    <div style={{
      height: '100vh',
      display: 'flex',
      flexDirection: 'column',
      fontFamily: "'Roboto', sans-serif",
      backgroundColor: 'white'
    }}>

      {/* Main Patient Record Page UI container */}
      <div
        id="patient-record-page-container"
        style={{
          display: inlineActiveForm ? 'none' : 'flex',
          flexDirection: 'column',
          height: '100%',
          overflow: 'hidden'
        }}
      >
        {/* Top Banner section */}
        <div style={{
          borderBottom: '0.2rem solid rgb(27, 110, 194)',
          padding: '0.4rem',
          display: 'flex',
          justifyContent: 'between',
          alignItems: 'center'
        }} className="flex-shrink-0">
          <h1 style={{ fontSize: '2rem', fontWeight: 500, margin: 0, cursor: 'pointer', color: 'black' }} onClick={() => navigate('/')}>
            Patient record
          </h1>
          <div className="flex-1"></div>
          {patient ? (
            <Addressograph
              nhsNumber={patient.nhs_number}
              surname={patient.surname}
              forenames={patient.forenames}
              title={patient.title}
              addressLine1={patient.address_line1}
              addressLine2={patient.address_line2}
              addressLine3={patient.address_line3}
              addressLine4={patient.address_line4}
              crn={patient.crn}
              dateOfBirth={patient.date_of_birth}
              sex={patient.sex}
            />
          ) : (
            <Addressograph />
          )}
        </div>

        {/* List of documents (forms_index) taking full width (no left gray column) */}
        <div style={{
          flex: 1,
          padding: '1.5rem',
          overflowY: 'auto'
        }}>
          {loading ? (
            <div style={{ fontSize: '1.1rem', color: '#666' }}>Loading forms...</div>
          ) : forms.length === 0 ? (
            <div style={{ fontSize: '1.1rem', color: '#666', fontStyle: 'italic' }}>
              No forms recorded for this patient yet. Use the button in the bottom left corner to add a form.
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column' }}>
              {forms.map((form) => {
                const isAppointment = form.form_type === 'outpatient_appointment';
                const appt = isAppointment ? appointments.find(a => a.uuid === form.form_uuid) : null;
                const clinicName = appt?.clinic_name || '';
                const isFutureAppointment = isAppointment && (new Date(form.event_datetime) > new Date());

                return (
                  <div
                    key={form.form_uuid}
                    style={{
                      display: 'grid',
                      gridTemplateColumns: '170px 1fr auto',
                      alignItems: 'start',
                      gap: '1.5rem',
                      borderBottom: '1px solid silver',
                      padding: '0.2rem 0'
                    }}
                  >
                    {/* Column 1: Badge */}
                    <div style={{ display: 'flex', alignItems: 'start', justifyContent: 'flex-start' }}>
                      {renderBadge(form)}
                    </div>

                    {/* Column 2: Custom Tile Component or Form details */}
                    <div>
                      {isAppointment ? (
                        <OutpatientAppointmentTile
                          dateTime={formatDateTime(form.event_datetime)}
                          clinicName={clinicName}
                          speciality={getSpecialityDisplay(form.speciality)}
                          src={form.senior_responsible_clinician || ''}
                        />
                      ) : (
                        <FormTile
                          dateTime={formatDateTime(form.document_datetime || form.event_datetime)}
                          formTypeName={getFormTypeDisplay(form.form_type)}
                          speciality={getSpecialityDisplay(form.speciality)}
                          src={form.senior_responsible_clinician || ''}
                          highlySensitive={!!form.highly_sensitive}
                        />
                      )}
                    </div>

                    {/* Column 3: Blue on White Buttons */}
                    <div>
                      {isAppointment ? (
                        !isFutureAppointment && (
                          <FbButton
                            variant="primary"
                            onClick={() => handleAppointmentClick(form)}
                            id={`outcome-btn-${form.form_uuid}`}
                          >
                            Outcome form
                          </FbButton>
                        )
                      ) : (
                        <FbButton
                          variant="primary"
                          onClick={() => handleFormClick(form)}
                          id={`open-btn-${form.form_uuid}`}
                        >
                          Open
                        </FbButton>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Bottom Control bar */}
        <div
          className="bottom-control-bar"
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: '0.4rem 0.8rem',
            backgroundColor: 'white',
            borderTop: '0.2rem solid rgb(27, 110, 194)',
            minHeight: '2.8rem',
            boxSizing: 'border-box',
            zIndex: 100 // ensure dropdown fits nicely
          }}
        >
          {/* New form / document button in the bottom left corner */}
          <div style={{ position: 'relative' }}>
            <AddButtonForPage
              ref={addButtonRef as any}
              label="New form or document"
              id="new-form-document-button"
              onClick={() => setShowAddMenu(prev => !prev)}
            />
            {showAddMenu && (
              <AddFormMenu
                buttonRef={addButtonRef}
                onSelectFormType={(type) => {
                  setShowAddMenu(false);
                  handleAddNewForm(type);
                }}
                onCancel={() => setShowAddMenu(false)}
              />
            )}
          </div>

          {/* User Name input and Close button in the bottom right corner */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.8rem' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
              <FbUserName
                value={username}
                onChange={handleUsernameChange}
                style={{ width: '10rem' }}
              />
            </div>

            <FbButton variant="primary" onClick={handleClose} id="patient-record-close-button">
              Close
            </FbButton>
          </div>
        </div>

      </div>

      {/* Render selected active form inline if present and hide parent container */}
      {inlineActiveForm && (
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', height: '100vh', overflow: 'hidden' }}>
          {inlineActiveForm.formType === 'waiting_list_card' && (
            <WaitingListCard
              inlineProps={{
                patientUuid: patient?.uuid,
                formUuid: inlineActiveForm.formUuid,
                openInRoV: inlineActiveForm.openInRoV,
                onClose: () => {
                  setInlineActiveForm(null);
                  fetchPatientAndForms({ showLoading: false });
                }
              }}
            />
          )}
          {inlineActiveForm.formType === 'operation_note' && (
            <OperationNote
              inlineProps={{
                patientUuid: patient?.uuid,
                formUuid: inlineActiveForm.formUuid,
                openInRoV: inlineActiveForm.openInRoV,
                onClose: () => {
                  setInlineActiveForm(null);
                  fetchPatientAndForms({ showLoading: false });
                }
              }}
            />
          )}
          {inlineActiveForm.formType === 'outpatient_outcome' && (
            <OutpatientOutcome
              inlineProps={{
                patientUuid: patient?.uuid,
                formUuid: inlineActiveForm.formUuid,
                appointmentUuid: inlineActiveForm.appointmentUuid,
                openInRoV: inlineActiveForm.openInRoV,
                onClose: () => {
                  setInlineActiveForm(null);
                  fetchPatientAndForms({ showLoading: false });
                }
              }}
            />
          )}
          {inlineActiveForm.formType === 'treatment_summary' && (
            <TreatmentSummary
              inlineProps={{
                patientUuid: patient?.uuid,
                formUuid: inlineActiveForm.formUuid,
                openInRoV: inlineActiveForm.openInRoV,
                onClose: () => {
                  setInlineActiveForm(null);
                  fetchPatientAndForms({ showLoading: false });
                }
              }}
            />
          )}
          {inlineActiveForm.formType === 'cardiology_test_request' && (
            <CardiologyTestRequest
              inlineProps={{
                patientUuid: patient?.uuid,
                formUuid: inlineActiveForm.formUuid,
                openInRoV: inlineActiveForm.openInRoV,
                onClose: () => {
                  setInlineActiveForm(null);
                  fetchPatientAndForms({ showLoading: false });
                }
              }}
            />
          )}
        </div>
      )}

    </div>
  );
}
