// src/routes/patient-registry/+page.svelte
<script lang="ts">
  import { base } from '$app/paths';
  import FbAddressograph from '$lib/components/fb/fbAddressograph.svelte';
  import FbButton from '$lib/components/fb/fbButton.svelte';
  import FbUserName from '$lib/components/fb/fbUserName.svelte';
  import type { Patient } from '$lib/types';
  import { openHrefWithReturn, returnByHref } from '$lib/utils/fbHrefNavigation';

  type PageData = {
    patients: Patient[];
    loadError: string;
  };

  let { data }: { data: PageData } = $props();
  let username = $state('demoUser');

  const patients = $derived(data.patients || []);

  $effect(() => {
    sessionStorage.setItem('fb_prev_main_page', `${base}/patient-registry`);
  });

  function openRecord(patientUuid: string) {
    openHrefWithReturn(`${base}/patient-record/${encodeURIComponent(patientUuid)}?username=${encodeURIComponent(username)}`);
  }

  function openCaseNotes(patient: Patient) {
    sessionStorage.setItem('fbcntUserUuid', 'bbbbbbbb-0005-4000-8000-000000000005');
    sessionStorage.setItem('fbcntInitialPatient', JSON.stringify(toCntPatient(patient)));
    openHrefWithReturn(`${base}/cnt?patientUuid=${encodeURIComponent(patient.uuid)}&loginAs=bbbbbbbb-0005-4000-8000-000000000005`);
  }

  function toCntPatient(patient: Patient) {
    return {
      uuid: patient.uuid,
      nhsNumber: patient.nhs_number || '',
      hospitalNumber: patient.hospital_number || patient.uuid.slice(0, 8),
      name: `${patient.forenames || ''} ${patient.surname || ''}`.trim(),
      title: patient.title || '',
      surname: patient.surname || '',
      forenames: patient.forenames || '',
      addressLine1: patient.address_line1 || '',
      addressLine2: patient.address_line2 || '',
      addressLine3: patient.address_line3 || '',
      addressLine4: patient.address_line4 || '',
      dateOfBirth: patient.date_of_birth || '',
      sex: patient.sex || '',
    };
  }
</script>

<main class="patient-list-page">
  <header class="patient-list-header">
    <a class="patient-list-title" href={`${base}/`}>Patient registry</a>
  </header>

  <section class="patient-list-main" aria-label="Patient registry">
    {#if data.loadError}
      <div class="patient-list-muted" role="alert">{data.loadError}</div>
    {:else if patients.length === 0}
      <div class="patient-list-muted italic">No patients found.</div>
    {:else}
      <table class="patient-list-table">
        <tbody>
          {#each patients as patient (patient.uuid)}
            <tr>
              <td>
                <div class="patient-list-row">
                  <button type="button" class="patient-addressograph-button" onclick={() => openRecord(patient.uuid)}>
                    <FbAddressograph
                      {patient}
                      nhsNumber={patient.nhs_number || ''}
                      surname={patient.surname || ''}
                      forenames={patient.forenames || ''}
                      title={patient.title || ''}
                      hospitalNumber={patient.hospital_number || ''}
                      dateOfBirth={patient.date_of_birth || ''}
                      sex={patient.sex || ''}
                    />
                  </button>
                  <div class="patient-list-actions">
                    <FbButton variant="primary" onclick={() => openRecord(patient.uuid)}>Open record</FbButton>
                    <FbButton variant="primary" onclick={() => openCaseNotes(patient)}>Case notes</FbButton>
                  </div>
                </div>
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    {/if}
  </section>

  <footer class="patient-list-footer bottom-control-bar">
    <FbUserName bind:value={username} />
    <FbButton variant="primary" onclick={() => returnByHref(`${base}/`)}>Back</FbButton>
  </footer>
</main>

<style>
  .patient-list-page {
    height: 100vh;
    display: flex;
    flex-direction: column;
    background: white;
  }

  .patient-list-header {
    padding: 1rem 0.8rem;
    border-bottom: 0.2rem solid #1b6ec2;
    background: white;
    box-sizing: border-box;
  }

  .patient-list-title {
    border: 0;
    background: transparent;
    color: #333;
    cursor: pointer;
    font-size: 1.8rem;
    font-weight: 700;
    line-height: 2.2rem;
    margin: 0;
    padding: 0;
    text-decoration: none;
  }

  .patient-list-main {
    flex: 1;
    overflow-y: auto;
    padding: 1.5rem;
    box-sizing: border-box;
  }

  .patient-list-muted {
    color: #666;
    font-size: 1.1rem;
  }

  .italic {
    font-style: italic;
  }

  .patient-list-table {
    width: 100%;
    border-collapse: collapse;
    background: white;
  }

  td {
    padding: 0.8rem 0;
    border-bottom: 0.1rem solid #e2e8f0;
    vertical-align: top;
  }

  .patient-list-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 1rem;
    width: 100%;
    min-width: 0;
  }

  .patient-addressograph-button {
    display: inline-block;
    flex: 0 0 auto;
    border: 0;
    background: transparent;
    cursor: pointer;
    padding: 0;
  }

  .patient-addressograph-button:hover :global(.fb-addressograph-card),
  .patient-addressograph-button:focus :global(.fb-addressograph-card) {
    box-shadow: 0 0.2rem 0.5rem rgb(0 0 0 / 8%);
    transform: scale(1.01);
  }

  .patient-list-actions {
    padding-right: 1rem;
    display: flex;
    flex-direction: column;
    gap: 0.6rem;
    justify-content: flex-end;
    align-items: stretch;
  }

  @media (max-width: 48rem) {
    .patient-list-main {
      padding: 1rem 0.5rem;
    }

    .patient-list-row {
      align-items: flex-start;
      flex-direction: column;
      gap: 0.5rem;
    }

    .patient-list-actions {
      justify-content: flex-start;
      padding-right: 0;
      padding-left: 0.1rem;
    }
  }

  .patient-list-footer {
    display: flex;
    align-items: center;
    justify-content: flex-end;
    gap: 0.8rem;
    min-height: 2.8rem;
    padding: 0.4rem 0.8rem;
    border-top: 0.2rem solid #1b6ec2;
    background: white;
    box-sizing: border-box;
  }
</style>

// reactOrig/src/PatientRegistry.tsx
import * as React from 'react';
import { useNavigate } from 'react-router';
import { fbAddressograph as Addressograph } from './components/fbAddressograph';
import { fbButton as FbButton } from './components/fbButton';
import { fbUserName as FbUserName } from './components/fbUserName';
import { createClient } from './restClient';
import PatientRecord from './PatientRecord';
import CaseNoteTracker from './caseNoteTracker/CaseNoteTracker';
import { popCntNavigation, pushCntNavigation } from './caseNoteTracker/cntNavigation';
import type { CntPatient } from './caseNoteTracker/cntStore';

const restClient = createClient();

interface Patient {
  uuid: string;
  nhs_number: string;
  surname: string;
  forenames: string;
  title: string;
  address_line1: string;
  address_line2: string;
  address_line3: string;
  address_line4: string;
  hospital_number: string;
  date_of_birth: string;
  sex: string;
}

export default function PatientRegistry() {
  const navigate = useNavigate();

  const [patients, setPatients] = React.useState<Patient[]>([]);
  const [loading, setLoading] = React.useState<boolean>(true);
  const [activePatientUuid, setActivePatientUuid] = React.useState<string | null>(null);
  const [activeCaseNotesPatient, setActiveCaseNotesPatient] = React.useState<CntPatient | null>(null);
  const [username, setUsername] = React.useState<string>('demoUser');

  const handleUsernameChange = (val: string) => {
    setUsername(val);
  };

  React.useEffect(() => {
    sessionStorage.setItem('fb_prev_main_page', '/patient-registry');
    fetchPatients();
  }, []);

  const fetchPatients = async () => {
    try {
      setLoading(true);

      // Select distinct latest versions of patients using our mock view
      // Ordered by surname (ascending), then forenames (ascending), then date_of_birth (ascending)
      const { data, error } = await restClient
        .from('patients_current')
        .select('*')
        .order('surname', { ascending: true })
        .order('forenames', { ascending: true })
        .order('date_of_birth', { ascending: true });

      if (error) {
        console.error('Error fetching patients:', error);
      } else {
        setPatients(data || []);
      }

    } catch (err) {
      console.error('Exception fetching patient registry data:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleOpenRecord = (patientUuid: string) => {
    setActivePatientUuid(patientUuid);
  };

  const handleOpenCaseNotes = (patient: Patient) => {
    pushCntNavigation({ kind: 'inline-patient-registry', label: 'Patient registry' });
    sessionStorage.setItem('fbcntUserUuid', 'bbbbbbbb-0005-4000-8000-000000000005');
    setActiveCaseNotesPatient(toCntPatient(patient));
  };

  const handleBack = () => {
    const entry = popCntNavigation();
    if (entry?.kind === 'url' && entry.url) {
      window.location.href = entry.url;
      return;
    }
    navigate('/');
  };

  return (
    <>
      {/* Registry UI container - visibility is toggled by setting style.display */}
      <div
        id="patient-registry-container"
        style={{
          height: '100vh',
          display: activePatientUuid || activeCaseNotesPatient ? 'none' : 'flex',
          flexDirection: 'column',
          fontFamily: "'Roboto', sans-serif",
          backgroundColor: 'white'
        }}
      >
        {/* Top Banner section */}
        <div style={{
          backgroundColor: 'white',
          borderBottom: '0.2rem solid rgb(27, 110, 194)',
          padding: '1rem 0.8rem',
          boxSizing: 'border-box',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between'
        }} className="flex-shrink-0">
          <h1
            style={{
              fontFamily: "'Roboto', sans-serif",
              fontSize: '1.8rem',
              fontWeight: 700,
              color: '#333',
              margin: 0,
              lineHeight: '2.2rem',
              cursor: 'pointer'
            }}
            onClick={() => navigate('/')}
          >
            Patient registry
          </h1>
        </div>

        {/* Main content container */}
        <div style={{
          flex: 1,
          padding: '1.5rem',
          overflowY: 'auto'
        }}>

          {loading ? (
            <div style={{ fontSize: '1.1rem', color: '#666' }}>Loading patients...</div>
          ) : patients.length === 0 ? (
            <div style={{ fontSize: '1.1rem', color: '#666', fontStyle: 'italic' }}>
              No patients found.
            </div>
          ) : (
            <table style={{
              width: '100%',
              borderCollapse: 'collapse',
              backgroundColor: 'white'
            }}>
              <tbody>
                {patients.map((pat) => (
                  <tr
                    key={pat.uuid}
                    style={{
                      borderBottom: '0.1rem solid #e2e8f0'
                    }}
                  >
                    <td style={{ padding: '0.8rem 0' }}>
                      <div style={{
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                        width: '100%'
                      }}>
                        <div
                          className="fb-addressograph-wrapper"
                          onClick={() => handleOpenRecord(pat.uuid)}
                          style={{
                            display: 'inline-block',
                            cursor: 'pointer'
                          }}
                          onMouseEnter={(e) => {
                            const card = e.currentTarget.querySelector('.fb-addressograph-card');
                            if (card) {
                              (card as HTMLElement).style.transform = 'scale(1.01)';
                              (card as HTMLElement).style.boxShadow = '0 0.2rem 0.5rem rgba(0,0,0,0.08)';
                            }
                          }}
                          onMouseLeave={(e) => {
                            const card = e.currentTarget.querySelector('.fb-addressograph-card');
                            if (card) {
                              (card as HTMLElement).style.transform = 'none';
                              (card as HTMLElement).style.boxShadow = 'none';
                            }
                          }}
                        >
                          <Addressograph
                            nhsNumber={pat.nhs_number}
                            surname={pat.surname}
                            forenames={pat.forenames}
                            title={pat.title}
                            addressLine1={pat.address_line1}
                            addressLine2={pat.address_line2}
                            addressLine3={pat.address_line3}
                            addressLine4={pat.address_line4}
                            hospitalNumber={pat.hospital_number}
                            dateOfBirth={pat.date_of_birth}
                            sex={pat.sex}
                          />
                        </div>
                        <div style={{
                          paddingRight: '1rem',
                          display: 'flex',
                          flexDirection: 'column',
                          alignItems: 'stretch',
                          gap: '0.6rem'
                        }}>
                          <FbButton
                            variant="primary"
                            onClick={() => handleOpenRecord(pat.uuid)}
                            id={`open-record-${pat.uuid}`}
                          >
                            Open record
                          </FbButton>
                          <FbButton
                            variant="primary"
                            onClick={() => handleOpenCaseNotes(pat)}
                            id={`open-case-notes-${pat.uuid}`}
                          >
                            Case notes
                          </FbButton>
                        </div>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}

        </div>

        {/* Footer Area with right-aligned userName input and blue/white Back button */}
        <div
          className="bottom-control-bar"
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'flex-end',
            gap: '0.8rem',
            padding: '0.4rem 0.8rem',
            backgroundColor: 'white',
            borderTop: '0.2rem solid rgb(27, 110, 194)',
            minHeight: '2.8rem',
            boxSizing: 'border-box'
          }}
        >
          <div>
            <FbUserName
              value={username}
              onChange={handleUsernameChange}
            />
          </div>
          <div>
            <FbButton variant="primary" onClick={handleBack}>
              Back
            </FbButton>
          </div>
        </div>
      </div>

      {/* Conditionally render PatientRecord to remove/add it from the DOM */}
      {activePatientUuid && (
        <PatientRecord
          inline
          patientUuid={activePatientUuid}
          username={username}
          onClose={() => setActivePatientUuid(null)}
        />
      )}
      {activeCaseNotesPatient && (
        <CaseNoteTracker
          inline
          initialPatient={activeCaseNotesPatient}
          onBack={() => setActiveCaseNotesPatient(null)}
        />
      )}
    </>
  );
}

function toCntPatient(patient: Patient): CntPatient {
  return {
    uuid: patient.uuid,
    nhsNumber: patient.nhs_number || '',
    hospitalNumber: patient.hospital_number || patient.uuid.slice(0, 8),
    name: `${patient.forenames || ''} ${patient.surname || ''}`.trim(),
    title: patient.title || '',
    surname: patient.surname || '',
    forenames: patient.forenames || '',
    addressLine1: patient.address_line1 || '',
    addressLine2: patient.address_line2 || '',
    addressLine3: patient.address_line3 || '',
    addressLine4: patient.address_line4 || '',
    dateOfBirth: patient.date_of_birth || '',
    sex: patient.sex || '',
  };
}
